"""Synthetic bounded original archives exercise policy, never claim native proof."""
from __future__ import annotations

from collections.abc import Callable, Generator
from contextlib import contextmanager
import copy
import errno
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile
from types import ModuleType, SimpleNamespace
from typing import Any, BinaryIO, cast
import unittest
from unittest.mock import patch
import zipfile

SCRIPT = Path(__file__).resolve().parents[1] / 'scripts/verify_native_wheel_proposal.py'
REPOSITORY = SCRIPT.parents[1]


def load_validator() -> ModuleType:
    name = '_native_wheel_validator_under_test'
    spec = importlib.util.spec_from_file_location(name, SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


V = load_validator()
SOURCE_SHA = 'a' * 40
PINS = {'packaging': '26.2', 'pip': '26.2.1', 'pip-tools': '7.6.1', 'urllib3': '2.8.0'}
BOOTSTRAP = b'pip==26.2.1\npip-tools==7.6.1\n'
TAGS_MODULE = b'# synthetic trusted module bytes, never imported\n'
UTILS_MODULE = b'# synthetic trusted utils bytes, never imported\n'


def digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def json_bytes(value: Any) -> bytes:
    return (json.dumps(value, sort_keys=True, indent=2) + '\n').encode()


def projection(pins: dict[str, str]) -> list[dict[str, str]]:
    return [{'name': name, 'version': pins[name]} for name in sorted(pins)]


def fingerprint(pins: dict[str, str]) -> str:
    return digest(''.join(f'{name}=={pins[name]}\n' for name in sorted(pins)).encode())


def regular_info(name: str, *, mode: int = 0o644) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name)
    info.create_system = 3
    info.external_attr = (stat.S_IFREG | mode) << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    return info


def zip_bytes(files: dict[str, bytes]) -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(output, 'w') as archive:
        for name, content in files.items():
            archive.writestr(regular_info(name), content)
    return output.getvalue()


def wheel_bytes(name: str, version: str, *, metadata_name: str | None = None, wheel_tag: str = 'py3-none-any', extras: dict[str, bytes] | None = None) -> bytes:
    parent = name.replace('-', '_') + '-' + version + '.dist-info'
    files = {
        parent + '/METADATA': f'Metadata-Version: 2.1\nName: {metadata_name or name}\nVersion: {version}\n\n'.encode(),
        parent + '/WHEEL': f'Wheel-Version: 1.0\nGenerator: independent-test\nRoot-Is-Purelib: true\nTag: {wheel_tag}\n\n'.encode(),
        name.replace('-', '_') + '/__init__.py': b'raise RuntimeError("wheel code must never execute")\n',
    }
    if name == 'packaging':
        files['packaging/tags.py'], files['packaging/utils.py'] = TAGS_MODULE, UTILS_MODULE
    files.update(extras or {})
    return zip_bytes(files)


def lock_bytes(seed: str, *, extra: str = '') -> bytes:
    # Literal independent canonical command rather than the parser's serializer.
    command = 'python -I scripts/compile_dependency_lock.py --resolver=backtracking --strip-extras --allow-unsafe --no-emit-index-url --no-emit-trusted-host --no-emit-find-links --no-emit-options --no-config "--pip-args=--isolated --disable-pip-version-check --no-input --no-cache-dir --only-binary=:all:" --output-file=' + seed + ' requirements-lock.in'
    header = '#\n# This file is autogenerated by pip-compile with Python 3.12\n# by the following command:\n#\n#    ' + command + '\n#\n'
    return (header + ''.join(f'{name}=={PINS[name]}\n' for name in sorted(PINS)) + extra).encode()


def bootstrap_projection(constraint: bytes, path: str, source_path: str = '/private/source/requirements-bootstrap.txt') -> dict[str, Any]:
    pair = {'pip': '26.2.1', 'pip-tools': '7.6.1'}
    return {'policy': 'stable', 'state': 'stable', 'source': {'path': source_path, 'sha256': digest(BOOTSTRAP), 'pin_fingerprint': fingerprint(pair), 'pins': pair}, 'constraints': [{'path': path, 'sha256': digest(constraint), 'pin_fingerprint': fingerprint(PINS), 'bootstrap_pins': pair}], 'source_transition': {'active': False, 'from': pair, 'to': pair}}


def receipt(native: dict[str, str], constraint: bytes, path: str, *, mode: str, source_path: str = '/private/source/requirements-bootstrap.txt') -> dict[str, Any]:
    installed = PINS if mode == 'complete' else {'pip': PINS['pip'], 'pip-tools': PINS['pip-tools']}
    return {
        'schema_version': 2, 'status': 'verified', 'mode': mode,
        'bootstrap': bootstrap_projection(constraint, path, source_path),
        'constraint': {'fingerprint': fingerprint(PINS), 'path': path, 'pins': projection(PINS), 'sha256': digest(constraint)},
        'required': ['pip', 'pip-tools'] if mode == 'subset' else [],
        'expected_environment': {'implementation_name': 'cpython', 'pip_version': PINS['pip'], 'platform_machine': native['machine'], 'python_full_version': native['python_version'], 'python_version': '3.12', 'sys_platform': native['sys_platform']},
        'observation': {'pip_check': {'returncode': 0, 'stdout': 'No broken requirements found.\n', 'stderr': ''}, 'pip_inspect': {'returncode': 0, 'stderr': ''}, 'environment': {'implementation_name': 'cpython', 'implementation_version': native['python_version'], 'os_name': native['os_name'], 'platform_machine': native['machine'], 'platform_python_implementation': 'CPython', 'platform_system': native['system'], 'python_full_version': native['python_version'], 'python_version': '3.12', 'sys_platform': native['sys_platform']}, 'installed': projection(installed), 'installed_fingerprint': fingerprint(installed), 'pip_inspect_schema': '1', 'pip_version': PINS['pip']}, 'errors': [],
    }


class Fixture:
    def __init__(self, root: Path, phase: str = 'discover', *, split: bool = False) -> None:
        self.root, self.phase = root, phase
        self.layout = {platform: host['seed'] for platform, host in V.HOSTS.items()}
        if split:
            self.layout['macos-arm64'] = 'constraints/requirements-macos-arm64-py312.lock'
            self.layout['macos-x64'] = 'constraints/requirements-macos-x64-py312.lock'
        self.source, self.artifacts = root / 'source', root / 'artifacts'
        self.source.mkdir()
        self.artifacts.mkdir()
        self.expected = V.ExpectedRun('Infiland/GM2Godot', SOURCE_SHA, 123, 2, phase)
        for relative in (*V.SOURCE_HELPERS, V.WORKFLOW_PATH):
            path = self.source / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            if relative.startswith('scripts/_anchored'):
                shutil.copyfile(REPOSITORY / relative, path)
            elif relative == 'scripts/verify_native_wheel_proposal.py':
                shutil.copyfile(SCRIPT, path)
            else:
                path.write_bytes(b'# trusted synthetic source fixture\n')
        (self.source / 'requirements-bootstrap.txt').write_bytes(BOOTSTRAP)
        (self.source / 'requirements.txt').write_bytes(b'urllib3==2.8.0\n')
        (self.source / 'requirements-tooling.txt').write_bytes(b'packaging==26.2\n')
        (self.source / 'requirements-lock.in').write_bytes(b'-r requirements-bootstrap.txt\n-r requirements.txt\n-r requirements-tooling.txt\n')
        for seed in self.layout.values():
            path = self.source / seed
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(lock_bytes(seed))
        self.files: dict[str, dict[str, bytes]] = {}
        for platform in V.HOSTS:
            self.files[platform] = self.build(platform)
        if phase == 'require-committed':
            for platform, host in V.HOSTS.items():
                (self.source / host['companion']).write_bytes(self.files[platform]['candidate/companion.wheels.lock'])
            for platform in V.HOSTS:
                self.files[platform] = self.build(platform)
        self.write_all()

    def build(self, platform: str) -> dict[str, bytes]:
        host = V.HOSTS[platform]
        seed_path = self.layout[platform]
        base = 'C:/private' if host['os_name'] == 'nt' else '/private'
        def native_path(suffix: str) -> str:
            return base + suffix
        bootstrap_path = native_path('/source/requirements-bootstrap.txt')
        suffix = '/Scripts/python.exe' if host['os_name'] == 'nt' else '/bin/python'
        current_python = native_path('/work/current-generator') + suffix
        candidate_python = native_path('/work/candidate-generator') + suffix
        seed = (self.source / seed_path).read_bytes()
        identity = {'repository': 'Infiland/GM2Godot', 'source_sha': SOURCE_SHA, 'run_id': 123, 'run_attempt': 2, 'platform': platform}
        native = {'python_version': host['python_version'], 'sys_platform': host['sys_platform'], 'os_name': host['os_name'], 'system': host['system'], 'machine': host['machine'], 'implementation': 'cpython'}
        tags = ['cp312-cp312-test_native', 'py3-none-any']
        observation = {'packaging_version': '26.2', 'packaging_tags_sha256': digest(TAGS_MODULE), 'packaging_utils_sha256': digest(UTILS_MODULE), 'tags': tags, 'tags_sha256': digest(('\n'.join(tags) + '\n').encode())}
        rows: list[dict[str, Any]] = []
        files: dict[str, bytes] = {}
        for name in sorted(PINS):
            filename = name.replace('-', '_') + '-' + PINS[name] + '-py3-none-any.whl'
            content = wheel_bytes(name, PINS[name])
            files['wheelhouse/' + filename] = content
            rows.append({'name': name, 'version': PINS[name], 'filename': filename, 'size': len(content), 'sha256': digest(content), 'tags': ['py3-none-any'], 'compatible_tags': ['py3-none-any']})
        companion = ''.join(f'{row["name"]}=={row["version"]} --hash=sha256:{row["sha256"]}\n' for row in rows).encode()
        inventory = {'schema_version': 1, 'identity': identity, 'native': native, 'candidate_sha256': digest(seed), 'tag_observation': observation, 'wheels': rows}
        source_names = set(V.SOURCE_HELPERS) | set(V.REQUIREMENT_ROOTS) | {V.WORKFLOW_PATH, seed_path}
        if self.phase == 'require-committed' and all((self.source / item['companion']).exists() for item in V.HOSTS.values()):
            source_names.update(item['companion'] for item in V.HOSTS.values())
            source_names.update(self.layout.values())
        source_records = {name: {'sha256': digest((self.source / name).read_bytes()), 'bytes': len((self.source / name).read_bytes())} for name in sorted(source_names)}
        commands: list[dict[str, Any]] = []
        phases: list[dict[str, Any]] = []
        compile_flags = ['--resolver=backtracking', '--strip-extras', '--allow-unsafe', '--no-emit-index-url', '--no-emit-trusted-host', '--no-emit-find-links', '--no-emit-options', '--no-config', '--pip-args=--isolated --disable-pip-version-check --no-input --no-cache-dir --only-binary=:all:']
        pip_flags = ['--isolated', '--disable-pip-version-check', '--no-input', '--no-cache-dir', '--only-binary=:all:']
        for phase in V.PHASE_ORDER:
            args: list[tuple[str, list[str]]] = []
            cwd = native_path('/source')
            if phase in ('candidate-compile', 'selfhost-compile'):
                python = current_python if phase == 'candidate-compile' else candidate_python
                cwd = native_path('/work/' + phase)
                args = [('compile', [python, '-I', 'scripts/compile_dependency_lock.py', *compile_flags, '--cache-dir=' + native_path('/work/' + phase + '-cache'), '--output-file=' + seed_path, 'requirements-lock.in'])]
            elif phase.endswith('-download'):
                house = native_path('/artifact/wheelhouse' if phase == 'first-download' else '/work/second-wheelhouse')
                args = [('download', [current_python, '-I', '-m', 'pip', *pip_flags, 'download', '--dest', house, '-r', native_path('/artifact/candidate/version.lock')])]
            elif phase.endswith('-observation'):
                args = [('observe', [current_python, '-I', native_path('/source/scripts/propose_native_wheels.py'), '--internal-observe', native_path('/work/' + phase + '.json')])]
            elif phase.endswith('-preflight') and phase != 'native-preflight':
                constraint = native_path('/artifact/inputs/seed.lock' if phase == 'current-preflight' else '/artifact/candidate/version.lock')
                args = [('preflight', [native_path('/native/python'), '-I', '-c', 'bootstrap_preflight_main', native_path('/source/scripts/verify_dependency_environment.py'), '--source', bootstrap_path, '--policy', 'stable', '--constraint', constraint, '--output', native_path('/artifact/receipts/' + phase + '.json')])]
            elif phase != 'native-preflight':
                environment = native_path('/work/' + phase)
                python = environment + suffix
                args.append(('venv', [native_path('/native/python'), '-I', '-m', 'venv', environment]))
                mode = 'subset' if phase == 'current-generator' else 'complete'
                constraint = native_path('/artifact/inputs/seed.lock' if mode == 'subset' else '/artifact/candidate/version.lock')
                for index in range(2):
                    install = [python, '-I', '-m', 'pip', *pip_flags, 'install']
                    if mode == 'subset':
                        install += ['--constraint', constraint, 'pip' if index == 0 else 'pip-tools']
                    else:
                        house = native_path('/work/second-wheelhouse' if phase == 'fresh-2' else '/artifact/wheelhouse')
                        requirement = native_path('/work/' + phase + '-pip.wheels.lock') if index == 0 else native_path('/artifact/candidate/companion.wheels.lock')
                        install += ['--require-hashes', '--no-index', '--find-links', house, '-r', requirement]
                    args.append(('install', install))
                required = ['--require', 'pip', '--require', 'pip-tools'] if mode == 'subset' else []
                args.append(('verify', [python, '-I', native_path('/source/scripts/verify_dependency_environment.py'), '--constraint', constraint, '--mode', mode, *required, '--expected-python', native['python_version'], '--expected-platform', native['sys_platform'], '--expected-machine', native['machine'], '--bootstrap', bootstrap_path, '--bootstrap-policy', 'stable', '--output', native_path('/artifact/receipts/' + phase + '.json')]))
            ids: list[int] = []
            for kind, argv in args:
                identifier = len(commands) + 1
                commands.append({'id': identifier, 'phase': phase, 'kind': kind, 'argv': argv, 'cwd': cwd, 'returncode': 0})
                ids.append(identifier)
            phases.append({'name': phase, 'returncode': 0, 'command_ids': ids})
        files.update({'inputs/source-bindings.json': json_bytes({'schema_version': 1, 'files': source_records}), 'inputs/seed.lock': seed, 'candidate/version.lock': seed, 'selfhost/version.lock': seed, 'candidate/companion.wheels.lock': companion, 'downloads/first-wheel-inventory.json': json_bytes(inventory), 'downloads/second-wheel-inventory.json': json_bytes(inventory), 'downloads/second-companion.wheels.lock': companion, 'logs/commands.jsonl': b''.join(json_bytes(row).replace(b'\n', b'') + b'\n' for row in commands)})
        for prefix, constraint, path in (('current', seed, native_path('/artifact/inputs/seed.lock')), ('candidate', seed, native_path('/artifact/candidate/version.lock'))):
            files['receipts/' + prefix + '-preflight.json'] = json_bytes({'schema_version': 1, 'status': 'verified', **bootstrap_projection(constraint, path, bootstrap_path), 'errors': []})
        for phase in ('current-generator', 'candidate-generator', 'fresh-1', 'fresh-2'):
            mode = 'subset' if phase == 'current-generator' else 'complete'
            path = native_path('/artifact/inputs/seed.lock' if mode == 'subset' else '/artifact/candidate/version.lock')
            files['receipts/' + phase + '.json'] = json_bytes(receipt(native, seed, path, mode=mode, source_path=bootstrap_path))
        files['proposal.json'] = json_bytes({'schema_version': 1, 'kind': 'native-wheel-proposal', 'status': 'verified', 'phase': self.phase, 'identity': identity, 'native': native, 'tag_observation': observation, 'files': {}, 'phases': phases, 'counts': {'pins': len(PINS), 'wheels': len(rows), 'commands': len(commands)}})
        return self.seal(files)

    @staticmethod
    def seal(files: dict[str, bytes]) -> dict[str, bytes]:
        proposal = json.loads(files['proposal.json'])
        proposal['files'] = {name: {'sha256': digest(content), 'bytes': len(content)} for name, content in files.items() if name != 'proposal.json'}
        files['proposal.json'] = json_bytes(proposal)
        return files

    def write_all(self) -> None:
        for platform in self.files:
            self.write(platform)

    def write(self, platform: str) -> None:
        directory = self.artifacts / platform
        directory.mkdir(exist_ok=True)
        archive = directory / V.archive_name(platform, self.expected)
        archive.write_bytes(zip_bytes(self.seal(self.files[platform])))

    def mutate_json(self, name: str, mutate: Callable[[Any], None], *, platform: str = 'linux-x64') -> None:
        value = json.loads(self.files[platform][name])
        mutate(value)
        self.files[platform][name] = json_bytes(value)
        self.write(platform)

    def validate(self) -> dict[str, Any]:
        return cast(dict[str, Any], V.validate_proposals(self.artifacts, self.source, self.expected))


class TestNativeWheelProposalValidation(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.fixture = Fixture(self.root)

    def assert_rejected(self, expression: str) -> None:
        with self.assertRaisesRegex(V.ProposalError, expression):
            self.fixture.validate()

    def test_four_original_archives_accept_with_honest_discovery_status(self) -> None:
        result = self.fixture.validate()
        self.assertEqual(result['status'], 'verified')
        self.assertEqual(len(result['platforms']), 4)
        self.assertEqual(result['macos_layout'], 'shared-neutral-proven')
        self.assertIs(result['discovery_establishes_committed_four_way_policy'], False)
        self.assertEqual([row['pins'] for row in result['platforms']], [4] * 4)
        self.assertFalse((self.root / 'packaging').exists())

    def test_require_committed_exact_four_companions_accept(self) -> None:
        other = self.root / 'committed'
        other.mkdir()
        fixture = Fixture(other, 'require-committed')
        self.assertIs(fixture.validate()['discovery_establishes_committed_four_way_policy'], True)
        companion = fixture.source / V.HOSTS['macos-x64']['companion']
        companion.write_bytes(companion.read_bytes() + b'# drift\n')
        with self.assertRaisesRegex(V.ProposalError, 'source/size/hash mismatch'):
            fixture.validate()

    def test_trusted_expectation_rejects_native_non_success_and_invalid_identity(self) -> None:
        for key, value in (('native_jobs_result', 'failure'), ('run_id', True), ('run_attempt', 0), ('repository', 'fork/GM2Godot'), ('source_sha', 'a' * 39), ('phase', 'automatic')):
            with self.subTest(key=key):
                data = {'repository': 'Infiland/GM2Godot', 'source_sha': SOURCE_SHA, 'run_id': 123, 'run_attempt': 2, 'phase': 'discover', 'native_jobs_result': 'success'}
                data[key] = value
                with self.assertRaises(V.ProposalError):
                    V.validate_proposals(self.fixture.artifacts, self.fixture.source, V.ExpectedRun(**data))

    def test_missing_extra_wrongly_named_and_nonregular_original_archives_reject(self) -> None:
        path = self.fixture.artifacts / 'linux-x64' / V.archive_name('linux-x64', self.fixture.expected)
        content = path.read_bytes()
        path.unlink()
        self.assert_rejected('exactly four')
        path.write_bytes(content)
        extra = path.with_name('extra.zip')
        extra.write_bytes(content)
        self.assert_rejected('exactly four')
        extra.unlink()
        outside = self.root / 'outside-archive.zip'
        path.rename(outside)
        if os.name == 'posix':
            path.symlink_to(outside)
            self.assert_rejected('not regular archive')
            path.unlink()
        os.link(outside, path)
        self.assert_rejected('physical bounded regular')

    def test_proposal_source_run_attempt_tuple_schema_and_success_are_exact(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        cases = ((['identity', 'run_id'], True), (['identity', 'run_attempt'], 3), (['identity', 'source_sha'], 'b' * 40), (['native', 'machine'], 'aarch64'), (['native', 'python_version'], '3.12.10'), (['schema_version'], True), (['status'], 'failed'), (['phase'], 'require-committed'))
        for parts, value in cases:
            with self.subTest(parts=parts):
                self.fixture.files['linux-x64'] = copy.deepcopy(original)
                def change(data: dict[str, Any]) -> None:
                    target = data
                    for key in parts[:-1]:
                        target = target[key]
                    target[parts[-1]] = value
                self.fixture.mutate_json('proposal.json', change)
                self.assert_rejected('invalid|mismatch|integer')

    def test_strict_json_duplicate_nonfinite_unknown_and_non_utf8_reject(self) -> None:
        for content in (b'{"schema_version":1,"schema_version":1}', b'{"x":NaN}', b'\xff'):
            with self.subTest(content=content), self.assertRaises(V.ProposalError):
                V.parse_json(content, 'test')
        self.fixture.mutate_json('proposal.json', lambda item: item.update(extra=True))
        self.assert_rejected('unexpected object keys')

    def test_source_bindings_include_workflow_and_all_executed_helpers(self) -> None:
        records = json.loads(self.fixture.files['linux-x64']['inputs/source-bindings.json'])['files']
        self.assertIn('.github/workflows/native-wheel-proposals.yml', records)
        self.assertEqual(set(V.SOURCE_HELPERS).difference(records), set())
        (self.fixture.source / 'scripts/compile_dependency_lock.py').write_bytes(b'# changed trusted bytes\n')
        self.assert_rejected('source/size/hash mismatch')

    def test_source_symlink_and_leaf_hardlink_reject(self) -> None:
        path = self.fixture.source / 'requirements.txt'
        old = path.read_bytes()
        path.unlink()
        target = self.root / 'outside.txt'
        target.write_bytes(old)
        if os.name == 'posix':
            path.symlink_to(target)
            self.assert_rejected('physical bounded regular')
            path.unlink()
        os.link(target, path)
        self.assert_rejected('physical bounded regular')

        # Literal cross-view models, never a claim about a native Windows mount.
        def modeled_stat(**changes: object) -> os.stat_result:
            values: dict[str, object] = {
                'st_dev': 7, 'st_ino': 71, 'st_mode': stat.S_IFREG | 0o644,
                'st_nlink': 1, 'st_size': 9, 'st_mtime_ns': 80,
                'st_ctime_ns': 90, 'st_birthtime_ns': 70,
            }
            values.update(changes)
            return cast(os.stat_result, SimpleNamespace(**values))

        named = modeled_stat()
        opened = modeled_stat(st_ctime_ns=91)
        with patch.object(V.sys, 'platform', 'win32'):
            self.assertTrue(V._same_file_views(named, opened))
            for attribute in ('st_dev', 'st_ino', 'st_mode', 'st_nlink', 'st_size', 'st_mtime_ns'):
                with self.subTest(changed_field=attribute):
                    changed = modeled_stat(**{attribute: getattr(named, attribute) + 1})
                    self.assertFalse(V._same_file_views(named, changed))
            self.assertFalse(V._same_file_views(named, modeled_stat(st_birthtime_ns=71)))
            missing_birth = modeled_stat()
            delattr(missing_birth, 'st_birthtime_ns')
            for invalid in (missing_birth, modeled_stat(st_birthtime_ns=True),
                            modeled_stat(st_birthtime_ns=70.0), modeled_stat(st_birthtime_ns=None)):
                with self.subTest(invalid_birth=getattr(invalid, 'st_birthtime_ns', 'missing')):
                    self.assertFalse(V._same_file_views(named, invalid))
                    self.assertFalse(V._same_file_views(invalid, named))
                    self.assertFalse(V._same_file_views(invalid, invalid))
        with patch.object(V.sys, 'platform', 'linux'):
            self.assertTrue(V._same_file_views(named, named))
            self.assertFalse(V._same_file_views(named, opened))

        reader_path = self.root / 'modeled-reader.txt'
        payload = b'actual bounded reader bytes'
        reader_path.write_bytes(payload)
        physical = reader_path.lstat()
        shared = {attribute: getattr(physical, attribute) for attribute in
                  ('st_dev', 'st_ino', 'st_mode', 'st_nlink', 'st_size', 'st_mtime_ns')}
        path_view = modeled_stat(**shared, st_ctime_ns=100, st_birthtime_ns=70)
        fd_view = modeled_stat(**shared, st_ctime_ns=200, st_birthtime_ns=70)
        fd_changed = modeled_stat(**shared, st_ctime_ns=201, st_birthtime_ns=70)
        actual_fstat = os.fstat
        for final_fd_view, changed in ((fd_view, False), (fd_changed, True)):
            with self.subTest(fd_ctime_changed=changed):
                owned_fd: int | None = None
                with patch.object(V.sys, 'platform', 'win32'), \
                        patch.object(Path, 'lstat', return_value=path_view), \
                        patch.object(V.os, 'fstat', side_effect=[fd_view, final_fd_view]) as observed:
                    def read_actual_file() -> None:
                        nonlocal owned_fd
                        with V._regular_file(reader_path, len(payload)) as (stream, captured):
                            owned_fd = stream.fileno()
                            self.assertIs(captured, fd_view)
                            self.assertEqual(stream.read(), payload)
                    if changed:
                        with self.assertRaisesRegex(V.ProposalError, 'file changed during read'):
                            read_actual_file()
                    else:
                        read_actual_file()
                    self.assertEqual(observed.call_count, 2)
                    self.assertEqual(path_view.st_ctime_ns, 100)
                assert owned_fd is not None
                with self.assertRaises(OSError) as closed:
                    actual_fstat(owned_fd)
                self.assertEqual(closed.exception.errno, errno.EBADF)

    def test_full_candidate_graph_authored_pins_and_selfhost_bytes_are_bound(self) -> None:
        self.fixture.files['linux-x64']['selfhost/version.lock'] += b'# drift\n'
        self.fixture.write('linux-x64')
        self.assert_rejected('selfhost raw bytes differ')
        candidate = self.fixture.files['linux-x64']['candidate/version.lock'].replace(b'urllib3==2.8.0', b'urllib3==2.7.0')
        self.fixture.files['linux-x64']['candidate/version.lock'] = candidate
        self.fixture.files['linux-x64']['selfhost/version.lock'] = candidate
        self.fixture.write('linux-x64')
        self.assert_rejected('authored requirement root')

    def test_canonical_header_is_not_dropped_to_make_two_compiles_equal(self) -> None:
        candidate = self.fixture.files['linux-x64']['candidate/version.lock'].replace(b'--allow-unsafe ', b'')
        for name in ('candidate/version.lock', 'selfhost/version.lock'):
            self.fixture.files['linux-x64'][name] = candidate
        self.fixture.write('linux-x64')
        self.assert_rejected('compile header')

    def test_actual_wheel_bytes_hash_and_size_are_independently_checked(self) -> None:
        name = next(name for name in self.fixture.files['linux-x64'] if name.endswith('.whl'))
        self.fixture.files['linux-x64'][name] += b'x'
        self.fixture.write('linux-x64')
        self.assert_rejected('actual wheel size mismatch')
        self.fixture.files['linux-x64'][name] = self.fixture.files['linux-x64'][name][:-2] + b'x'
        self.fixture.write('linux-x64')
        self.assert_rejected('actual wheel SHA256 mismatch')

    def test_wheel_metadata_filename_and_tags_are_independent(self) -> None:
        for content, expression in ((wheel_bytes('urllib3', '2.8.0', metadata_name='other'), 'METADATA/filename'), (wheel_bytes('urllib3', '2.8.0', wheel_tag='cp312-cp312-wrong'), 'WHEEL/filename')):
            with self.subTest(expression=expression), self.assertRaisesRegex(V.ProposalError, expression):
                V.inspect_wheel(io.BytesIO(content), len(content), 'urllib3-2.8.0-py3-none-any.whl')
        universal = wheel_bytes('urllib3', '2.8.0', wheel_tag='py2.py3-none-any')
        result = V.inspect_wheel(io.BytesIO(universal), len(universal), 'urllib3-2.8.0-py2.py3-none-any.whl')
        self.assertEqual(result['tags'], ['py2-none-any', 'py3-none-any'])

    def test_wheel_root_metadata_pair_allows_nested_vendor_payload_without_ambiguity(self) -> None:
        root = 'setuptools-83.0.0.dist-info'
        vendor = 'setuptools/_vendor/packaging-26.0.dist-info'
        filename = 'setuptools-83.0.0-py3-none-any.whl'
        content = wheel_bytes('setuptools', '83.0.0', extras={
            vendor + '/METADATA': b'Metadata-Version: 2.1\nName: packaging\nVersion: 26.0\n\n',
            vendor + '/WHEEL': b'Wheel-Version: 1.0\nTag: cp39-none-vendor\n\n',
            'setuptools/_vendor/wheel-0.46.3.dist-info/METADATA': b'Metadata-Version: 2.1\nName: wheel\nVersion: 0.46.3\n\n',
        })
        self.assertEqual(V.inspect_wheel(io.BytesIO(content), len(content), filename), {
            'name': 'setuptools', 'version': '83.0.0', 'tags': ['py3-none-any'],
        })
        with zipfile.ZipFile(io.BytesIO(content)) as archive:
            files = {info.filename: archive.read(info) for info in archive.infolist()}
        metadata_name, wheel_name = root + '/METADATA', root + '/WHEEL'
        cases: tuple[tuple[str, dict[str, bytes], str], ...] = (
            ('missing root METADATA', {key: value for key, value in files.items() if key != metadata_name}, 'exactly one METADATA'),
            ('missing root WHEEL', {key: value for key, value in files.items() if key != wheel_name}, 'exactly one WHEEL'),
            ('nested-only pair', {key: value for key, value in files.items() if key not in (metadata_name, wheel_name)}, 'exactly one METADATA'),
            ('second root METADATA', {**files, 'other-1.dist-info/METADATA': files[metadata_name]}, 'exactly one METADATA'),
            ('second root WHEEL', {**files, 'other-1.dist-info/WHEEL': files[wheel_name]}, 'exactly one WHEEL'),
            ('different root parents', {**{key: value for key, value in files.items() if key != wheel_name}, 'other-1.dist-info/WHEEL': files[wheel_name]}, 'root metadata parents mismatch'),
        )
        for label, members, expression in cases:
            rejected = zip_bytes(members)
            with self.subTest(label=label), self.assertRaisesRegex(V.ProposalError, expression):
                V.inspect_wheel(io.BytesIO(rejected), len(rejected), filename)

    def test_selected_packaging_bytes_and_native_tag_observation_are_bound(self) -> None:
        self.fixture.mutate_json('proposal.json', lambda item: item['tag_observation'].update(packaging_tags_sha256='b' * 64))
        self.assert_rejected('inventory provenance mismatch')
        for name in ('downloads/first-wheel-inventory.json', 'downloads/second-wheel-inventory.json'):
            self.fixture.mutate_json(name, lambda item: item['tag_observation'].update(packaging_tags_sha256='b' * 64))
        self.assert_rejected('Packaging observation source differs')

    def test_nested_inventory_numeric_identity_never_uses_python_boolean_equality(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        for name in ('downloads/first-wheel-inventory.json', 'downloads/second-wheel-inventory.json'):
            for value in (True, 2.0):
                with self.subTest(name=name, value=value):
                    self.fixture.files['linux-x64'] = copy.deepcopy(original)
                    self.fixture.mutate_json(name, lambda item: item['identity'].update(run_attempt=value))
                    self.assert_rejected('expected exact integer')

    def test_native_tags_digest_uniqueness_and_candidate_packaging_version_reject(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        changes: tuple[Callable[[Any], None], ...] = (lambda item: item.update(tags_sha256='0' * 64), lambda item: item.update(tags=item['tags'] * 2), lambda item: item.update(packaging_version='26.1'))
        for change in changes:
            self.fixture.files['linux-x64'] = copy.deepcopy(original)
            self.fixture.mutate_json('proposal.json', lambda item: change(item['tag_observation']))
            self.assert_rejected('tags digest|duplicate tags|Packaging version')

    def test_second_observation_and_companion_must_equal_first_raw_bytes(self) -> None:
        self.fixture.files['linux-x64']['downloads/second-wheel-inventory.json'] += b' '
        self.fixture.write('linux-x64')
        self.assert_rejected('two independent wheel observations differ')
        self.fixture.files['linux-x64']['downloads/second-wheel-inventory.json'] = self.fixture.files['linux-x64']['downloads/first-wheel-inventory.json']
        self.fixture.files['linux-x64']['downloads/second-companion.wheels.lock'] += b'# extra\n'
        self.fixture.write('linux-x64')
        self.assert_rejected('companion bytes differ')

    def test_complete_receipt_original_schema_runtime_coverage_and_hashes_reject(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        cases: tuple[Callable[[Any], None], ...] = (lambda item: item.update(schema_version=True), lambda item: item.update(status='failed'), lambda item: item['observation']['pip_check'].update(returncode=True), lambda item: item['observation']['environment'].update(platform_machine='arm64'), lambda item: item['constraint'].update(sha256='0' * 64), lambda item: item['observation'].update(installed=item['observation']['installed'][:-1]))
        for change in cases:
            self.fixture.files['linux-x64'] = copy.deepcopy(original)
            self.fixture.mutate_json('receipts/fresh-1.json', change)
            self.assert_rejected('verified|succeed|mismatch|fingerprint|missing packages')

    def test_fresh_receipt_byte_identity_retains_paths_outputs_and_original_schema(self) -> None:
        self.fixture.files['linux-x64']['receipts/fresh-2.json'] += b'\n'
        self.fixture.write('linux-x64')
        self.assert_rejected('normalized receipt bytes differ')
        self.fixture.files['linux-x64']['receipts/fresh-2.json'] = self.fixture.files['linux-x64']['receipts/fresh-1.json']
        self.fixture.mutate_json('receipts/fresh-2.json', lambda item: item['bootstrap']['source'].update(path='/different/bootstrap.txt'))
        self.assert_rejected('original receipt paths mismatch')

    def test_phase_outcomes_exact_ids_coverage_and_positive_counts_reject(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        cases: tuple[Callable[[Any], None], ...] = (lambda item: item['phases'][1].update(returncode=True), lambda item: item['phases'][2].update(command_ids=[]), lambda item: item['phases'].reverse(), lambda item: item['counts'].update(wheels=0), lambda item: item['counts'].update(commands=True))
        for change in cases:
            self.fixture.files['linux-x64'] = copy.deepcopy(original)
            self.fixture.mutate_json('proposal.json', change)
            self.assert_rejected('phase|count|integer')

    def test_command_hash_offline_isolation_and_cross_platform_bypasses_reject(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        for flag in ('--no-deps', '--platform=win_amd64', '--extra-index-url=https://example.invalid'):
            self.fixture.files['linux-x64'] = copy.deepcopy(original)
            rows = [json.loads(line) for line in original['logs/commands.jsonl'].splitlines()]
            rows[0]['argv'].append(flag)
            self.fixture.files['linux-x64']['logs/commands.jsonl'] = b''.join(json_bytes(row).replace(b'\n', b'') + b'\n' for row in rows)
            self.fixture.write('linux-x64')
            self.assert_rejected('forbidden pip override')
        self.fixture.files['linux-x64'] = copy.deepcopy(original)
        rows = [json.loads(line) for line in original['logs/commands.jsonl'].splitlines()]
        next(row for row in rows if row['phase'] == 'fresh-1' and row['kind'] == 'install')['argv'].remove('--require-hashes')
        self.fixture.files['linux-x64']['logs/commands.jsonl'] = b''.join(json_bytes(row).replace(b'\n', b'') + b'\n' for row in rows)
        self.fixture.write('linux-x64')
        self.assert_rejected('offline hash install flags missing')

    def test_outer_zip_unknown_traversal_duplicate_special_and_encrypted_reject(self) -> None:
        path = self.fixture.artifacts / 'linux-x64' / V.archive_name('linux-x64', self.fixture.expected)
        original = path.read_bytes()
        for name, mode in (('../escape', stat.S_IFREG), ('undeclared.txt', stat.S_IFREG), ('proposal.json', stat.S_IFLNK)):
            with self.subTest(name=name):
                path.write_bytes(original)
                with zipfile.ZipFile(path, 'a') as archive:
                    info = regular_info(name)
                    info.external_attr = (mode | 0o644) << 16
                    if name == 'proposal.json':
                        with self.assertWarnsRegex(UserWarning, 'Duplicate name'):
                            archive.writestr(info, b'x')
                    else:
                        archive.writestr(info, b'x')
                with self.assertRaisesRegex(V.ProposalError, 'unsafe|undeclared|duplicate|special'):
                    self.fixture.validate()
        path.write_bytes(original)
        raw = bytearray(original)
        position = raw.index(b'PK\x01\x02')
        raw[position + 8] |= 1
        path.write_bytes(raw)
        self.assert_rejected('encrypted ZIP')

    def test_nested_member_bound_is_separate_and_large_synthetic_vendor_layout_accepts(self) -> None:
        content = wheel_bytes('urllib3', '2.8.0', extras={f'package/module{index}.py': b'# fixture\n' for index in range(600)})
        self.assertGreater(len(zipfile.ZipFile(io.BytesIO(content)).infolist()), 512)
        self.assertEqual(V.inspect_wheel(io.BytesIO(content), len(content), 'urllib3-2.8.0-py3-none-any.whl')['name'], 'urllib3')
        with patch.object(V, 'MAX_WHEEL_MEMBERS', 512), self.assertRaisesRegex(V.ProposalError, 'member count'):
            V.inspect_wheel(io.BytesIO(content), len(content), 'urllib3-2.8.0-py3-none-any.whl')

    def test_independent_size_read_and_count_budgets_fail_closed(self) -> None:
        with patch.object(V, 'MAX_OUTER_MEMBERS', 3):
            self.assert_rejected('member count')
        with patch.object(V, 'MAX_ARCHIVE_BYTES', 10):
            self.assert_rejected('physical bounded regular')
        stream = io.BytesIO(b'x' * 20)
        reader = V._BoundedReader(stream, 20)
        with patch.object(V, 'MAX_ZIP_READ_BYTES', 10), self.assertRaisesRegex(V.ProposalError, 'read request'):
            reader.read()
        with self.assertRaisesRegex(V.ProposalError, 'outside fixed'):
            reader.seek(21)
        archive_path = self.fixture.artifacts / 'linux-x64' / V.archive_name('linux-x64', self.fixture.expected)
        initial_size = archive_path.stat().st_size
        original = V._regular_file
        consumed: list[int] = []
        changed = False
        @contextmanager
        def growing_file(path: Path, maximum: int) -> Generator[tuple[BinaryIO, os.stat_result]]:
            nonlocal changed
            with original(path, maximum) as opened:
                stream, before = cast(tuple[BinaryIO, os.stat_result], opened)
                if path != archive_path:
                    yield stream, before
                    return
                actual_read = stream.read
                def read(size: int = -1) -> bytes:
                    nonlocal changed
                    content = actual_read(size)
                    consumed.append(len(content))
                    if content and not changed:
                        with path.open('ab') as growing:
                            growing.write(b'actual growth after initial read')
                        changed = True
                    return content
                with patch.object(stream, 'read', side_effect=read):
                    yield stream, before
        with patch.object(V, '_regular_file', side_effect=growing_file):
            self.assert_rejected('outer archive grew beyond captured size')
        self.assertTrue(changed)
        self.assertEqual(sum(consumed), initial_size + 1)
        self.assertLessEqual(max(consumed), 1024 * 1024)


    def test_partial_explicit_mac_pair_and_missing_committed_companions_reject(self) -> None:
        other = self.root / 'missing'
        other.mkdir()
        fixture = Fixture(other, 'require-committed')
        (fixture.source / V.HOSTS['macos-x64']['companion']).unlink()
        with self.assertRaises(FileNotFoundError):
            fixture.validate()
        (fixture.source / 'constraints/requirements-macos-arm64-py312.lock').write_bytes(b'packaging==26.2\n')
        with self.assertRaisesRegex(V.ProposalError, 'partial explicit Mac'):
            fixture.validate()

    def test_distinct_environment_wheelhouse_cache_and_monotonic_command_proofs_reject(self) -> None:
        original = copy.deepcopy(self.fixture.files['linux-x64'])
        def reuse_environment(rows: list[dict[str, Any]]) -> None:
            for row in rows:
                if row['phase'] == 'fresh-2':
                    row['argv'] = [arg.replace('/work/fresh-2', '/work/fresh-1') for arg in row['argv']]
        def omit_venv(rows: list[dict[str, Any]]) -> None:
            next(row for row in rows if row['phase'] == 'fresh-1' and row['kind'] == 'venv')['kind'] = 'observe'
        def reuse_house(rows: list[dict[str, Any]]) -> None:
            row = next(row for row in rows if row['phase'] == 'second-download')
            row['argv'][row['argv'].index('--dest') + 1] = '/private/artifact/wheelhouse'
        def reuse_cache(rows: list[dict[str, Any]]) -> None:
            row = next(row for row in rows if row['phase'] == 'selfhost-compile')
            row['argv'] = [arg.replace('selfhost-compile-cache', 'candidate-compile-cache') for arg in row['argv']]
        def wrong_python(rows: list[dict[str, Any]]) -> None:
            next(row for row in rows if row['phase'] == 'fresh-2' and row['kind'] == 'verify')['argv'][0] = '/private/work/fresh-1/bin/python'
        cases = ((reuse_environment, 'environment root reused'), (omit_venv, 'ordered venv'), (reuse_house, 'wheelhouse destination reused'), (reuse_cache, 'cache/root reused'), (wrong_python, 'another phase environment'))
        for mutate, expression in cases:
            with self.subTest(expression=expression):
                self.fixture.files['linux-x64'] = copy.deepcopy(original)
                rows = [json.loads(line) for line in original['logs/commands.jsonl'].splitlines()]
                mutate(rows)
                self.fixture.files['linux-x64']['logs/commands.jsonl'] = b''.join(json_bytes(row).replace(b'\n', b'') + b'\n' for row in rows)
                self.fixture.write('linux-x64')
                self.assert_rejected(expression)
        self.fixture.files['linux-x64'] = copy.deepcopy(original)
        rows = [json.loads(line) for line in original['logs/commands.jsonl'].splitlines()]
        rows[0], rows[-1] = rows[-1], rows[0]
        for index, row in enumerate(rows, 1):
            row['id'] = index
        self.fixture.files['linux-x64']['logs/commands.jsonl'] = b''.join(json_bytes(row).replace(b'\n', b'') + b'\n' for row in rows)
        self.fixture.write('linux-x64')
        self.assert_rejected('phase order regressed')

    def test_explicit_committed_mac_pair_accepts_without_obsolete_neutral_lock(self) -> None:
        other = self.root / 'explicit'
        other.mkdir()
        fixture = Fixture(other, 'require-committed', split=True)
        self.assertFalse((fixture.source / 'constraints/requirements-macos-py312.lock').exists())
        result = fixture.validate()
        self.assertEqual(result['macos_layout'], 'explicit-arm64-x64-committed-and-proven')
        self.assertEqual([row['version_path'] for row in result['platforms'][1:3]], ['constraints/requirements-macos-arm64-py312.lock', 'constraints/requirements-macos-x64-py312.lock'])

    def test_source_snapshot_is_consistent_across_four_artifacts_and_publication(self) -> None:
        original = V._inspect_proposal
        changed = False
        def inspect(*args: Any, **kwargs: Any) -> dict[str, Any]:
            nonlocal changed
            result = cast(dict[str, Any], original(*args, **kwargs))
            if not changed:
                (self.fixture.source / 'scripts/compile_dependency_lock.py').write_bytes(b'# changed after first platform inspection\n')
                changed = True
            return result
        with patch.object(V, '_inspect_proposal', side_effect=inspect):
            self.assert_rejected('trusted source changed during aggregate validation')

    def test_publication_executes_only_retained_helper_snapshot_bytes(self) -> None:
        result = self.fixture.validate()
        snapshot = V._publication_snapshot(self.fixture.source)
        marker = self.root / 'must-not-execute'
        malicious = f'from pathlib import Path\nPath({str(marker)!r}).write_text("executed")\nraise RuntimeError("changed original module")\n'.encode()
        (self.fixture.source / 'scripts/_anchored_output.py').write_bytes(malicious)
        output = self.root / 'retained-acceptance.json'
        V._publish(self.fixture.source, output, result, snapshot)
        self.assertEqual(json.loads(output.read_bytes())['status'], 'verified')
        self.assertFalse(marker.exists())
        changed_snapshot = dict(snapshot)
        changed_snapshot['scripts/_anchored_output.py'] = malicious
        with self.assertRaisesRegex(V.ProposalError, 'differs from validated source bytes'):
            V._publish(self.fixture.source, self.root / 'changed.json', result, changed_snapshot)
        self.assertFalse(marker.exists())

    def test_cli_isolated_startup_unrelated_cwd_and_failure_receipt(self) -> None:
        output = self.root / 'acceptance.json'
        args = [sys.executable, '-I', str(SCRIPT), '--artifact-root', str(self.fixture.artifacts), '--source-root', str(self.fixture.source), '--repository', 'Infiland/GM2Godot', '--source-sha', SOURCE_SHA, '--run-id', '123', '--run-attempt', '2', '--phase', 'discover', '--native-jobs-result', 'success', '--output', str(output)]
        unrelated = self.root / 'unrelated'
        unrelated.mkdir()
        malicious = unrelated / 'packaging.py'
        malicious.write_text('raise RuntimeError("unrelated module must not execute")\n')
        environment = dict(os.environ, PYTHONPATH=str(unrelated))
        completed = subprocess.run(args, cwd=unrelated, env=environment, capture_output=True, text=True, timeout=10, check=False)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        self.assertEqual(json.loads(output.read_bytes())['status'], 'verified')
        nonisolated = subprocess.run([arg for arg in args if arg != '-I'], cwd=unrelated, env=environment, capture_output=True, text=True, timeout=10, check=False)
        self.assertEqual(nonisolated.returncode, 2)
        self.assertIn('requires Python isolated mode', nonisolated.stderr)
        output.unlink()
        args[args.index('--native-jobs-result') + 1] = 'cancelled'
        completed = subprocess.run(args, cwd=unrelated, env=environment, capture_output=True, text=True, timeout=10, check=False)
        self.assertEqual(completed.returncode, 2, completed.stderr)
        self.assertFalse(output.exists())
        self.assertEqual(json.loads(output.with_name('acceptance.json.failed.json').read_bytes())['status'], 'failed')

    def test_cli_writer_controls_fail_even_system_exit_zero_and_preserve_prior_bytes(self) -> None:
        output = self.root / 'acceptance.json'
        output.write_bytes(b'prior receipt')
        before = output.stat()
        args = ['--artifact-root', str(self.fixture.artifacts), '--source-root', str(self.fixture.source), '--repository', 'Infiland/GM2Godot', '--source-sha', SOURCE_SHA, '--run-id', '123', '--run-attempt', '2', '--phase', 'discover', '--native-jobs-result', 'success', '--output', str(output)]
        for error in (KeyboardInterrupt(), SystemExit(0), SystemExit(2)):
            with self.subTest(error=type(error).__name__), patch.object(V, '_publish', side_effect=error), patch('sys.stderr', new_callable=io.StringIO) as stderr:
                self.assertEqual(V.main(args), 2)
                self.assertIn('immutable candidate or prior identical receipt may remain', stderr.getvalue())
            self.assertEqual(output.read_bytes(), b'prior receipt')
            self.assertEqual(output.stat().st_ino, before.st_ino)


if __name__ == '__main__':
    unittest.main()
