# pyright: reportPrivateUsage=false, reportUnusedFunction=false, reportUnusedClass=false
from __future__ import annotations

from .model import _AssignmentOperator, _BuiltinVariableMetadata, _Token

_EOF = _Token("EOF", "")

_MULTI_CHAR_OPERATORS = (
    "??=",
    "<<=",
    ">>=",
    ":=",
    "??",
    "<=",
    ">=",
    "==",
    "!=",
    "&&",
    "||",
    "^^",
    "++",
    "--",
    "+=",
    "-=",
    "*=",
    "/=",
    "%=",
    "&=",
    "|=",
    "^=",
    "<<",
    ">>",
)

_ASSIGNMENT_OPERATORS: tuple[_AssignmentOperator, ...] = (
    "??=",
    "<<=",
    ">>=",
    ":=",
    "+=",
    "-=",
    "*=",
    "/=",
    "%=",
    "&=",
    "|=",
    "^=",
    "=",
)

_BINARY_PRECEDENCE = {
    "??": 10,
    "or": 20,
    "||": 20,
    "^^": 20,
    "and": 30,
    "&&": 30,
    "|": 40,
    "^": 50,
    "&": 60,
    "=": 70,
    "==": 70,
    "!=": 70,
    "<": 70,
    "<=": 70,
    ">": 70,
    ">=": 70,
    "<<": 80,
    ">>": 80,
    "+": 90,
    "-": 90,
    "*": 100,
    "/": 100,
    "%": 100,
    "div": 100,
    "mod": 100,
}

_UNARY_PRECEDENCE = 110
_POSTFIX_PRECEDENCE = 120
_PRIMARY_PRECEDENCE = 130
_TERNARY_PRECEDENCE = 5
_GML_IDENTIFIER_MAX_LENGTH = 64
_GENERATED_IDENTIFIER_PREFIX = "_gml_"

_RIGHT_ASSOCIATIVE = {"??"}

_GDSCRIPT_RESERVED_IDENTIFIERS = frozenset({
    "as",
    "break",
    "class",
    "class_name",
    "const",
    "continue",
    "elif",
    "else",
    "enum",
    "extends",
    "false",
    "for",
    "func",
    "if",
    "in",
    "is",
    "match",
    "null",
    "pass",
    "return",
    "self",
    "signal",
    "static",
    "super",
    "true",
    "var",
    "void",
    "when",
    "while",
})
_GML_LITERAL_IDENTIFIERS = frozenset({
    "false",
    "null",
    "self",
    "super",
    "true",
})
_GML_BUILTIN_CONSTANT_IDENTIFIERS = frozenset({
    "NaN",
    "all",
    "false",
    "infinity",
    "nan",
    "noone",
    "null",
    "pi",
    "layerelementtype_undefined",
    "layerelementtype_background",
    "layerelementtype_instance",
    "layerelementtype_oldtilemap",
    "layerelementtype_sprite",
    "layerelementtype_tilemap",
    "layerelementtype_particlesystem",
    "layerelementtype_tile",
    "layerelementtype_sequence",
    "seqdir_right",
    "seqdir_left",
    "seqplay_none",
    "seqplay_loop",
    "seqplay_pingpong",
    "seqtracktype_graphic",
    "seqtracktype_instance",
    "seqtracktype_sequence",
    "seqtracktype_audio",
    "seqtracktype_text",
    "seqtracktype_particle",
    "seqtracktype_real",
    "seqtracktype_color",
    "seqtracktype_bool",
    "texturegroup_status_unloaded",
    "texturegroup_status_loading",
    "texturegroup_status_loaded",
    "texturegroup_status_fetched",
    "video_status_closed",
    "video_status_preparing",
    "video_status_playing",
    "video_status_paused",
    "video_format_rgba",
    "video_format_yuv",
    "pointer_invalid",
    "pointer_null",
    "true",
    "undefined",
})
_DIRECT_MEMBER_TARGETS = frozenset({
    "global",
    "other",
    "self",
    "super",
})

_BOOLEAN_RESULT_BINARY_OPERATORS = frozenset({
    "&&",
    "||",
    "^^",
    "and",
    "or",
    "=",
    "==",
    "!=",
    "<",
    "<=",
    ">",
    ">=",
})

_BOOLEAN_RESULT_FUNCTIONS = frozenset({
    "bool",
    "is_array",
    "is_bool",
    "is_callable",
    "is_handle",
    "is_infinity",
    "is_int32",
    "is_int64",
    "is_method",
    "is_nan",
    "is_numeric",
    "is_ptr",
    "is_real",
    "is_string",
    "is_struct",
    "struct_exists",
    "is_undefined",
    "gamepad_button_check",
    "gamepad_button_check_pressed",
    "gamepad_button_check_released",
    "gamepad_is_connected",
    "keyboard_check",
    "keyboard_check_pressed",
    "keyboard_check_released",
    "mouse_check_button",
    "mouse_check_button_pressed",
    "mouse_check_button_released",
    "audio_is_playing",
    "buffer_exists",
    "directory_exists",
    "file_exists",
    "file_text_eof",
    "clipboard_has_text",
    "ini_key_exists",
    "ini_section_exists",
    "layer_exists",
    "part_emitter_exists",
    "part_system_exists",
    "part_type_exists",
    "room_exists",
    "sound_isplaying",
    "texture_exists",
    "texture_is_ready",
})

_ARITHMETIC_RUNTIME_FUNCTIONS = {
    "+": "gml_add",
    "-": "gml_sub",
    "*": "gml_mul",
    "%": "gml_mod",
    "mod": "gml_mod",
}

_BITWISE_RUNTIME_FUNCTIONS = {
    "&": "gml_bit_and",
    "|": "gml_bit_or",
    "^": "gml_bit_xor",
    "<<": "gml_shift_left",
    ">>": "gml_shift_right",
}

_COMPARISON_RUNTIME_FUNCTIONS = {
    "<": "gml_lt",
    "<=": "gml_lte",
    ">": "gml_gt",
    ">=": "gml_gte",
}

_DS_COLLECTIONS_FUNCTIONS = {
    "ds_exists": "gml_ds_exists",
    "ds_list_create": "gml_ds_list_create",
    "ds_list_destroy": "gml_ds_list_destroy",
    "ds_list_clear": "gml_ds_list_clear",
    "ds_list_empty": "gml_ds_list_empty",
    "ds_list_size": "gml_ds_list_size",
    "ds_list_add": "gml_ds_list_add",
    "ds_list_set": "gml_ds_list_set",
    "ds_list_delete": "gml_ds_list_delete",
    "ds_list_find_index": "gml_ds_list_find_index",
    "ds_list_find_value": "gml_ds_list_find_value",
    "ds_list_insert": "gml_ds_list_insert",
    "ds_list_replace": "gml_ds_list_replace",
    "ds_list_shuffle": "gml_ds_list_shuffle",
    "ds_list_sort": "gml_ds_list_sort",
    "ds_list_copy": "gml_ds_list_copy",
    "ds_list_read": "gml_ds_list_read",
    "ds_list_write": "gml_ds_list_write",
    "ds_list_mark_as_list": "gml_ds_list_mark_as_list",
    "ds_list_mark_as_map": "gml_ds_list_mark_as_map",
    "ds_list_is_list": "gml_ds_list_is_list",
    "ds_list_is_map": "gml_ds_list_is_map",

    "ds_stack_create": "gml_ds_stack_create",
    "ds_stack_destroy": "gml_ds_stack_destroy",
    "ds_stack_clear": "gml_ds_stack_clear",
    "ds_stack_empty": "gml_ds_stack_empty",
    "ds_stack_size": "gml_ds_stack_size",
    "ds_stack_push": "gml_ds_stack_push",
    "ds_stack_pop": "gml_ds_stack_pop",
    "ds_stack_top": "gml_ds_stack_top",
    "ds_stack_copy": "gml_ds_stack_copy",
    "ds_stack_read": "gml_ds_stack_read",
    "ds_stack_write": "gml_ds_stack_write",

    "ds_queue_create": "gml_ds_queue_create",
    "ds_queue_destroy": "gml_ds_queue_destroy",
    "ds_queue_clear": "gml_ds_queue_clear",
    "ds_queue_empty": "gml_ds_queue_empty",
    "ds_queue_size": "gml_ds_queue_size",
    "ds_queue_enqueue": "gml_ds_queue_enqueue",
    "ds_queue_dequeue": "gml_ds_queue_dequeue",
    "ds_queue_head": "gml_ds_queue_head",
    "ds_queue_tail": "gml_ds_queue_tail",
    "ds_queue_copy": "gml_ds_queue_copy",
    "ds_queue_read": "gml_ds_queue_read",
    "ds_queue_write": "gml_ds_queue_write",

    "ds_priority_create": "gml_ds_priority_create",
    "ds_priority_destroy": "gml_ds_priority_destroy",
    "ds_priority_clear": "gml_ds_priority_clear",
    "ds_priority_empty": "gml_ds_priority_empty",
    "ds_priority_size": "gml_ds_priority_size",
    "ds_priority_add": "gml_ds_priority_add",
    "ds_priority_change_priority": "gml_ds_priority_change_priority",
    "ds_priority_delete_max": "gml_ds_priority_delete_max",
    "ds_priority_delete_min": "gml_ds_priority_delete_min",
    "ds_priority_delete_value": "gml_ds_priority_delete_value",
    "ds_priority_find_max": "gml_ds_priority_find_max",
    "ds_priority_find_min": "gml_ds_priority_find_min",
    "ds_priority_find_priority": "gml_ds_priority_find_priority",
    "ds_priority_copy": "gml_ds_priority_copy",
    "ds_priority_read": "gml_ds_priority_read",
    "ds_priority_write": "gml_ds_priority_write",
}

_COMPOUND_RUNTIME_FUNCTIONS: dict[_AssignmentOperator, str] = {
    "&=": "gml_bit_and",
    "+=": "gml_add",
    "-=": "gml_sub",
    "*=": "gml_mul",
    "/=": "gml_div",
    "%=": "gml_mod",
    "<<=": "gml_shift_left",
    ">>=": "gml_shift_right",
    "|=": "gml_bit_or",
    "^=": "gml_bit_xor",
}

_OPERATOR_REPLACEMENTS = {
    "&&": "and",
    "||": "or",
    "=": "==",
    "mod": "%",
}

_NAME_REPLACEMENTS = {
    "all": "GMRuntime.gml_instance_all()",
    "application_surface": 'GMRuntime.gml_builtin_global("application_surface")',
    "buffer_bool": "9",
    "buffer_fast": "3",
    "buffer_f16": "7",
    "buffer_f32": "7",
    "buffer_f64": "8",
    "buffer_fixed": "0",
    "buffer_grow": "1",
    "buffer_s8": "2",
    "buffer_s16": "4",
    "buffer_s32": "6",
    "buffer_seek_end": "2",
    "buffer_seek_relative": "1",
    "buffer_seek_start": "0",
    "buffer_string": "10",
    "buffer_text": "11",
    "ds_type_map": "1",
    "ds_type_list": "2",
    "ds_type_stack": "3",
    "ds_type_grid": "4",
    "ds_type_queue": "5",
    "ds_type_priority": "6",
    "fa_read": "0",
    "fa_write": "1",
    "fa_readwrite": "2",
    "buffer_u8": "1",
    "buffer_u16": "3",
    "buffer_u32": "5",
    "buffer_wrap": "2",
    "c_aqua": "0xffff00",
    "c_black": "0x000000",
    "c_blue": "0xff0000",
    "c_dkgray": "0x404040",
    "c_fuchsia": "0xff00ff",
    "c_gray": "0x808080",
    "c_green": "0x008000",
    "c_lime": "0x00ff00",
    "c_ltgray": "0xc0c0c0",
    "c_maroon": "0x000080",
    "c_navy": "0x800000",
    "c_olive": "0x008080",
    "c_orange": "0x00a5ff",
    "c_purple": "0x800080",
    "c_red": "0x0000ff",
    "c_silver": "0xc0c0c0",
    "c_teal": "0x808000",
    "c_white": "0xffffff",
    "c_yellow": "0x00ffff",
    "ps_shape_rectangle": '"rectangle"',
    "ps_shape_ellipse": '"ellipse"',
    "ps_shape_diamond": '"diamond"',
    "ps_shape_line": '"line"',
    "ps_distr_linear": '"linear"',
    "ps_distr_gaussian": '"gaussian"',
    "ps_distr_invgaussian": '"invgaussian"',
    "pt_shape_pixel": '"pixel"',
    "pt_shape_disk": '"disk"',
    "pt_shape_square": '"square"',
    "pt_shape_line": '"line"',
    "pt_shape_star": '"star"',
    "pt_shape_circle": '"circle"',
    "pt_shape_ring": '"ring"',
    "pt_shape_sphere": '"sphere"',
    "pt_shape_flare": '"flare"',
    "pt_shape_spark": '"spark"',
    "pt_shape_explosion": '"explosion"',
    "pt_shape_cloud": '"cloud"',
    "pt_shape_smoke": '"smoke"',
    "pt_shape_snow": '"snow"',
    "phy_joint_anchor_1_x": '"anchor_1_x"',
    "phy_joint_anchor_1_y": '"anchor_1_y"',
    "phy_joint_anchor_2_x": '"anchor_2_x"',
    "phy_joint_anchor_2_y": '"anchor_2_y"',
    "phy_joint_reaction_force_x": '"reaction_force_x"',
    "phy_joint_reaction_force_y": '"reaction_force_y"',
    "phy_joint_reaction_torque": '"reaction_torque"',
    "phy_joint_motor_speed": '"motor_speed"',
    "phy_joint_max_motor_torque": '"max_motor_torque"',
    "phy_joint_angle": '"angle"',
    "phy_joint_speed": '"speed"',
    "phy_joint_length": '"length"',
    "phy_joint_frequency": '"frequency"',
    "phy_joint_damping_ratio": '"damping_ratio"',
    "layerelementtype_undefined": '"undefined"',
    "layerelementtype_background": '"background"',
    "layerelementtype_instance": '"instance"',
    "layerelementtype_oldtilemap": '"old_tilemap"',
    "layerelementtype_sprite": '"sprite"',
    "layerelementtype_tilemap": '"tilemap"',
    "layerelementtype_particlesystem": '"particle_system"',
    "layerelementtype_tile": '"tile"',
    "layerelementtype_sequence": '"sequence"',
    "seqdir_right": "1",
    "seqdir_left": "-1",
    "seqplay_none": "0",
    "seqplay_loop": "1",
    "seqplay_pingpong": "2",
    "seqtracktype_graphic": '"graphic"',
    "seqtracktype_instance": '"instance"',
    "seqtracktype_sequence": '"sequence"',
    "seqtracktype_audio": '"audio"',
    "seqtracktype_text": '"text"',
    "seqtracktype_particle": '"particle"',
    "seqtracktype_real": '"real"',
    "seqtracktype_color": '"color"',
    "seqtracktype_bool": '"bool"',
    "texturegroup_status_unloaded": "0",
    "texturegroup_status_loading": "1",
    "texturegroup_status_loaded": "2",
    "texturegroup_status_fetched": "3",
    "video_status_closed": "0",
    "video_status_preparing": "1",
    "video_status_playing": "2",
    "video_status_paused": "3",
    "video_format_rgba": "0",
    "video_format_yuv": "1",
    "bm_normal": "0",
    "bm_add": "1",
    "bm_subtract": "2",
    "bm_multiply": "3",
    "browser_not_a_browser": '"not_a_browser"',
    "browser_unknown": '"unknown"',
    "browser_ie": '"ie"',
    "browser_ie_mobile": '"ie_mobile"',
    "browser_edge": '"edge"',
    "browser_firefox": '"firefox"',
    "browser_chrome": '"chrome"',
    "browser_safari": '"safari"',
    "browser_safari_mobile": '"safari_mobile"',
    "browser_opera": '"opera"',
    "browser_tizen": '"tizen"',
    "browser_windows_store": '"windows_store"',
    "cull_noculling": "0",
    "cull_clockwise": "1",
    "cull_counterclockwise": "2",
    "fa_left": "0",
    "fa_center": "1",
    "fa_right": "2",
    "fa_top": "0",
    "fa_middle": "1",
    "fa_bottom": "2",
    "device_ios_ipad": '"ios_ipad"',
    "device_ios_ipad_retina": '"ios_ipad_retina"',
    "device_ios_iphone6": '"ios_iphone6"',
    "device_ios_iphone6plus": '"ios_iphone6plus"',
    "device_ios_iphone5": '"ios_iphone5"',
    "device_ios_iphone": '"ios_iphone"',
    "device_ios_iphone_retina": '"ios_iphone_retina"',
    "device_emulator": '"emulator"',
    "device_tablet": '"tablet"',
    "device_ios_unknown": '"ios_unknown"',
    "flexpanel_align": "GMRuntime.gml_flexpanel_align()",
    "flexpanel_direction": "GMRuntime.gml_flexpanel_direction()",
    "flexpanel_display": "GMRuntime.gml_flexpanel_display()",
    "flexpanel_edge": "GMRuntime.gml_flexpanel_edge()",
    "flexpanel_flex_direction": "GMRuntime.gml_flexpanel_flex_direction()",
    "flexpanel_gutter": "GMRuntime.gml_flexpanel_gutter()",
    "flexpanel_justify": "GMRuntime.gml_flexpanel_justify()",
    "flexpanel_position_type": "GMRuntime.gml_flexpanel_position_type()",
    "flexpanel_unit": "GMRuntime.gml_flexpanel_unit()",
    "flexpanel_wrap": "GMRuntime.gml_flexpanel_wrap()",
    "global": "GMRuntime.gml_global_scope()",
    "infinity": "INF",
    "NaN": "NAN",
    "nan": "NAN",
    "noone": "GMRuntime.gml_instance_noone()",
    "pi": "PI",
    "pointer_invalid": "GMRuntime.gml_pointer_invalid()",
    "pointer_null": "GMRuntime.gml_pointer_null()",
    "surface_rgba8unorm": "0",
    "surface_r8unorm": "1",
    "surface_rg8unorm": "2",
    "surface_rgba4unorm": "3",
    "surface_rgba16float": "4",
    "surface_r16float": "5",
    "surface_rgba32float": "6",
    "surface_r32float": "7",
    "tile_flip": "0x20000000",
    "tile_index_mask": "0x000fffff",
    "tile_mirror": "0x10000000",
    "tile_rotate": "0x40000000",
    "undefined": "GMRuntime.gml_undefined()",
    "vk_anykey": "0",
    "vk_nokey": "0",
    "vk_backspace": "KEY_BACKSPACE",
    "vk_tab": "KEY_TAB",
    "vk_enter": "KEY_ENTER",
    "vk_return": "KEY_ENTER",
    "vk_shift": "KEY_SHIFT",
    "vk_control": "KEY_CTRL",
    "vk_alt": "KEY_ALT",
    "vk_pause": "KEY_PAUSE",
    "vk_escape": "KEY_ESCAPE",
    "vk_space": "KEY_SPACE",
    "vk_pageup": "KEY_PAGEUP",
    "vk_pagedown": "KEY_PAGEDOWN",
    "vk_end": "KEY_END",
    "vk_home": "KEY_HOME",
    "vk_left": "KEY_LEFT",
    "vk_up": "KEY_UP",
    "vk_right": "KEY_RIGHT",
    "vk_down": "KEY_DOWN",
    "vk_insert": "KEY_INSERT",
    "vk_delete": "KEY_DELETE",
    "mb_left": "MOUSE_BUTTON_LEFT",
    "mb_right": "MOUSE_BUTTON_RIGHT",
    "mb_middle": "MOUSE_BUTTON_MIDDLE",
    "mb_any": "-1",
    "network_socket_tcp": "0",
    "network_socket_udp": "1",
    "network_socket_ws": "2",
    "network_socket_wss": "3",
    "network_type_connect": "1",
    "network_type_disconnect": "2",
    "network_type_data": "3",
    "network_connect_none": "0",
    "network_connect_blocking": "1",
    "network_connect_active": "2",
    "network_connect_nonblocking": "2",
    "network_connect_passive": "3",
    "os_windows": '"windows"',
    "os_gxgames": '"gxgames"',
    "os_linux": '"linux"',
    "os_macosx": '"macosx"',
    "os_ios": '"ios"',
    "os_tvos": '"tvos"',
    "os_android": '"android"',
    "os_ps4": '"ps4"',
    "os_ps5": '"ps5"',
    "os_gdk": '"gdk"',
    "os_xboxseriesxs": '"gdk"',
    "os_switch": '"switch"',
    "os_unknown": '"unknown"',
    "gp_face1": "JOY_BUTTON_A",
    "gp_face2": "JOY_BUTTON_B",
    "gp_face3": "JOY_BUTTON_X",
    "gp_face4": "JOY_BUTTON_Y",
    "gp_shoulderl": "JOY_BUTTON_LEFT_SHOULDER",
    "gp_shoulderr": "JOY_BUTTON_RIGHT_SHOULDER",
    "gp_select": "JOY_BUTTON_BACK",
    "gp_start": "JOY_BUTTON_START",
    "gp_stickl": "JOY_BUTTON_LEFT_STICK",
    "gp_stickr": "JOY_BUTTON_RIGHT_STICK",
    "gp_padu": "JOY_BUTTON_DPAD_UP",
    "gp_padd": "JOY_BUTTON_DPAD_DOWN",
    "gp_padl": "JOY_BUTTON_DPAD_LEFT",
    "gp_padr": "JOY_BUTTON_DPAD_RIGHT",
    "gp_axislh": "JOY_AXIS_LEFT_X",
    "gp_axislv": "JOY_AXIS_LEFT_Y",
    "gp_axisrh": "JOY_AXIS_RIGHT_X",
    "gp_axisrv": "JOY_AXIS_RIGHT_Y",
    "gp_axisltrigger": "JOY_AXIS_TRIGGER_LEFT",
    "gp_axisrtrigger": "JOY_AXIS_TRIGGER_RIGHT",
}

_BLOCK_DELIMITER_REPLACEMENTS = {
    "begin": "{",
    "end": "}",
}

_INSTANCE_NAME_REPLACEMENTS = {
    "x": "position.x",
    "y": "position.y",
}

_LEGACY_GLOBAL_BUILTINS = frozenset({"health", "lives", "score"})

_BUILTIN_VARIABLE_REGISTRY = {
    "application_surface": _BuiltinVariableMetadata("global", "undefined", False, False, "surface"),
    "argument": _BuiltinVariableMetadata("global", "[]", False, False, "script_arguments"),
    "argument_count": _BuiltinVariableMetadata("global", "0", False, False, "script_arguments"),
    "async_load": _BuiltinVariableMetadata("global", "{}", False, False, "async_event"),
    "bbox_bottom": _BuiltinVariableMetadata("instance", "0", False, False, "collision_bounds"),
    "bbox_left": _BuiltinVariableMetadata("instance", "0", False, False, "collision_bounds"),
    "bbox_right": _BuiltinVariableMetadata("instance", "0", False, False, "collision_bounds"),
    "bbox_top": _BuiltinVariableMetadata("instance", "0", False, False, "collision_bounds"),
    "browser_height": _BuiltinVariableMetadata("global", "0", False, False, "platform"),
    "browser_width": _BuiltinVariableMetadata("global", "0", False, False, "platform"),
    "current_time": _BuiltinVariableMetadata("global", "0", False, False, "time"),
    "debug_mode": _BuiltinVariableMetadata("global", "false", False, False, "debug"),
    "depth": _BuiltinVariableMetadata("instance", "0", True, False, "rendering"),
    "direction": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "event_data": _BuiltinVariableMetadata("global", "{}", False, False, "event"),
    "fps": _BuiltinVariableMetadata("global", "0", False, False, "time"),
    "fps_real": _BuiltinVariableMetadata("global", "0", False, False, "time"),
    "friction": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "gravity": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "gravity_direction": _BuiltinVariableMetadata("instance", "270", True, False, "motion"),
    "hspeed": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "id": _BuiltinVariableMetadata("instance", "undefined", False, False, "identity"),
    "image_alpha": _BuiltinVariableMetadata("instance", "1", True, False, "sprite"),
    "image_angle": _BuiltinVariableMetadata("instance", "0", True, False, "sprite"),
    "image_blend": _BuiltinVariableMetadata("instance", "16777215", True, False, "sprite"),
    "image_index": _BuiltinVariableMetadata("instance", "0", True, False, "sprite"),
    "image_number": _BuiltinVariableMetadata("instance", "0", False, False, "sprite"),
    "image_speed": _BuiltinVariableMetadata("instance", "1", True, False, "sprite"),
    "image_xscale": _BuiltinVariableMetadata("instance", "1", True, False, "sprite"),
    "image_yscale": _BuiltinVariableMetadata("instance", "1", True, False, "sprite"),
    "instance_count": _BuiltinVariableMetadata("global", "0", False, False, "instances"),
    "keyboard_key": _BuiltinVariableMetadata("global", "0", True, False, "input"),
    "keyboard_lastkey": _BuiltinVariableMetadata("global", "0", True, False, "input"),
    "keyboard_string": _BuiltinVariableMetadata("global", "", True, False, "input"),
    "layer": _BuiltinVariableMetadata("instance", "0", True, False, "rendering"),
    "mouse_x": _BuiltinVariableMetadata("global", "0", False, False, "input"),
    "mouse_y": _BuiltinVariableMetadata("global", "0", False, False, "input"),
    "mouse_wheel_down": _BuiltinVariableMetadata("global", "false", False, False, "input"),
    "mouse_wheel_up": _BuiltinVariableMetadata("global", "false", False, False, "input"),
    "object_index": _BuiltinVariableMetadata("instance", "undefined", False, False, "identity"),
    "os_browser": _BuiltinVariableMetadata("global", "browser_not_a_browser", False, False, "platform"),
    "os_device": _BuiltinVariableMetadata("global", "device_ios_unknown", False, False, "platform"),
    "os_type": _BuiltinVariableMetadata("global", "os_unknown", False, False, "platform"),
    "os_version": _BuiltinVariableMetadata("global", "0", False, False, "platform"),
    "program_directory": _BuiltinVariableMetadata("global", "", False, False, "files"),
    "path_index": _BuiltinVariableMetadata("instance", "undefined", True, False, "path"),
    "path_position": _BuiltinVariableMetadata("instance", "0", True, False, "path"),
    "path_scale": _BuiltinVariableMetadata("instance", "1", True, False, "path"),
    "path_speed": _BuiltinVariableMetadata("instance", "0", True, False, "path"),
    "room": _BuiltinVariableMetadata("global", "undefined", False, False, "room"),
    "room_height": _BuiltinVariableMetadata("global", "0", False, False, "room"),
    "room_width": _BuiltinVariableMetadata("global", "0", False, False, "room"),
    "drawn_by_sequence": _BuiltinVariableMetadata("instance", "false", False, False, "sequence"),
    "in_sequence": _BuiltinVariableMetadata("instance", "false", False, False, "sequence"),
    "sequence_instance": _BuiltinVariableMetadata("instance", "undefined", False, False, "sequence"),
    "solid": _BuiltinVariableMetadata("instance", "false", True, False, "collision"),
    "speed": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "sprite_index": _BuiltinVariableMetadata("instance", "undefined", True, False, "sprite"),
    "timeline_index": _BuiltinVariableMetadata("instance", "undefined", True, False, "timeline"),
    "timeline_loop": _BuiltinVariableMetadata("instance", "false", True, False, "timeline"),
    "timeline_position": _BuiltinVariableMetadata("instance", "0", True, False, "timeline"),
    "timeline_running": _BuiltinVariableMetadata("instance", "false", True, False, "timeline"),
    "timeline_speed": _BuiltinVariableMetadata("instance", "1", True, False, "timeline"),
    "view_angle": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_camera": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_current": _BuiltinVariableMetadata("global", "undefined", False, True, "view"),
    "view_enabled": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_hborder": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_hport": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_hspeed": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_hview": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_object": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_surface_id": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_vborder": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_visible": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_vspeed": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_wport": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_wview": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_xport": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_xview": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_yport": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "view_yview": _BuiltinVariableMetadata("global", "undefined", True, True, "view"),
    "visible": _BuiltinVariableMetadata("instance", "true", True, False, "rendering"),
    "vspeed": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "temp_directory": _BuiltinVariableMetadata("global", "", False, False, "files"),
    "webgl_enabled": _BuiltinVariableMetadata("global", "true", False, False, "platform"),
    "working_directory": _BuiltinVariableMetadata("global", "", False, False, "files"),
    "x": _BuiltinVariableMetadata("instance", "0", True, False, "transform"),
    "xprevious": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "xstart": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "y": _BuiltinVariableMetadata("instance", "0", True, False, "transform"),
    "yprevious": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
    "ystart": _BuiltinVariableMetadata("instance", "0", True, False, "motion"),
}

_BUILTIN_GLOBAL_VARIABLES = frozenset(
    name for name, metadata in _BUILTIN_VARIABLE_REGISTRY.items()
    if metadata.scope == "global" and not metadata.is_array
)
_BUILTIN_ARRAY_VARIABLES = frozenset(
    name for name, metadata in _BUILTIN_VARIABLE_REGISTRY.items()
    if metadata.is_array
)
_READ_ONLY_BUILTIN_VARIABLES = frozenset(
    name for name, metadata in _BUILTIN_VARIABLE_REGISTRY.items()
    if not metadata.mutable
)
_BUILTIN_INSTANCE_VARIABLES = frozenset(_BUILTIN_VARIABLE_REGISTRY)

_VIRTUAL_KEY_ACTIONS = {
    "vk_left": "ui_left",
    "vk_right": "ui_right",
    "vk_up": "ui_up",
    "vk_down": "ui_down",
}

_VIRTUAL_KEY_CONSTANTS = {
    "vk_shift": "KEY_SHIFT",
}

_RUNTIME_FUNCTIONS = {
    "int64": "gml_int64",
    "is_array": "is_array",
    "is_bool": "is_bool",
    "is_callable": "is_callable",
    "is_handle": "is_handle",
    "is_infinity": "is_infinity",
    "is_int32": "is_int32",
    "is_int64": "is_int64",
    "is_method": "is_method",
    "is_nan": "is_nan_value",
    "is_numeric": "is_numeric",
    "is_ptr": "is_ptr",
    "is_real": "is_real",
    "is_string": "is_string",
    "is_struct": "is_struct",
    "is_undefined": "is_undefined",
    "handle_parse": "gml_handle_parse",
    "method_get_index": "gml_method_get_index",
    "method_get_self": "gml_method_get_self",
    "real": "gml_real",
    "ptr": "gml_ptr",
    "sqrt": "gml_sqrt",
    "typeof": "gml_typeof",
    "with_targets": "gml_with_targets",
    "string": "gml_string",
    "bool": "gml_bool",
}

_MATH_RUNTIME_FUNCTIONS = {
    "abs": "gml_abs",
    "sign": "gml_sign",
    "floor": "gml_floor",
    "ceil": "gml_ceil",
    "round": "gml_round",
    "frac": "gml_frac",
    "sqr": "gml_sqr",
    "power": "gml_power",
    "exp": "gml_exp",
    "ln": "gml_ln",
    "log2": "gml_log2",
    "log10": "gml_log10",
    "clamp": "gml_clamp",
    "lerp": "gml_lerp",
    "min": "gml_min",
    "max": "gml_max",
    "sin": "gml_sin",
    "cos": "gml_cos",
    "tan": "gml_tan",
    "arcsin": "gml_arcsin",
    "arccos": "gml_arccos",
    "arctan": "gml_arctan",
    "arctan2": "gml_arctan2",
    "dsin": "gml_dsin",
    "dcos": "gml_dcos",
    "dtan": "gml_dtan",
    "darcsin": "gml_darcsin",
    "darccos": "gml_darccos",
    "darctan": "gml_darctan",
    "darctan2": "gml_darctan2",
    "degtorad": "gml_degtorad",
    "radtodeg": "gml_radtodeg",
    "point_distance": "gml_point_distance",
    "point_direction": "gml_point_direction",
    "lengthdir_x": "gml_lengthdir_x",
    "lengthdir_y": "gml_lengthdir_y",
    "angle_difference": "gml_angle_difference",
    "dot_product": "gml_dot_product",
    "dot_product_3d": "gml_dot_product_3d",
    "dot_product_normalised": "gml_dot_product_normalised",
    "dot_product_3d_normalised": "gml_dot_product_3d_normalised",
    "random": "gml_random",
    "irandom": "gml_irandom",
    "random_range": "gml_random_range",
    "irandom_range": "gml_irandom_range",
    "choose": "gml_choose",
    "randomize": "gml_randomize",
    "randomise": "gml_randomise",
    "random_set_seed": "gml_random_set_seed",
    "random_get_seed": "gml_random_get_seed",
}

_FILE_RUNTIME_FUNCTIONS = {
    "file_exists": "gml_file_exists",
    "file_delete": "gml_file_delete",
    "directory_exists": "gml_directory_exists",
    "directory_create": "gml_directory_create",
    "directory_destroy": "gml_directory_destroy",
    "file_text_open_read": "gml_file_text_open_read",
    "file_text_open_write": "gml_file_text_open_write",
    "file_text_open_append": "gml_file_text_open_append",
    "file_text_close": "gml_file_text_close",
    "file_text_eof": "gml_file_text_eof",
    "file_text_read_string": "gml_file_text_read_string",
    "file_text_readln": "gml_file_text_readln",
    "file_text_read_real": "gml_file_text_read_real",
    "file_text_write_string": "gml_file_text_write_string",
    "file_text_write_real": "gml_file_text_write_real",
    "file_text_writeln": "gml_file_text_writeln",
    "file_bin_open": "gml_file_bin_open",
    "file_bin_rewrite": "gml_file_bin_rewrite",
    "file_bin_close": "gml_file_bin_close",
    "file_bin_size": "gml_file_bin_size",
    "file_bin_position": "gml_file_bin_position",
    "file_bin_seek": "gml_file_bin_seek",
    "file_bin_read_byte": "gml_file_bin_read_byte",
    "file_bin_write_byte": "gml_file_bin_write_byte",
    "filename_name": "gml_filename_name",
    "filename_ext": "gml_filename_ext",
    "filename_dir": "gml_filename_dir",
    "filename_path": "gml_filename_path",
    "filename_change_ext": "gml_filename_change_ext",
    "ini_open": "gml_ini_open",
    "ini_close": "gml_ini_close",
    "ini_read_string": "gml_ini_read_string",
    "ini_read_real": "gml_ini_read_real",
    "ini_write_string": "gml_ini_write_string",
    "ini_write_real": "gml_ini_write_real",
    "ini_section_exists": "gml_ini_section_exists",
    "ini_key_exists": "gml_ini_key_exists",
    "ini_key_delete": "gml_ini_key_delete",
    "ini_section_delete": "gml_ini_section_delete",
    "json_encode": "gml_json_encode",
    "json_decode": "gml_json_decode",
    "json_stringify": "gml_json_stringify",
    "json_parse": "gml_json_parse",
}

_BUFFER_RUNTIME_FUNCTIONS = {
    "buffer_create": "gml_buffer_create",
    "buffer_delete": "gml_buffer_delete",
    "buffer_exists": "gml_buffer_exists",
    "buffer_tell": "gml_buffer_tell",
    "buffer_seek": "gml_buffer_seek",
    "buffer_get_size": "gml_buffer_get_size",
    "buffer_get_used_size": "gml_buffer_get_used_size",
    "buffer_resize": "gml_buffer_resize",
    "buffer_sizeof": "gml_buffer_sizeof",
    "buffer_write": "gml_buffer_write",
    "buffer_read": "gml_buffer_read",
    "buffer_peek": "gml_buffer_peek",
    "buffer_poke": "gml_buffer_poke",
    "buffer_fill": "gml_buffer_fill",
    "buffer_copy": "gml_buffer_copy",
    "buffer_save": "gml_buffer_save",
    "buffer_load": "gml_buffer_load",
    "buffer_save_ext": "gml_buffer_save_ext",
    "buffer_load_ext": "gml_buffer_load_ext",
    "buffer_save_async": "gml_buffer_save_async",
    "buffer_load_async": "gml_buffer_load_async",
    "buffer_compress": "gml_buffer_compress",
    "buffer_decompress": "gml_buffer_decompress",
    "buffer_base64_encode": "gml_buffer_base64_encode",
    "buffer_base64_decode": "gml_buffer_base64_decode",
    "buffer_md5": "gml_buffer_md5",
    "buffer_sha1": "gml_buffer_sha1",
    "buffer_sha256": "gml_buffer_sha256",
    "buffer_crc32": "gml_buffer_crc32",
}

_ASYNC_RUNTIME_FUNCTIONS = {
    "http_get": "gml_http_get",
    "http_post_string": "gml_http_post_string",
    "http_request": "gml_http_request",
}

_NETWORK_RUNTIME_FUNCTIONS = {
    "network_create_socket": "gml_network_create_socket",
    "network_create_socket_ext": "gml_network_create_socket_ext",
    "network_create_server": "gml_network_create_server",
    "network_create_server_raw": "gml_network_create_server_raw",
    "network_connect": "gml_network_connect",
    "network_connect_async": "gml_network_connect_async",
    "network_connect_raw": "gml_network_connect_raw",
    "network_connect_raw_async": "gml_network_connect_raw_async",
    "network_send_raw": "gml_network_send_raw",
    "network_send_packet": "gml_network_send_packet",
    "network_send_udp": "gml_network_send_udp",
    "network_send_udp_raw": "gml_network_send_udp_raw",
    "network_send_broadcast": "gml_network_send_broadcast",
    "network_destroy": "gml_network_destroy",
}

_PHYSICS_RUNTIME_FUNCTIONS = {
    "physics_world_create": "gml_physics_world_create",
    "physics_world_gravity": "gml_physics_world_gravity",
    "physics_world_gravity_get": "gml_physics_world_gravity_get",
    "physics_world_update_speed": "gml_physics_world_update_speed",
    "physics_pause_enable": "gml_physics_pause_enable",
    "physics_fixture_create": "gml_physics_fixture_create",
    "physics_fixture_delete": "gml_physics_fixture_delete",
    "physics_fixture_set_box_shape": "gml_physics_fixture_set_box_shape",
    "physics_fixture_set_circle_shape": "gml_physics_fixture_set_circle_shape",
    "physics_fixture_set_density": "gml_physics_fixture_set_density",
    "physics_fixture_set_friction": "gml_physics_fixture_set_friction",
    "physics_fixture_set_restitution": "gml_physics_fixture_set_restitution",
    "physics_fixture_set_linear_damping": "gml_physics_fixture_set_linear_damping",
    "physics_fixture_set_angular_damping": "gml_physics_fixture_set_angular_damping",
    "physics_fixture_set_sensor": "gml_physics_fixture_set_sensor",
    "physics_fixture_bind": "gml_physics_fixture_bind",
    "physics_apply_force": "gml_physics_apply_force",
    "physics_apply_impulse": "gml_physics_apply_impulse",
    "physics_apply_local_force": "gml_physics_apply_local_force",
    "physics_apply_local_impulse": "gml_physics_apply_local_impulse",
    "physics_apply_angular_impulse": "gml_physics_apply_angular_impulse",
    "physics_apply_torque": "gml_physics_apply_torque",
    "physics_joint_distance_create": "gml_physics_joint_distance_create",
    "physics_joint_revolute_create": "gml_physics_joint_revolute_create",
    "physics_joint_delete": "gml_physics_joint_delete",
    "physics_joint_get_value": "gml_physics_joint_get_value",
    "physics_joint_set_value": "gml_physics_joint_set_value",
    "physics_joint_enable_motor": "gml_physics_joint_enable_motor",
    "physics_mass_properties": "gml_physics_mass_properties",
}

_STRUCT_RUNTIME_FUNCTIONS = {
    "struct_exists": "gml_struct_exists",
    "struct_get": "gml_struct_get",
    "struct_get_names": "gml_struct_get_names",
    "struct_names_count": "gml_struct_names_count",
    "struct_set": "gml_struct_set",
    "struct_remove": "gml_struct_remove",
    "struct_foreach": "gml_struct_foreach",
    "static_get": "gml_static_get",
    "static_set": "gml_static_set",
    "is_instanceof": "gml_is_instanceof",
    "instanceof": "gml_instanceof",
    "variable_get_hash": "gml_variable_get_hash",
    "struct_get_from_hash": "gml_struct_get_from_hash",
    "struct_set_from_hash": "gml_struct_set_from_hash",
    "struct_exists_from_hash": "gml_struct_exists_from_hash",
    "struct_remove_from_hash": "gml_struct_remove_from_hash",
}

_VARIABLE_RUNTIME_FUNCTIONS = {
    "method_call": "gml_method_call",
    "method": "gml_method",
    "script_execute": "gml_script_execute",
    "script_exists": "gml_script_exists",
    "script_get_name": "gml_script_get_name",
    "script_get_callable": "gml_script_get_callable",
    "global_function": "gml_global_function",
    "argument_count": "gml_argument_count",
    "ref_create": "gml_ref_create",
    "variable_clone": "gml_variable_clone",
    "variable_instance_exists": "gml_variable_instance_exists",
    "variable_instance_get": "gml_variable_instance_get",
    "variable_instance_set": "gml_variable_instance_set",
    "variable_instance_get_names": "gml_variable_instance_get_names",
    "variable_instance_names_count": "gml_variable_instance_names_count",
    "variable_global_exists": "gml_variable_global_exists",
    "variable_global_get": "gml_variable_global_get",
    "variable_global_set": "gml_variable_global_set",
    "variable_struct_exists": "gml_variable_struct_exists",
    "variable_struct_get": "gml_variable_struct_get",
    "variable_struct_set": "gml_variable_struct_set",
    "variable_struct_remove": "gml_variable_struct_remove",
    "variable_struct_get_names": "gml_variable_struct_get_names",
    "variable_struct_names_count": "gml_variable_struct_names_count",
}

_DS_MAP_RUNTIME_FUNCTIONS = {
    "ds_map_create": "gml_ds_map_create",
    "ds_map_destroy": "gml_ds_map_destroy",
    "ds_map_clear": "gml_ds_map_clear",
    "ds_map_empty": "gml_ds_map_empty",
    "ds_map_size": "gml_ds_map_size",
    "ds_map_add": "gml_ds_map_add",
    "ds_map_set": "gml_ds_map_set",
    "ds_map_replace": "gml_ds_map_replace",
    "ds_map_delete": "gml_ds_map_delete",
    "ds_map_exists": "gml_ds_map_exists",
    "ds_map_find_value": "gml_ds_map_find_value",
    "ds_map_find_first": "gml_ds_map_find_first",
    "ds_map_find_last": "gml_ds_map_find_last",
    "ds_map_find_next": "gml_ds_map_find_next",
    "ds_map_find_previous": "gml_ds_map_find_previous",
    "ds_map_keys": "gml_ds_map_keys",
    "ds_map_values": "gml_ds_map_values",
    "ds_map_copy": "gml_ds_map_copy",
    "ds_map_merge": "gml_ds_map_merge",
    "ds_map_read": "gml_ds_map_read",
    "ds_map_write": "gml_ds_map_write",
    "ds_map_add_list": "gml_ds_map_add_list",
    "ds_map_add_map": "gml_ds_map_add_map",
    "ds_map_replace_list": "gml_ds_map_replace_list",
    "ds_map_replace_map": "gml_ds_map_replace_map",
    "ds_map_is_list": "gml_ds_map_is_list",
    "ds_map_is_map": "gml_ds_map_is_map",
}

_DS_GRID_FUNCTIONS = {
    "ds_grid_create": "gml_ds_grid_create",
    "ds_grid_destroy": "gml_ds_grid_destroy",
    "ds_grid_width": "gml_ds_grid_width",
    "ds_grid_height": "gml_ds_grid_height",
    "ds_grid_clear": "gml_ds_grid_clear",
    "ds_grid_resize": "gml_ds_grid_resize",
    "ds_grid_set": "gml_ds_grid_set",
    "ds_grid_get": "gml_ds_grid_get",
    "ds_grid_add": "gml_ds_grid_add",
    "ds_grid_multiply": "gml_ds_grid_multiply",
    "ds_grid_set_region": "gml_ds_grid_set_region",
    "ds_grid_get_region": "gml_ds_grid_get_region",
    "ds_grid_clear_region": "gml_ds_grid_clear_region",
    "ds_grid_add_region": "gml_ds_grid_add_region",
    "ds_grid_multiply_region": "gml_ds_grid_multiply_region",
    "ds_grid_value_exists": "gml_ds_grid_value_exists",
    "ds_grid_value_x": "gml_ds_grid_value_x",
    "ds_grid_value_y": "gml_ds_grid_value_y",
    "ds_grid_copy": "gml_ds_grid_copy",
    "ds_grid_read": "gml_ds_grid_read",
    "ds_grid_write": "gml_ds_grid_write",
}

_STRING_RUNTIME_FUNCTIONS = {
    "string_length": "gml_string_length",
    "string_char_at": "gml_string_char_at",
    "string_ord_at": "gml_string_ord_at",
    "string_copy": "gml_string_copy",
    "string_pos": "gml_string_pos",
    "string_replace": "gml_string_replace",
    "string_replace_all": "gml_string_replace_all",
    "string_delete": "gml_string_delete",
    "string_insert": "gml_string_insert",
    "string_lower": "gml_string_lower",
    "string_upper": "gml_string_upper",
    "string_trim": "gml_string_trim",
    "string_repeat": "gml_string_repeat",
    "string_digits": "gml_string_digits",
    "string_letters": "gml_string_letters",
    "string_lettersdigits": "gml_string_lettersdigits",
    "string_split": "gml_string_split",
    "string_join": "gml_string_join",
    "chr": "gml_chr",
    "ord": "gml_ord",
    "ansi_char": "gml_ansi_char",
}

_ARRAY_RUNTIME_FUNCTIONS = {
    "array_equals": "gml_array_equals",
    "array_push": "gml_array_push",
    "array_push_back": "gml_array_push_back",
    "array_create": "gml_array_create",
    "array_length_1d": "gml_array_length_1d",
    "array_resize": "gml_array_resize",
    "array_pop": "gml_array_pop",
    "array_insert": "gml_array_insert",
    "array_delete": "gml_array_delete",
    "array_sort": "gml_array_sort",
    "array_shuffle": "gml_array_shuffle",
    "array_copy": "gml_array_copy",
    "array_concat": "gml_array_concat",
    "array_contains": "gml_array_contains",
    "array_find_index": "gml_array_find_index",
    "array_filter": "gml_array_filter",
    "array_map": "gml_array_map",
    "array_reduce": "gml_array_reduce",
}

_ASSET_RUNTIME_FUNCTIONS = {
    "asset_get_index": "gml_asset_get_index",
    "asset_get_type": "gml_asset_get_type",
    "asset_get_ids": "gml_asset_get_ids",
    "asset_get_type_name": "gml_asset_get_type_name",
    "asset_get_index_from_id": "gml_asset_get_index_from_id",
    "asset_has_any_tag": "gml_asset_has_any_tag",
}

_INSTANCE_RUNTIME_FUNCTIONS = {
    "instance_create_layer": "gml_instance_create_layer",
    "instance_create_depth": "gml_instance_create_depth",
    "instance_destroy": "gml_instance_destroy",
    "instance_exists": "gml_instance_exists",
    "instance_find": "gml_instance_find",
    "instance_number": "gml_instance_number",
    "instance_nearest": "gml_instance_nearest",
    "instance_furthest": "gml_instance_furthest",
    "instance_id_get": "gml_instance_id_get",
}

_COLLISION_RUNTIME_FUNCTIONS = {
    "place_meeting": "gml_place_meeting",
    "position_meeting": "gml_position_meeting",
    "instance_place": "gml_instance_place",
    "instance_position": "gml_instance_position",
    "collision_point": "gml_collision_point",
    "collision_rectangle": "gml_collision_rectangle",
    "collision_line": "gml_collision_line",
    "collision_circle": "gml_collision_circle",
    "collision_point_list": "gml_collision_point_list",
    "collision_rectangle_list": "gml_collision_rectangle_list",
    "collision_line_list": "gml_collision_line_list",
    "collision_circle_list": "gml_collision_circle_list",
}

_MOTION_RUNTIME_FUNCTIONS = {
    "motion_set": "gml_motion_set",
    "motion_add": "gml_motion_add",
    "move_towards_point": "gml_move_towards_point",
    "move_contact_solid": "gml_move_contact_solid",
    "move_contact_all": "gml_move_contact_all",
    "move_bounce_solid": "gml_move_bounce_solid",
    "move_bounce_all": "gml_move_bounce_all",
    "move_random": "gml_move_random",
    "move_snap": "gml_move_snap",
    "place_snapped": "gml_place_snapped",
}

_PATH_RUNTIME_FUNCTIONS = {
    "path_start": "gml_path_start",
    "path_end": "gml_path_end",
    "path_get_length": "gml_path_get_length",
}

_MP_GRID_RUNTIME_FUNCTIONS = {
    "mp_grid_create": "gml_mp_grid_create",
    "mp_grid_destroy": "gml_mp_grid_destroy",
    "mp_grid_clear_all": "gml_mp_grid_clear_all",
    "mp_grid_add_cell": "gml_mp_grid_add_cell",
    "mp_grid_clear_cell": "gml_mp_grid_clear_cell",
    "mp_grid_add_rectangle": "gml_mp_grid_add_rectangle",
    "mp_grid_path": "gml_mp_grid_path",
}

_INPUT_RUNTIME_FUNCTIONS = {
    "keyboard_check": "gml_keyboard_check",
    "keyboard_check_pressed": "gml_keyboard_check_pressed",
    "keyboard_check_released": "gml_keyboard_check_released",
    "keyboard_clear": "gml_keyboard_clear",
    "keyboard_key_press": "gml_keyboard_key_press",
    "keyboard_key_release": "gml_keyboard_key_release",
    "mouse_check_button": "gml_mouse_check_button",
    "mouse_check_button_pressed": "gml_mouse_check_button_pressed",
    "mouse_check_button_released": "gml_mouse_check_button_released",
    "display_mouse_get_x": "gml_display_mouse_get_x",
    "display_mouse_get_y": "gml_display_mouse_get_y",
    "device_mouse_x_to_gui": "gml_device_mouse_x_to_gui",
    "device_mouse_y_to_gui": "gml_device_mouse_y_to_gui",
    "gamepad_is_connected": "gml_gamepad_is_connected",
    "gamepad_button_check": "gml_gamepad_button_check",
    "gamepad_button_check_pressed": "gml_gamepad_button_check_pressed",
    "gamepad_button_check_released": "gml_gamepad_button_check_released",
    "gamepad_axis_value": "gml_gamepad_axis_value",
    "gamepad_set_axis_deadzone": "gml_gamepad_set_axis_deadzone",
    "gamepad_get_axis_deadzone": "gml_gamepad_get_axis_deadzone",
    "gamepad_set_vibration": "gml_gamepad_set_vibration",
}

_AUDIO_RUNTIME_FUNCTIONS = {
    "audio_play_sound": "gml_audio_play_sound",
    "audio_stop_sound": "gml_audio_stop_sound",
    "audio_pause_sound": "gml_audio_pause_sound",
    "audio_resume_sound": "gml_audio_resume_sound",
    "audio_is_playing": "gml_audio_is_playing",
    "audio_sound_gain": "gml_audio_sound_gain",
    "audio_sound_pitch": "gml_audio_sound_pitch",
    "audio_group_load": "gml_audio_group_load",
    "audio_group_unload": "gml_audio_group_unload",
    "audio_group_is_loaded": "gml_audio_group_is_loaded",
    "audio_group_load_progress": "gml_audio_group_load_progress",
    "audio_group_name": "gml_audio_group_name",
    "audio_group_stop_all": "gml_audio_group_stop_all",
    "audio_group_set_gain": "gml_audio_group_set_gain",
    "audio_group_get_gain": "gml_audio_group_get_gain",
    "sound_play": "gml_sound_play",
    "sound_loop": "gml_sound_loop",
    "sound_stop": "gml_sound_stop",
    "sound_pause": "gml_sound_pause",
    "sound_resume": "gml_sound_resume",
    "sound_isplaying": "gml_sound_isplaying",
    "sound_volume": "gml_sound_volume",
    "sound_pitch": "gml_sound_pitch",
    "sound_global_volume": "gml_sound_global_volume",
}

_TIME_RUNTIME_FUNCTIONS = {
    "alarm_get": "gml_alarm_get",
    "alarm_set": "gml_alarm_set",
    "time_source_create": "gml_time_source_create",
    "time_source_start": "gml_time_source_start",
    "time_source_stop": "gml_time_source_stop",
    "time_source_pause": "gml_time_source_pause",
    "time_source_resume": "gml_time_source_resume",
    "time_source_destroy": "gml_time_source_destroy",
    "time_source_get_state": "gml_time_source_get_state",
    "time_source_get_period": "gml_time_source_get_period",
    "time_source_get_reps_completed": "gml_time_source_get_reps_completed",
    "time_source_get_reps_remaining": "gml_time_source_get_reps_remaining",
    "time_source_get_time_remaining": "gml_time_source_get_time_remaining",
    "call_later": "gml_call_later",
    "call_cancel": "gml_call_cancel",
}

_ROOM_RUNTIME_FUNCTIONS = {
    "room_goto": "gml_room_goto",
    "room_goto_next": "gml_room_goto_next",
    "room_goto_previous": "gml_room_goto_previous",
    "room_restart": "gml_room_restart",
    "game_restart": "gml_game_restart",
    "game_end": "gml_game_end",
    "room_exists": "gml_room_exists",
    "room_get_name": "gml_room_get_name",
    "room_get_info": "gml_room_get_info",
}

_LAYER_RUNTIME_FUNCTIONS = {
    "layer_exists": "gml_layer_exists",
    "layer_get_id": "gml_layer_get_id",
    "layer_get_id_at_depth": "gml_layer_get_id_at_depth",
    "layer_get_name": "gml_layer_get_name",
    "layer_get_all": "gml_layer_get_all",
    "layer_get_depth": "gml_layer_get_depth",
    "layer_get_x": "gml_layer_get_x",
    "layer_get_y": "gml_layer_get_y",
    "layer_get_hspeed": "gml_layer_get_hspeed",
    "layer_get_vspeed": "gml_layer_get_vspeed",
    "layer_depth": "gml_layer_depth",
    "layer_x": "gml_layer_x",
    "layer_y": "gml_layer_y",
    "layer_hspeed": "gml_layer_hspeed",
    "layer_vspeed": "gml_layer_vspeed",
    "layer_create": "gml_layer_create",
    "layer_destroy": "gml_layer_destroy",
    "layer_add_instance": "gml_layer_add_instance",
    "layer_get_all_elements": "gml_layer_get_all_elements",
    "layer_element_move": "gml_layer_element_move",
    "layer_get_element_type": "gml_layer_get_element_type",
    "layer_set_visible": "gml_layer_set_visible",
    "layer_get_visible": "gml_layer_get_visible",
}

_SEQUENCE_TIMELINE_RUNTIME_FUNCTIONS = {
    "timeline_exists": "gml_timeline_exists",
    "timeline_get_name": "gml_timeline_get_name",
    "timeline_moment_add_script": "gml_timeline_moment_add_script",
    "timeline_moment_clear": "gml_timeline_moment_clear",
    "timeline_clear": "gml_timeline_clear",
    "timeline_size": "gml_timeline_size",
    "timeline_max_moment": "gml_timeline_max_moment",
    "timeline_step": "gml_timeline_step",
    "sequence_exists": "gml_sequence_exists",
    "sequence_get": "gml_sequence_get",
    "sequence_create": "gml_sequence_create",
    "sequence_destroy": "gml_sequence_destroy",
    "layer_sequence_create": "gml_layer_sequence_create",
    "layer_sequence_destroy": "gml_layer_sequence_destroy",
    "layer_sequence_get_instance": "gml_layer_sequence_get_instance",
    "layer_sequence_headpos": "gml_layer_sequence_headpos",
    "layer_sequence_get_headpos": "gml_layer_sequence_get_headpos",
    "layer_sequence_speedscale": "gml_layer_sequence_speedscale",
    "layer_sequence_get_speedscale": "gml_layer_sequence_get_speedscale",
    "layer_sequence_headdir": "gml_layer_sequence_headdir",
    "layer_sequence_get_headdir": "gml_layer_sequence_get_headdir",
    "layer_sequence_pause": "gml_layer_sequence_pause",
    "layer_sequence_play": "gml_layer_sequence_play",
    "layer_sequence_is_paused": "gml_layer_sequence_is_paused",
    "layer_sequence_is_finished": "gml_layer_sequence_is_finished",
    "layer_sequence_step": "gml_layer_sequence_step",
}

_FLEXPANEL_RUNTIME_FUNCTIONS = {
    "flexpanel_create_node": "gml_flexpanel_create_node",
    "flexpanel_delete_node": "gml_flexpanel_delete_node",
    "flexpanel_node_insert_child": "gml_flexpanel_node_insert_child",
    "flexpanel_node_remove_child": "gml_flexpanel_node_remove_child",
    "flexpanel_node_remove_all_children": "gml_flexpanel_node_remove_all_children",
    "flexpanel_calculate_layout": "gml_flexpanel_calculate_layout",
    "flexpanel_node_set_name": "gml_flexpanel_node_set_name",
    "flexpanel_node_layout_get_position": "gml_flexpanel_node_layout_get_position",
    "flexpanel_node_get_num_children": "gml_flexpanel_node_get_num_children",
    "flexpanel_node_get_child": "gml_flexpanel_node_get_child",
    "flexpanel_node_get_child_hash": "gml_flexpanel_node_get_child_hash",
    "flexpanel_node_get_parent": "gml_flexpanel_node_get_parent",
    "flexpanel_node_get_name": "gml_flexpanel_node_get_name",
    "flexpanel_node_get_data": "gml_flexpanel_node_get_data",
    "flexpanel_node_get_struct": "gml_flexpanel_node_get_struct",
    "flexpanel_node_set_measure_function": "gml_flexpanel_node_set_measure_function",
    "flexpanel_node_get_measure_function": "gml_flexpanel_node_get_measure_function",
    "flexpanel_node_style_set_width": "gml_flexpanel_node_style_set_width",
    "flexpanel_node_style_set_height": "gml_flexpanel_node_style_set_height",
    "flexpanel_node_style_set_min_width": "gml_flexpanel_node_style_set_min_width",
    "flexpanel_node_style_set_max_width": "gml_flexpanel_node_style_set_max_width",
    "flexpanel_node_style_set_min_height": "gml_flexpanel_node_style_set_min_height",
    "flexpanel_node_style_set_max_height": "gml_flexpanel_node_style_set_max_height",
    "flexpanel_node_style_set_aspect_ratio": "gml_flexpanel_node_style_set_aspect_ratio",
    "flexpanel_node_style_set_position": "gml_flexpanel_node_style_set_position",
    "flexpanel_node_style_set_position_type": "gml_flexpanel_node_style_set_position_type",
    "flexpanel_node_style_set_margin": "gml_flexpanel_node_style_set_margin",
    "flexpanel_node_style_set_padding": "gml_flexpanel_node_style_set_padding",
    "flexpanel_node_style_set_border": "gml_flexpanel_node_style_set_border",
    "flexpanel_node_style_set_gap": "gml_flexpanel_node_style_set_gap",
    "flexpanel_node_style_set_direction": "gml_flexpanel_node_style_set_direction",
    "flexpanel_node_style_set_flex_direction": "gml_flexpanel_node_style_set_flex_direction",
    "flexpanel_node_style_set_flex_wrap": "gml_flexpanel_node_style_set_flex_wrap",
    "flexpanel_node_style_set_flex_basis": "gml_flexpanel_node_style_set_flex_basis",
    "flexpanel_node_style_set_flex_grow": "gml_flexpanel_node_style_set_flex_grow",
    "flexpanel_node_style_set_flex_shrink": "gml_flexpanel_node_style_set_flex_shrink",
    "flexpanel_node_style_set_flex": "gml_flexpanel_node_style_set_flex",
    "flexpanel_node_style_set_justify_content": "gml_flexpanel_node_style_set_justify_content",
    "flexpanel_node_style_set_align_items": "gml_flexpanel_node_style_set_align_items",
    "flexpanel_node_style_set_align_self": "gml_flexpanel_node_style_set_align_self",
    "flexpanel_node_style_set_align_content": "gml_flexpanel_node_style_set_align_content",
    "flexpanel_node_style_set_display": "gml_flexpanel_node_style_set_display",
    "flexpanel_node_style_get_width": "gml_flexpanel_node_style_get_width",
    "flexpanel_node_style_get_height": "gml_flexpanel_node_style_get_height",
    "flexpanel_node_style_get_min_width": "gml_flexpanel_node_style_get_min_width",
    "flexpanel_node_style_get_max_width": "gml_flexpanel_node_style_get_max_width",
    "flexpanel_node_style_get_min_height": "gml_flexpanel_node_style_get_min_height",
    "flexpanel_node_style_get_max_height": "gml_flexpanel_node_style_get_max_height",
    "flexpanel_node_style_get_aspect_ratio": "gml_flexpanel_node_style_get_aspect_ratio",
    "flexpanel_node_style_get_position": "gml_flexpanel_node_style_get_position",
    "flexpanel_node_style_get_position_type": "gml_flexpanel_node_style_get_position_type",
    "flexpanel_node_style_get_margin": "gml_flexpanel_node_style_get_margin",
    "flexpanel_node_style_get_padding": "gml_flexpanel_node_style_get_padding",
    "flexpanel_node_style_get_border": "gml_flexpanel_node_style_get_border",
    "flexpanel_node_style_get_gap": "gml_flexpanel_node_style_get_gap",
    "flexpanel_node_style_get_direction": "gml_flexpanel_node_style_get_direction",
    "flexpanel_node_style_get_flex_direction": "gml_flexpanel_node_style_get_flex_direction",
    "flexpanel_node_style_get_flex_wrap": "gml_flexpanel_node_style_get_flex_wrap",
    "flexpanel_node_style_get_flex_basis": "gml_flexpanel_node_style_get_flex_basis",
    "flexpanel_node_style_get_flex_grow": "gml_flexpanel_node_style_get_flex_grow",
    "flexpanel_node_style_get_flex_shrink": "gml_flexpanel_node_style_get_flex_shrink",
    "flexpanel_node_style_get_flex": "gml_flexpanel_node_style_get_flex",
    "flexpanel_node_style_get_justify_content": "gml_flexpanel_node_style_get_justify_content",
    "flexpanel_node_style_get_align_items": "gml_flexpanel_node_style_get_align_items",
    "flexpanel_node_style_get_align_self": "gml_flexpanel_node_style_get_align_self",
    "flexpanel_node_style_get_align_content": "gml_flexpanel_node_style_get_align_content",
    "flexpanel_node_style_get_display": "gml_flexpanel_node_style_get_display",
}

_OS_DEBUG_GC_RUNTIME_FUNCTIONS = {
    "os_is_paused": "gml_os_is_paused",
    "os_is_network_connected": "gml_os_is_network_connected",
    "os_get_config": "gml_os_get_config",
    "os_get_language": "gml_os_get_language",
    "os_get_region": "gml_os_get_region",
    "os_get_info": "gml_os_get_info",
    "parameter_count": "gml_parameter_count",
    "parameter_string": "gml_parameter_string",
    "environment_get_variable": "gml_environment_get_variable",
    "clipboard_has_text": "gml_clipboard_has_text",
    "clipboard_get_text": "gml_clipboard_get_text",
    "clipboard_set_text": "gml_clipboard_set_text",
    "debug_get_callstack": "gml_debug_get_callstack",
    "exception_unhandled_handler": "gml_exception_unhandled_handler",
    "show_debug_message_ext": "gml_show_debug_message_ext",
    "show_message": "gml_show_message",
    "show_error": "gml_show_error",
    "code_is_compiled": "gml_code_is_compiled",
    "gc_enable": "gml_gc_enable",
    "gc_is_enabled": "gml_gc_is_enabled",
    "gc_collect": "gml_gc_collect",
    "gc_target_frame_time": "gml_gc_target_frame_time",
    "gc_get_target_frame_time": "gml_gc_get_target_frame_time",
    "gc_get_stats": "gml_gc_get_stats",
    "weak_ref_create": "gml_weak_ref_create",
    "weak_ref_alive": "gml_weak_ref_alive",
    "weak_ref_any_alive": "gml_weak_ref_any_alive",
}

_PLATFORM_SERVICE_RUNTIME_FUNCTIONS = {
    "steam_is_initialized": "gml_steam_is_initialized",
    "browser_input_capture": "gml_browser_input_capture",
    "url_open": "gml_url_open",
    "url_open_ext": "gml_url_open_ext",
    "url_open_full": "gml_url_open_full",
    "url_get_domain": "gml_url_get_domain",
    "xboxlive_user_is_signed_in": "gml_xboxlive_user_is_signed_in",
    "xboxlive_user_is_signing_in": "gml_xboxlive_user_is_signing_in",
    "xboxlive_gamertag_for_user": "gml_xboxlive_gamertag_for_user",
    "xboxlive_show_account_picker": "gml_xboxlive_show_account_picker",
    "wallpaper_set_config": "gml_wallpaper_set_config",
    "wallpaper_set_subscriptions": "gml_wallpaper_set_subscriptions",
    "cloud_synchronise": "gml_cloud_synchronise",
    "cloud_string_save": "gml_cloud_string_save",
    "cloud_file_save": "gml_cloud_file_save",
}

_DRAW_RUNTIME_FUNCTIONS = {
    "draw_self": "gml_draw_self",
    "draw_sprite": "gml_draw_sprite",
    "draw_sprite_ext": "gml_draw_sprite_ext",
    "draw_sprite_part": "gml_draw_sprite_part",
    "draw_sprite_part_ext": "gml_draw_sprite_part_ext",
    "draw_sprite_general": "gml_draw_sprite_general",
    "draw_sprite_pos": "gml_draw_sprite_pos",
    "draw_sprite_tiled": "gml_draw_sprite_tiled",
    "draw_sprite_tiled_ext": "gml_draw_sprite_tiled_ext",
    "draw_tile": "gml_draw_tile",
    "draw_tilemap": "gml_draw_tilemap",
    "draw_set_color": "gml_draw_set_color",
    "draw_get_color": "gml_draw_get_color",
    "draw_set_alpha": "gml_draw_set_alpha",
    "draw_get_alpha": "gml_draw_get_alpha",
    "draw_set_line_width": "gml_draw_set_line_width",
    "draw_get_line_width": "gml_draw_get_line_width",
    "gpu_set_blendmode": "gml_gpu_set_blendmode",
    "gpu_get_blendmode": "gml_gpu_get_blendmode",
    "draw_set_blend_mode": "gml_draw_set_blend_mode",
    "draw_get_blend_mode": "gml_draw_get_blend_mode",
    "gpu_set_texfilter": "gml_gpu_set_texfilter",
    "gpu_get_texfilter": "gml_gpu_get_texfilter",
    "texture_set_interpolation": "gml_texture_set_interpolation",
    "texture_get_interpolation": "gml_texture_get_interpolation",
    "gpu_set_texrepeat": "gml_gpu_set_texrepeat",
    "gpu_get_texrepeat": "gml_gpu_get_texrepeat",
    "texture_set_repeat": "gml_texture_set_repeat",
    "texture_get_repeat": "gml_texture_get_repeat",
    "gpu_set_colorwriteenable": "gml_gpu_set_colorwriteenable",
    "gpu_get_colorwriteenable": "gml_gpu_get_colorwriteenable",
    "gpu_set_cullmode": "gml_gpu_set_cullmode",
    "gpu_get_cullmode": "gml_gpu_get_cullmode",
    "gpu_set_alphatestenable": "gml_gpu_set_alphatestenable",
    "gpu_get_alphatestenable": "gml_gpu_get_alphatestenable",
    "gpu_set_alphatestref": "gml_gpu_set_alphatestref",
    "gpu_get_alphatestref": "gml_gpu_get_alphatestref",
    "sprite_get_texture": "gml_sprite_get_texture",
    "sprite_get_uvs": "gml_sprite_get_uvs",
    "surface_get_texture": "gml_surface_get_texture",
    "texture_exists": "gml_texture_exists",
    "texture_get_width": "gml_texture_get_width",
    "texture_get_height": "gml_texture_get_height",
    "texture_get_texel_width": "gml_texture_get_texel_width",
    "texture_get_texel_height": "gml_texture_get_texel_height",
    "texture_get_uvs": "gml_texture_get_uvs",
    "texture_is_ready": "gml_texture_is_ready",
    "texture_prefetch": "gml_texture_prefetch",
    "texture_flush": "gml_texture_flush",
    "sprite_prefetch": "gml_sprite_prefetch",
    "sprite_flush": "gml_sprite_flush",
    "sprite_prefetch_multi": "gml_sprite_prefetch_multi",
    "sprite_flush_multi": "gml_sprite_flush_multi",
    "draw_texture_flush": "gml_draw_texture_flush",
    "draw_flush": "gml_draw_flush",
    "texture_global_scale": "gml_texture_global_scale",
    "texture_debug_messages": "gml_texture_debug_messages",
    "texturegroup_set_mode": "gml_texturegroup_set_mode",
    "texturegroup_load": "gml_texturegroup_load",
    "texturegroup_unload": "gml_texturegroup_unload",
    "texturegroup_get_status": "gml_texturegroup_get_status",
    "texturegroup_get_names": "gml_texturegroup_get_names",
    "texturegroup_get_textures": "gml_texturegroup_get_textures",
    "texturegroup_get_sprites": "gml_texturegroup_get_sprites",
    "texturegroup_get_fonts": "gml_texturegroup_get_fonts",
    "texturegroup_get_tilesets": "gml_texturegroup_get_tilesets",
    "shader_set": "gml_shader_set",
    "shader_reset": "gml_shader_reset",
    "shader_get_name": "gml_shader_get_name",
    "shader_is_compiled": "gml_shader_is_compiled",
    "shader_get_uniform": "gml_shader_get_uniform",
    "shader_get_sampler_index": "gml_shader_get_sampler_index",
    "shader_set_uniform_f": "gml_shader_set_uniform_f",
    "shader_set_uniform_i": "gml_shader_set_uniform_i",
    "shader_set_uniform_f_array": "gml_shader_set_uniform_f_array",
    "shader_set_uniform_i_array": "gml_shader_set_uniform_i_array",
    "shader_set_uniform_matrix": "gml_shader_set_uniform_matrix",
    "texture_set_stage": "gml_texture_set_stage",
    "part_system_exists": "gml_part_system_exists",
    "part_system_create": "gml_part_system_create",
    "part_system_create_layer": "gml_part_system_create_layer",
    "part_system_get_layer": "gml_part_system_get_layer",
    "part_system_layer": "gml_part_system_layer",
    "part_system_depth": "gml_part_system_depth",
    "part_system_position": "gml_part_system_position",
    "part_system_destroy": "gml_part_system_destroy",
    "part_system_clear": "gml_part_system_clear",
    "part_particles_clear": "gml_part_particles_clear",
    "part_particles_count": "gml_part_particles_count",
    "part_particles_create": "gml_part_particles_create",
    "part_type_exists": "gml_part_type_exists",
    "part_type_create": "gml_part_type_create",
    "part_type_destroy": "gml_part_type_destroy",
    "part_type_shape": "gml_part_type_shape",
    "part_type_size": "gml_part_type_size",
    "part_type_scale": "gml_part_type_scale",
    "part_type_life": "gml_part_type_life",
    "part_type_speed": "gml_part_type_speed",
    "part_type_direction": "gml_part_type_direction",
    "part_type_gravity": "gml_part_type_gravity",
    "part_type_orientation": "gml_part_type_orientation",
    "part_type_colour1": "gml_part_type_colour1",
    "part_type_colour2": "gml_part_type_colour2",
    "part_type_colour3": "gml_part_type_colour3",
    "part_type_alpha1": "gml_part_type_alpha1",
    "part_type_alpha2": "gml_part_type_alpha2",
    "part_type_alpha3": "gml_part_type_alpha3",
    "part_type_blend": "gml_part_type_blend",
    "part_type_sprite": "gml_part_type_sprite",
    "part_emitter_exists": "gml_part_emitter_exists",
    "part_emitter_create": "gml_part_emitter_create",
    "part_emitter_region": "gml_part_emitter_region",
    "part_emitter_relative": "gml_part_emitter_relative",
    "part_emitter_destroy": "gml_part_emitter_destroy",
    "part_emitter_destroy_all": "gml_part_emitter_destroy_all",
    "part_emitter_clear": "gml_part_emitter_clear",
    "part_emitter_enable": "gml_part_emitter_enable",
    "part_emitter_burst": "gml_part_emitter_burst",
    "part_emitter_stream": "gml_part_emitter_stream",
    "draw_clear": "gml_draw_clear",
    "draw_line": "gml_draw_line",
    "draw_rectangle": "gml_draw_rectangle",
    "draw_circle": "gml_draw_circle",
    "draw_triangle": "gml_draw_triangle",
    "draw_point": "gml_draw_point",
    "surface_create": "gml_surface_create",
    "surface_exists": "gml_surface_exists",
    "surface_free": "gml_surface_free",
    "surface_set_target": "gml_surface_set_target",
    "surface_reset_target": "gml_surface_reset_target",
    "surface_get_width": "gml_surface_get_width",
    "surface_get_height": "gml_surface_get_height",
    "draw_surface": "gml_draw_surface",
    "draw_surface_ext": "gml_draw_surface_ext",
    "surface_copy": "gml_surface_copy",
    "surface_save": "gml_surface_save",
    "application_surface_enable": "gml_application_surface_enable",
    "application_surface_is_enabled": "gml_application_surface_is_enabled",
    "application_surface_draw_enable": "gml_application_surface_draw_enable",
    "application_surface_is_draw_enabled": "gml_application_surface_is_draw_enabled",
    "application_get_position": "gml_application_get_position",
    "camera_create_view": "gml_camera_create_view",
    "camera_set_view_pos": "gml_camera_set_view_pos",
    "camera_set_view_size": "gml_camera_set_view_size",
    "camera_get_view_x": "gml_camera_get_view_x",
    "camera_get_view_y": "gml_camera_get_view_y",
    "camera_get_view_width": "gml_camera_get_view_width",
    "camera_get_view_height": "gml_camera_get_view_height",
    "camera_set_view_angle": "gml_camera_set_view_angle",
    "camera_get_view_angle": "gml_camera_get_view_angle",
    "display_get_gui_width": "gml_display_get_gui_width",
    "display_get_gui_height": "gml_display_get_gui_height",
    "display_set_gui_size": "gml_display_set_gui_size",
    "draw_text": "gml_draw_text",
    "draw_text_ext": "gml_draw_text_ext",
    "draw_text_transformed": "gml_draw_text_transformed",
    "draw_set_font": "gml_draw_set_font",
    "draw_get_font": "gml_draw_get_font",
    "draw_set_halign": "gml_draw_set_halign",
    "draw_get_halign": "gml_draw_get_halign",
    "draw_set_valign": "gml_draw_set_valign",
    "draw_get_valign": "gml_draw_get_valign",
    "string_width": "gml_string_width",
    "string_height": "gml_string_height",
    "string_width_ext": "gml_string_width_ext",
    "string_height_ext": "gml_string_height_ext",
}
