# pyright: reportPrivateUsage=false
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Literal, TypeAlias

GMLAPISupportStatus: TypeAlias = Literal[
    "implemented",
    "partial",
    "planned",
    "unsupported",
    "out_of_scope",
]
GMLAPISupportFlag: TypeAlias = Literal["yes", "partial", "no", "n/a"]


@dataclass(frozen=True)
class GMLAPIEntry:
    name: str
    category: str
    status: GMLAPISupportStatus
    issue_number: int
    owner_module: str
    parser_support: GMLAPISupportFlag
    emitter_support: GMLAPISupportFlag
    runtime_support: GMLAPISupportFlag
    smoke_coverage: GMLAPISupportFlag
    docs_url: str
    notes: str


@dataclass(frozen=True)
class GMLAPICategoryReport:
    category: str
    issue_number: int
    implemented: int
    partial: int
    planned: int
    unsupported: int
    out_of_scope: int

    @property
    def total(self) -> int:
        return (
            self.implemented
            + self.partial
            + self.planned
            + self.unsupported
            + self.out_of_scope
        )


_GM_DOCS = "https://manual.gamemaker.io/monthly/en"
_GODOT_DOCS = "https://docs.godotengine.org/en/stable"

_CATEGORY_ISSUE_NUMBERS = {
    "Foundation": 482,
    "Runtime Function Dispatch": 483,
    "Asset Management": 484,
    "Instances": 485,
    "Cross-Instance Addressing": 486,
    "Movement and Collisions": 487,
    "Motion Helpers": 488,
    "Paths and Motion Planning": 489,
    "Drawing Basic Forms": 490,
    "Drawing Sprites Text Fonts": 491,
    "Drawing Surfaces": 492,
    "Cameras and Display": 493,
    "Game Input": 494,
    "Audio": 495,
    "General Game Control": 496,
    "Time": 497,
    "Data Structures Sequential": 498,
    "Data Structures Maps": 499,
    "Data Structures Grids": 500,
    "Accessors": 501,
    "Arrays": 502,
    "Strings": 503,
    "Maths and Numbers": 504,
    "Files INI JSON": 505,
    "Buffers": 506,
    "Asynchronous Functions": 507,
    "Networking": 508,
    "Particles GPU Effects": 509,
    "Shaders": 510,
    "Physics": 511,
    "Script Functions": 512,
    "Preprocessor": 513,
    "Flex Panels": 514,
    "OS Compiler Debug GC": 515,
    "Platform Services": 516,
    "Extensions": 517,
    "Full-Game Fixtures": 518,
}


def _entry(
    name: str,
    category: str,
    status: GMLAPISupportStatus,
    owner_module: str,
    parser_support: GMLAPISupportFlag,
    emitter_support: GMLAPISupportFlag,
    runtime_support: GMLAPISupportFlag,
    smoke_coverage: GMLAPISupportFlag,
    docs_path: str,
    notes: str,
    issue_number: int | None = None,
) -> GMLAPIEntry:
    return GMLAPIEntry(
        name=name,
        category=category,
        status=status,
        issue_number=issue_number or _CATEGORY_ISSUE_NUMBERS[category],
        owner_module=owner_module,
        parser_support=parser_support,
        emitter_support=emitter_support,
        runtime_support=runtime_support,
        smoke_coverage=smoke_coverage,
        docs_url=f"{_GM_DOCS}/{docs_path}",
        notes=notes,
    )


_GML_API_ENTRIES: tuple[GMLAPIEntry, ...] = (
    _entry(
        "gml_api_compatibility_report",
        "Foundation",
        "implemented",
        "src.conversion.gml_transpiler_parts.gml_api_manifest",
        "n/a",
        "n/a",
        "n/a",
        "no",
        "GameMaker_Language/GML_Reference/GML_Reference.htm",
        "Python-side manifest/reporting surface for tracking GML Reference coverage.",
    ),
    _entry(
        "unsupported_gml_api_diagnostic",
        "Runtime Function Dispatch",
        "implemented",
        "src.conversion.gml_transpiler_parts.emitter",
        "n/a",
        "yes",
        "n/a",
        "no",
        "GameMaker_Language/GML_Reference/GML_Reference.htm",
        "Known but unimplemented GML built-ins fail before they are emitted as raw GDScript calls.",
    ),
    _entry(
        "asset_get_index",
        "Asset Management",
        "implemented",
        "src.conversion.asset_registry",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Asset_Management.htm",
        "Implemented through the generated GMRuntime asset registry.",
    ),
    _entry(
        "asset_get_type",
        "Asset Management",
        "implemented",
        "src.conversion.asset_registry",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Asset_Management.htm",
        "Implemented through stable registry ids and type metadata.",
    ),
    _entry(
        "asset_get_ids",
        "Asset Management",
        "implemented",
        "src.conversion.asset_registry",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Asset_Management.htm",
        "Returns generated legacy ids from the runtime asset registry.",
    ),
    _entry(
        "asset_get_type_name",
        "Asset Management",
        "implemented",
        "src.conversion.asset_registry",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Asset_Management.htm",
        "Maps registry asset types to stable display names.",
    ),
    _entry(
        "asset_get_index_from_id",
        "Asset Management",
        "implemented",
        "src.conversion.asset_registry",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Asset_Management.htm",
        "Resolves generated legacy ids back to stable runtime asset indices.",
    ),
    _entry(
        "asset_has_any_tag",
        "Asset Management",
        "implemented",
        "src.conversion.asset_registry",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Asset_Management.htm",
        "Uses generated tag metadata when GameMaker resources include it.",
    ),
    _entry(
        "instance_create_layer",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Instantiates generated object scenes and registers live instances through GMRuntime.",
    ),
    _entry(
        "instance_create_depth",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Instantiates generated object scenes with depth metadata and registry handles.",
    ),
    _entry(
        "instance_destroy",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Runs destroy callbacks, unregisters instances, and queues Godot nodes for deletion.",
    ),
    _entry(
        "instance_exists",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Queries live instance registry entries by instance id, object selector, or keyword.",
    ),
    _entry(
        "instance_find",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Returns stable handles from creation-ordered object selector matches.",
    ),
    _entry(
        "instance_number",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Counts live registry matches including inherited object selectors.",
    ),
    _entry(
        "instance_nearest",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Selects the nearest live instance using Godot Node2D positions.",
    ),
    _entry(
        "instance_furthest",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Selects the furthest live instance using Godot Node2D positions.",
    ),
    _entry(
        "instance_id_get",
        "Instances",
        "implemented",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Instances/Instances.htm",
        "Returns creation-ordered live instance handles from the runtime registry.",
    ),
    _entry(
        "with",
        "Cross-Instance Addressing",
        "partial",
        "src.conversion.gml_transpiler_parts.statement_parser",
        "yes",
        "partial",
        "partial",
        "no",
        "GameMaker_Language/GML_Overview/Language_Features.htm",
        "Basic with-target execution exists; object selector and parent-chain dispatch is planned.",
    ),
    _entry(
        "variable_instance_get",
        "Cross-Instance Addressing",
        "implemented",
        "src.conversion.gml_runtime_parts.segments.40_arrays_structs_variables",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Variable_Functions/Variable_Functions.htm",
        "Implemented through instance keyword and runtime variable helpers.",
    ),
    _entry(
        "place_meeting",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Implemented as generated-shape bounding-box queries; precise masks emit a warning and use bbox approximation.",
    ),
    _entry(
        "position_meeting",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Implemented as generated-shape bounding-box point queries.",
    ),
    _entry(
        "instance_place",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Returns matching registered instance handles using generated collision shape bounds.",
    ),
    _entry(
        "instance_position",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Returns matching registered instance handles using generated collision shape bounds.",
    ),
    _entry(
        "collision_point",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Supports selectors, notme, and bbox approximation for precise masks.",
    ),
    _entry(
        "collision_rectangle",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Supports selectors, notme, and bbox approximation for precise masks.",
    ),
    _entry(
        "collision_line",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Supports selectors, notme, and bbox approximation for precise masks.",
    ),
    _entry(
        "collision_circle",
        "Movement and Collisions",
        "partial",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "yes",
        "yes",
        "partial",
        "yes",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Supports selectors, notme, and bbox approximation for precise masks.",
    ),
    _entry(
        "collision_point_list",
        "Movement and Collisions",
        "planned",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Deferred until DS list handles are available.",
    ),
    _entry(
        "collision_rectangle_list",
        "Movement and Collisions",
        "planned",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Deferred until DS list handles are available.",
    ),
    _entry(
        "collision_line_list",
        "Movement and Collisions",
        "planned",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Deferred until DS list handles are available.",
    ),
    _entry(
        "collision_circle_list",
        "Movement and Collisions",
        "planned",
        "src.conversion.gml_runtime_parts.segments.45_collision_queries",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Deferred until DS list handles are available.",
    ),
    _entry(
        "motion_set",
        "Motion Helpers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Requires synchronized speed/direction/hspeed/vspeed built-ins.",
    ),
    _entry(
        "move_towards_point",
        "Motion Helpers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Requires GameMaker angle and coordinate convention wrappers.",
    ),
    _entry(
        "path_start",
        "Paths and Motion Planning",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Requires converted path asset registry and per-instance path state.",
    ),
    _entry(
        "mp_grid_path",
        "Paths and Motion Planning",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Movement_And_Collisions/Movement_And_Collisions.htm",
        "Likely maps to a compatibility wrapper over AStarGrid2D.",
    ),
    _entry(
        "draw_line",
        "Drawing Basic Forms",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Basic_Forms/Basic_Forms.htm",
        "Requires active draw context and CanvasItem draw bridge.",
    ),
    _entry(
        "draw_rectangle",
        "Drawing Basic Forms",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Basic_Forms/Basic_Forms.htm",
        "Requires draw state for color, alpha, fill, and outline semantics.",
    ),
    _entry(
        "draw_sprite",
        "Drawing Sprites Text Fonts",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Sprites_And_Tiles/Sprites_And_Tiles.htm",
        "Requires sprite asset registry lookup and draw-event context.",
    ),
    _entry(
        "draw_text",
        "Drawing Sprites Text Fonts",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Text/Text.htm",
        "Requires font state, alignment state, and text measurement parity.",
    ),
    _entry(
        "surface_create",
        "Drawing Surfaces",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Surfaces/Surfaces.htm",
        "Requires handle-backed SubViewport or render target wrapper.",
    ),
    _entry(
        "surface_set_target",
        "Drawing Surfaces",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Surfaces/Surfaces.htm",
        "Requires draw target stack and invalid surface checks.",
    ),
    _entry(
        "camera_create_view",
        "Cameras and Display",
        "planned",
        "src.conversion.rooms",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Cameras_And_Display/Cameras_And_Display.htm",
        "Requires runtime camera/view manager in addition to room conversion metadata.",
    ),
    _entry(
        "display_get_gui_width",
        "Cameras and Display",
        "planned",
        "src.conversion.rooms",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Cameras_And_Display/Cameras_And_Display.htm",
        "Requires GUI coordinate space state.",
    ),
    _entry(
        "keyboard_check",
        "Game Input",
        "partial",
        "src.conversion.gml_transpiler_parts.emitter",
        "n/a",
        "partial",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Game_Input/Game_Input.htm",
        "Only selected virtual key constants lower directly to Godot Input today.",
    ),
    _entry(
        "mouse_check_button",
        "Game Input",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Game_Input/Game_Input.htm",
        "Requires frame-accurate input bridge.",
    ),
    _entry(
        "gamepad_button_check",
        "Game Input",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Game_Input/Game_Input.htm",
        "Requires gamepad constants, device mapping, and per-frame edge tracking.",
    ),
    _entry(
        "audio_play_sound",
        "Audio",
        "planned",
        "src.conversion.sounds",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Sounds/Sounds.htm",
        "Requires runtime audio manager and sound instance handles.",
    ),
    _entry(
        "audio_stop_sound",
        "Audio",
        "planned",
        "src.conversion.sounds",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Asset_Management/Sounds/Sounds.htm",
        "Requires sound instance lookup and AudioStreamPlayer lifecycle management.",
    ),
    _entry(
        "room_goto",
        "General Game Control",
        "planned",
        "src.conversion.rooms",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/General_Game_Control/General_Game_Control.htm",
        "Requires room manager and GameMaker lifecycle event ordering.",
    ),
    _entry(
        "game_restart",
        "General Game Control",
        "planned",
        "src.conversion.rooms",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/General_Game_Control/General_Game_Control.htm",
        "Requires generated project root/runtime reset policy.",
    ),
    _entry(
        "alarm_set",
        "Time",
        "planned",
        "src.conversion.events.mappings.core",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Time_Sources/Time_Sources.htm",
        "Alarm events are mapped, but alarm array/function runtime is not implemented.",
    ),
    _entry(
        "time_source_create",
        "Time",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Time_Sources/Time_Sources.htm",
        "Requires custom scheduler for frame/seconds mode and callback dispatch.",
    ),
    _entry(
        "ds_list_create",
        "Data Structures Sequential",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Data_Structures/DS_Lists/DS_Lists.htm",
        "Requires handle-backed DS list runtime.",
    ),
    _entry(
        "ds_queue_enqueue",
        "Data Structures Sequential",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Data_Structures/Data_Structures.htm",
        "Requires handle-backed DS queue runtime.",
    ),
    _entry(
        "ds_map_find_value",
        "Data Structures Maps",
        "partial",
        "src.conversion.gml_runtime_parts.segments.40_arrays_structs_variables",
        "n/a",
        "yes",
        "partial",
        "no",
        "GameMaker_Language/GML_Reference/Data_Structures/DS_Maps/DS_Maps.htm",
        "Direct value lookup exists; map lifecycle and JSON marking are planned.",
    ),
    _entry(
        "ds_map_create",
        "Data Structures Maps",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Data_Structures/DS_Maps/DS_Maps.htm",
        "Requires handle-backed DS map lifecycle.",
    ),
    _entry(
        "ds_grid_create",
        "Data Structures Grids",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Data_Structures/DS_Grids/DS_Grids.htm",
        "Requires handle-backed 2D grid runtime and grid accessor parsing.",
    ),
    _entry(
        "ds_grid_get",
        "Data Structures Grids",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Data_Structures/DS_Grids/DS_Grids.htm",
        "Requires coordinate coercion and invalid-handle behavior.",
    ),
    _entry(
        "array_accessor",
        "Accessors",
        "implemented",
        "src.conversion.gml_transpiler_parts.expression_parser",
        "yes",
        "yes",
        "partial",
        "no",
        "GameMaker_Language/GML_Overview/Accessors.htm",
        "Normal array indexing lowers through GMRuntime array get/set helpers.",
    ),
    _entry(
        "ds_list_accessor",
        "Accessors",
        "planned",
        "src.conversion.gml_transpiler_parts.expression_parser",
        "no",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Overview/Accessors.htm",
        "The [|] accessor still needs parser, emitter, assignment, and runtime support.",
    ),
    _entry(
        "ds_grid_accessor",
        "Accessors",
        "planned",
        "src.conversion.gml_transpiler_parts.expression_parser",
        "no",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Overview/Accessors.htm",
        "The [#] accessor still needs parser, emitter, assignment, and runtime support.",
    ),
    _entry(
        "array_push",
        "Arrays",
        "implemented",
        "src.conversion.gml_runtime_parts.segments.40_arrays_structs_variables",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Array_Functions/Array_Functions.htm",
        "Implemented as a runtime helper with GML mutation behavior.",
    ),
    _entry(
        "array_create",
        "Arrays",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Array_Functions/Array_Functions.htm",
        "Requires full array function surface and index coercion policy.",
    ),
    _entry(
        "array_map",
        "Arrays",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Array_Functions/Array_Functions.htm",
        "Requires callback execution through GML method runtime.",
    ),
    _entry(
        "string",
        "Strings",
        "implemented",
        "src.conversion.gml_runtime_parts.segments.50_static_types_and_clone",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Strings/Strings.htm",
        "Basic GML string conversion exists.",
    ),
    _entry(
        "string_length",
        "Strings",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Strings/Strings.htm",
        "Requires explicit Unicode and indexing compatibility policy.",
    ),
    _entry(
        "string_char_at",
        "Strings",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Strings/Strings.htm",
        "Requires GameMaker one-based indexing semantics.",
    ),
    _entry(
        "sqrt",
        "Maths and Numbers",
        "implemented",
        "src.conversion.gml_runtime_parts.segments.30_numeric_arithmetic",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Reference/Maths_And_Numbers/Maths_And_Numbers.htm",
        "Implemented through runtime numeric helper to preserve NaN behavior.",
    ),
    _entry(
        "random",
        "Maths and Numbers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Maths_And_Numbers/Maths_And_Numbers.htm",
        "Requires deterministic compatibility RNG and seed APIs.",
    ),
    _entry(
        "choose",
        "Maths and Numbers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Maths_And_Numbers/Maths_And_Numbers.htm",
        "Requires GameMaker random selection behavior and argument handling.",
    ),
    _entry(
        "point_direction",
        "Maths and Numbers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Maths_And_Numbers/Maths_And_Numbers.htm",
        "Requires degree-based GameMaker coordinate convention wrapper.",
    ),
    _entry(
        "file_text_open_read",
        "Files INI JSON",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/File_Handling/File_Handling.htm",
        "Requires file handle runtime and sandbox path resolver.",
    ),
    _entry(
        "ini_open",
        "Files INI JSON",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/File_Handling/File_Handling.htm",
        "Requires INI parser/writer compatibility policy.",
    ),
    _entry(
        "json_encode",
        "Files INI JSON",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/File_Handling/File_Handling.htm",
        "Requires DS map/list marking and unsupported value policy.",
    ),
    _entry(
        "buffer_create",
        "Buffers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Buffers/Buffers.htm",
        "Requires handle-backed PackedByteArray wrapper with alignment semantics.",
    ),
    _entry(
        "buffer_write",
        "Buffers",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Buffers/Buffers.htm",
        "Requires value type encoding, cursor, alignment, and endian policy.",
    ),
    _entry(
        "http_get",
        "Asynchronous Functions",
        "planned",
        "src.conversion.events.mappings.other_async_http",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Asynchronous_Functions/Asynchronous_Functions.htm",
        "Async HTTP event mapping exists, but request runtime is planned.",
    ),
    _entry(
        "http_post_string",
        "Asynchronous Functions",
        "planned",
        "src.conversion.events.mappings.other_async_http",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Asynchronous_Functions/Asynchronous_Functions.htm",
        "Requires HTTPRequest bridge and async_load dispatch.",
    ),
    _entry(
        "network_create_socket",
        "Networking",
        "planned",
        "src.conversion.events.mappings.other_async_networking",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Networking/Networking.htm",
        "Async networking event mapping exists; socket runtime is planned.",
    ),
    _entry(
        "network_send_packet",
        "Networking",
        "planned",
        "src.conversion.events.mappings.other_async_networking",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Networking/Networking.htm",
        "Requires socket handles and buffer/packet compatibility.",
    ),
    _entry(
        "part_system_create",
        "Particles GPU Effects",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/Particles/Particles.htm",
        "Requires particle runtime manager or generated particle resources.",
    ),
    _entry(
        "gpu_set_blendmode",
        "Particles GPU Effects",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Drawing/GPU_Control/GPU_Control.htm",
        "Requires draw state bridge for blend/material settings.",
    ),
    _entry(
        "shader_set",
        "Shaders",
        "planned",
        "src.conversion.shaders",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Drawing/Shaders/Shaders.htm",
        "Shader assets can be converted, but runtime shader state helpers are planned.",
    ),
    _entry(
        "shader_set_uniform_f",
        "Shaders",
        "planned",
        "src.conversion.shaders",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Drawing/Shaders/Shaders.htm",
        "Requires ShaderMaterial parameter bridge.",
    ),
    _entry(
        "physics_world_create",
        "Physics",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Physics/Physics.htm",
        "Requires scoped Box2D-to-Godot physics compatibility policy.",
    ),
    _entry(
        "physics_apply_force",
        "Physics",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Physics/Physics.htm",
        "Requires generated physics body mapping.",
    ),
    _entry(
        "method_call",
        "Script Functions",
        "implemented",
        "src.conversion.gml_runtime_parts.segments.20_methods_and_exceptions",
        "n/a",
        "yes",
        "yes",
        "no",
        "GameMaker_Language/GML_Overview/Method_Variables.htm",
        "Implemented through GML method runtime helpers.",
    ),
    _entry(
        "script_execute",
        "Script Functions",
        "planned",
        "src.conversion.script_generator",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Overview/Script_Functions.htm",
        "Requires script asset registry and legacy argument variable support.",
    ),
    _entry(
        "#macro",
        "Preprocessor",
        "implemented",
        "src.conversion.gml_transpiler_parts.statement_parser",
        "yes",
        "yes",
        "n/a",
        "no",
        "GameMaker_Language/GML_Overview/GML_Overview.htm",
        "Macro declarations and configuration overrides are supported.",
    ),
    _entry(
        "#region",
        "Preprocessor",
        "planned",
        "src.conversion.gml_transpiler_parts.tokens",
        "no",
        "no",
        "n/a",
        "no",
        "GameMaker_Language/GML_Overview/Commenting_Code.htm",
        "Editor-only directives should be stripped before tokenization.",
    ),
    _entry(
        "flexpanel_create_node",
        "Flex Panels",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Flex_Panels/Flex_Panels.htm",
        "Requires compatibility layout wrapper or Control/Container mapping.",
    ),
    _entry(
        "flexpanel_node_style_set_width",
        "Flex Panels",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Flex_Panels/Flex_Panels.htm",
        "Requires Flex Panel style model and layout pass.",
    ),
    _entry(
        "show_debug_message",
        "OS Compiler Debug GC",
        "implemented",
        "src.conversion.gml_transpiler_parts.emitter",
        "n/a",
        "yes",
        "n/a",
        "no",
        "GameMaker_Language/GML_Reference/Debugging/Debugging.htm",
        "Lowers to Godot print for baseline debug output.",
    ),
    _entry(
        "os_type",
        "OS Compiler Debug GC",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/OS_And_Compiler/OS_And_Compiler.htm",
        "Requires explicit GameMaker-to-Godot platform constant mapping.",
    ),
    _entry(
        "gc_collect",
        "OS Compiler Debug GC",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Garbage_Collection/Garbage_Collection.htm",
        "Requires Godot reference/GC compatibility policy.",
    ),
    _entry(
        "steam_is_initialized",
        "Platform Services",
        "unsupported",
        "src.conversion.events.mappings.other_async_steam",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/Steam/Steam.htm",
        "Needs optional Steam addon/SDK integration; pure transpilation cannot provide it.",
    ),
    _entry(
        "iap_activate",
        "Platform Services",
        "unsupported",
        "src.conversion.events.mappings.other_async_platform",
        "n/a",
        "no",
        "no",
        "partial",
        "GameMaker_Language/GML_Reference/In_App_Purchases/In_App_Purchases.htm",
        "Requires platform store SDK integration outside the core transpiler.",
    ),
    _entry(
        "browser_input_capture",
        "Platform Services",
        "planned",
        "src.conversion.gml_runtime_parts",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/Web_And_HTML5/Web_And_HTML5.htm",
        "Requires HTML5/export-target policy.",
    ),
    _entry(
        "external_define",
        "Extensions",
        "unsupported",
        "src.conversion.resource_index",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/GML_Reference.htm",
        "Native extension calls require explicit project mapping or GDExtension hooks.",
    ),
    _entry(
        "extension_function_mapping",
        "Extensions",
        "planned",
        "src.conversion.resource_index",
        "n/a",
        "no",
        "no",
        "no",
        "GameMaker_Language/GML_Reference/GML_Reference.htm",
        "Project extension functions should be discovered and mapped separately from built-ins.",
    ),
    _entry(
        "compatibility_fixture_suite",
        "Full-Game Fixtures",
        "planned",
        "tests",
        "n/a",
        "n/a",
        "n/a",
        "no",
        "GameMaker_Language/GML_Reference/GML_Reference.htm",
        "Fixture coverage is planned for cross-feature generated Godot verification.",
    ),
)

_GML_API_ENTRY_BY_NAME = {entry.name: entry for entry in _GML_API_ENTRIES}
_DIAGNOSTIC_STATUSES: frozenset[GMLAPISupportStatus] = frozenset(
    {"partial", "planned", "unsupported", "out_of_scope"}
)


def iter_gml_api_entries() -> Iterable[GMLAPIEntry]:
    return _GML_API_ENTRIES


def get_gml_api_entry(name: str) -> GMLAPIEntry | None:
    return _GML_API_ENTRY_BY_NAME.get(name)


def is_known_gml_api(name: str) -> bool:
    return name in _GML_API_ENTRY_BY_NAME


def diagnostic_for_unimplemented_gml_api(name: str) -> str | None:
    entry = get_gml_api_entry(name)
    if entry is None or entry.status not in _DIAGNOSTIC_STATUSES:
        return None
    return (
        f"GML API '{entry.name}' from {entry.category} is {entry.status}; "
        f"tracked by #{entry.issue_number}. {entry.notes}"
    )


def generate_gml_api_compatibility_report() -> tuple[GMLAPICategoryReport, ...]:
    entries_by_category: dict[str, list[GMLAPIEntry]] = {
        category: [] for category in _CATEGORY_ISSUE_NUMBERS
    }
    for entry in _GML_API_ENTRIES:
        entries_by_category.setdefault(entry.category, []).append(entry)

    reports: list[GMLAPICategoryReport] = []
    for category, issue_number in _CATEGORY_ISSUE_NUMBERS.items():
        counts = _status_counts(entries_by_category.get(category, ()))
        reports.append(
            GMLAPICategoryReport(
                category=category,
                issue_number=issue_number,
                implemented=counts["implemented"],
                partial=counts["partial"],
                planned=counts["planned"],
                unsupported=counts["unsupported"],
                out_of_scope=counts["out_of_scope"],
            )
        )
    return tuple(reports)


def category_issue_numbers() -> dict[str, int]:
    return dict(_CATEGORY_ISSUE_NUMBERS)


def _status_counts(entries: Iterable[GMLAPIEntry]) -> dict[GMLAPISupportStatus, int]:
    counts: dict[GMLAPISupportStatus, int] = {
        "implemented": 0,
        "partial": 0,
        "planned": 0,
        "unsupported": 0,
        "out_of_scope": 0,
    }
    for entry in entries:
        counts[entry.status] += 1
    return counts


def godot_docs_root() -> str:
    return _GODOT_DOCS
