"""Legacy private model aliases retained for the #820 facade cleanup."""

from .expression_models import (
    ArrayLiteral as _ArrayLiteral,
    Binary as _Binary,
    Call as _Call,
    DSMapAccess as _DSMapAccess,
    Expression as _Expression,
    FunctionLiteral as _FunctionLiteral,
    FunctionParameter as _FunctionParameter,
    Grouped as _Grouped,
    Index as _Index,
    Literal as _Literal,
    Member as _Member,
    Name as _Name,
    NameOf as _NameOf,
    NewCall as _NewCall,
    NumberLiteral as _NumberLiteral,
    StringLiteral as _StringLiteral,
    StructAccess as _StructAccess,
    StructLiteral as _StructLiteral,
    TemplateStringLiteral as _TemplateStringLiteral,
    Ternary as _Ternary,
    Unary as _Unary,
)
from .shared_models import (
    BuiltinVariableMetadata as _BuiltinVariableMetadata,
    ScopeContext as _ScopeContext,
    StaticDeclaration as _StaticDeclaration,
    Token as _Token,
)


__all__ = [
    "_ArrayLiteral",
    "_Binary",
    "_BuiltinVariableMetadata",
    "_Call",
    "_DSMapAccess",
    "_Expression",
    "_FunctionLiteral",
    "_FunctionParameter",
    "_Grouped",
    "_Index",
    "_Literal",
    "_Member",
    "_Name",
    "_NameOf",
    "_NewCall",
    "_NumberLiteral",
    "_ScopeContext",
    "_StaticDeclaration",
    "_StringLiteral",
    "_StructAccess",
    "_StructLiteral",
    "_TemplateStringLiteral",
    "_Ternary",
    "_Token",
    "_Unary",
]
