# pyright: reportPrivateUsage=false
from __future__ import annotations

from src.conversion.gml_transpiler_parts.api import transpile_gml_code
from src.conversion.gml_transpiler_parts.api import transpile_gml_code_with_source_map
from src.conversion.gml_transpiler_parts.constants import _BUILTIN_VARIABLE_REGISTRY
from src.conversion.gml_transpiler_parts.expression_parser import (
    _ExpressionParser,
    _parse_gml_expression,
)
from src.conversion.gml_transpiler_parts.expression_service import (
    transpile_gml_condition,
    transpile_gml_expression,
)
from src.conversion.gml_transpiler_parts.extension_functions import (
    EXTENSION_FUNCTION_MAPPING_FILENAME,
    diagnostic_for_unmapped_extension_function,
    load_gml_extension_function_mappings,
    normalize_extension_function_mappings,
    normalize_extension_functions,
)
from src.conversion.gml_transpiler_parts.gml_api_manifest import (
    GMLAPICategoryReport,
    GMLAPIEntry,
    category_issue_numbers,
    diagnostic_for_unimplemented_gml_api,
    generate_gml_api_compatibility_report,
    get_gml_api_entry,
    godot_docs_root,
    is_known_gml_api,
    iter_gml_api_entries,
)
from src.conversion.gml_transpiler_parts.gml_manual_scope import (
    GMLManualScopeCategoryReport,
    GMLManualScopeEntry,
    generate_gml_manual_scope_report,
    get_gml_manual_scope_entry,
    iter_gml_manual_scope_entries,
    render_gml_manual_scope_markdown,
    validate_gml_manual_scope_against_manifest,
)
from src.conversion.gml_transpiler_parts.gml_function_dispatch import (
    GMLFunctionDescriptor,
    get_gml_function_descriptor,
    iter_gml_function_descriptors,
    validate_gml_function_arity,
)
from src.conversion.gml_transpiler_parts.model import (
    GMLExtensionFunction,
    GMLExtensionFunctionMapping,
    GMLTranspileError,
    _ArrayLiteral,
    _Binary,
    _BuiltinVariableMetadata,
    _Call,
    _DSMapAccess,
    _Expression,
    _FunctionLiteral,
    _FunctionParameter,
    _Grouped,
    _Index,
    _Literal,
    _Member,
    _Name,
    _NameOf,
    _NewCall,
    _NumberLiteral,
    _ScopeContext,
    _StaticDeclaration,
    _StringLiteral,
    _StructAccess,
    _StructLiteral,
    _Ternary,
    _Token,
    _Unary,
)
from src.conversion.gml_transpiler_parts.preprocessor import (
    GMLPreprocessResult,
    GMLPreprocessorDiagnostic,
    preprocess_gml_source,
)
from src.conversion.gml_transpiler_parts.source_map import (
    GMLSourceDiagnostic,
    GMLSourceMap,
    GMLSourceMapEntry,
    GMLTranspileResult,
    analyze_gml_source_identifiers,
    gml_source_map_path,
    merge_gml_source_maps,
    render_gml_source_header,
    write_gml_source_map,
)
from src.conversion.gml_transpiler_parts.tokens import _expression_tokens, _tokenize

__all__ = [
    "GMLTranspileError",
    "GMLAPICategoryReport",
    "GMLAPIEntry",
    "GMLManualScopeCategoryReport",
    "GMLManualScopeEntry",
    "GMLFunctionDescriptor",
    "GMLExtensionFunction",
    "GMLExtensionFunctionMapping",
    "GMLPreprocessResult",
    "GMLPreprocessorDiagnostic",
    "GMLSourceDiagnostic",
    "GMLSourceMap",
    "GMLSourceMapEntry",
    "GMLTranspileResult",
    "_ArrayLiteral",
    "_Binary",
    "_BuiltinVariableMetadata",
    "_BUILTIN_VARIABLE_REGISTRY",
    "_Call",
    "_DSMapAccess",
    "_Expression",
    "_ExpressionParser",
    "_FunctionLiteral",
    "_FunctionParameter",
    "_Grouped",
    "_Index",
    "_Literal",
    "_Member",
    "_Name",
    "_NameOf",
    "_NewCall",
    "_NumberLiteral",
    "_ScopeContext",
    "_StaticDeclaration",
    "_StringLiteral",
    "_StructAccess",
    "_StructLiteral",
    "_Ternary",
    "_Token",
    "_Unary",
    "_expression_tokens",
    "_parse_gml_expression",
    "_tokenize",
    "category_issue_numbers",
    "EXTENSION_FUNCTION_MAPPING_FILENAME",
    "diagnostic_for_unimplemented_gml_api",
    "diagnostic_for_unmapped_extension_function",
    "generate_gml_api_compatibility_report",
    "generate_gml_manual_scope_report",
    "get_gml_api_entry",
    "get_gml_function_descriptor",
    "get_gml_manual_scope_entry",
    "godot_docs_root",
    "is_known_gml_api",
    "iter_gml_api_entries",
    "iter_gml_manual_scope_entries",
    "iter_gml_function_descriptors",
    "load_gml_extension_function_mappings",
    "normalize_extension_function_mappings",
    "normalize_extension_functions",
    "analyze_gml_source_identifiers",
    "gml_source_map_path",
    "merge_gml_source_maps",
    "preprocess_gml_source",
    "render_gml_manual_scope_markdown",
    "render_gml_source_header",
    "transpile_gml_code",
    "transpile_gml_code_with_source_map",
    "transpile_gml_condition",
    "transpile_gml_expression",
    "validate_gml_manual_scope_against_manifest",
    "validate_gml_function_arity",
    "write_gml_source_map",
]
