# pyright: reportPrivateUsage=false
from __future__ import annotations

from src.conversion.gml_transpiler_parts.api import transpile_gml_code
from src.conversion.gml_transpiler_parts.constants import _BUILTIN_VARIABLE_REGISTRY
from src.conversion.gml_transpiler_parts.expression_parser import (
    _ExpressionParser,
    _parse_gml_expression,
)
from src.conversion.gml_transpiler_parts.expression_service import (
    transpile_gml_condition,
    transpile_gml_expression,
)
from src.conversion.gml_transpiler_parts.gml_api_manifest import (
    GMLAPICategoryReport,
    GMLAPIEntry,
    category_issue_numbers,
    diagnostic_for_unimplemented_gml_api,
    generate_gml_api_compatibility_report,
    get_gml_api_entry,
    godot_docs_root,
    is_known_gml_api,
    iter_gml_api_entries,
)
from src.conversion.gml_transpiler_parts.model import (
    GMLTranspileError,
    _ArrayLiteral,
    _Binary,
    _BuiltinVariableMetadata,
    _Call,
    _DSMapAccess,
    _Expression,
    _FunctionLiteral,
    _FunctionParameter,
    _Grouped,
    _Index,
    _Literal,
    _Member,
    _Name,
    _NameOf,
    _NewCall,
    _NumberLiteral,
    _ScopeContext,
    _StaticDeclaration,
    _StringLiteral,
    _StructAccess,
    _StructLiteral,
    _Ternary,
    _Token,
    _Unary,
)
from src.conversion.gml_transpiler_parts.tokens import _expression_tokens, _tokenize

__all__ = [
    "GMLTranspileError",
    "GMLAPICategoryReport",
    "GMLAPIEntry",
    "_ArrayLiteral",
    "_Binary",
    "_BuiltinVariableMetadata",
    "_BUILTIN_VARIABLE_REGISTRY",
    "_Call",
    "_DSMapAccess",
    "_Expression",
    "_ExpressionParser",
    "_FunctionLiteral",
    "_FunctionParameter",
    "_Grouped",
    "_Index",
    "_Literal",
    "_Member",
    "_Name",
    "_NameOf",
    "_NewCall",
    "_NumberLiteral",
    "_ScopeContext",
    "_StaticDeclaration",
    "_StringLiteral",
    "_StructAccess",
    "_StructLiteral",
    "_Ternary",
    "_Token",
    "_Unary",
    "_expression_tokens",
    "_parse_gml_expression",
    "_tokenize",
    "category_issue_numbers",
    "diagnostic_for_unimplemented_gml_api",
    "generate_gml_api_compatibility_report",
    "get_gml_api_entry",
    "godot_docs_root",
    "is_known_gml_api",
    "iter_gml_api_entries",
    "transpile_gml_code",
    "transpile_gml_condition",
    "transpile_gml_expression",
]
