_INCLUDED_FILES_ROOT_NAME = "included_files"
_INCLUDED_FILES_STAGE_PREFIX = ".gm2godot-included-files-"
_INCLUDED_FILES_LOCK_NAME = ".gm2godot-included-files.lock"
_INCLUDED_FILES_LOCK_TEMP_PREFIX = ".gm2godot-included-files-lock."
_INCLUDED_FILES_LOCK_CLEANUP_PREFIX = ".gm2godot-included-files-lock-cleanup."
_INCLUDED_FILES_JOURNAL_NAME = ".gm2godot-included-files-transaction.json"
_INCLUDED_FILES_COMMIT_NAME = ".gm2godot-included-files-commit.json"
_INCLUDED_FILES_JOURNAL_TEMP_PREFIX = ".gm2godot-included-files-journal."
_INCLUDED_FILES_COMMIT_TEMP_PREFIX = ".gm2godot-included-files-commit."
_INCLUDED_FILES_STAGE_MARKER_NAME = ".gm2godot-included-files-stage.json"
_INCLUDED_FILES_CLEANUP_PREFIX = ".gm2godot-included-cleanup."
_INCLUDED_FILES_LEGACY_RECOVERY_FORMAT_VERSION = 1
_INCLUDED_FILES_RECOVERY_FORMAT_VERSION = 2
_INCLUDED_FILES_STAGE_MARKER_FORMAT_VERSION = 1
_INCLUDED_FILES_WORKER_WINDOW_MULTIPLIER = 2
# The canonical cap is a parser-memory safety boundary, not a scaling knob.
# Format v2 removes repeated field names and uses fixed-width integer metadata
# so its exact serialized size can be preflighted before payload staging.
_INCLUDED_FILES_RECOVERY_RECORD_MAX_BYTES = 16 * 1024 * 1024
_INCLUDED_FILES_RECOVERY_MAX_TREE_ENTRIES = 100_000
_INCLUDED_FILES_RECOVERY_INTEGER_HEX_DIGITS = 16
_INCLUDED_FILES_RECOVERY_INTEGER_MAX = (
    1 << (_INCLUDED_FILES_RECOVERY_INTEGER_HEX_DIGITS * 4)
) - 1
_INCLUDED_FILES_RECOVERY_PLACEHOLDER_SHA256 = "0" * 64
_INCLUDED_FILES_LOCK_CONTENT = b"GM2Godot Included Files lock v1\n"


# Finite package-internal aliases; helpers continue reading facade globals.
INCLUDED_FILES_ROOT_NAME = _INCLUDED_FILES_ROOT_NAME
INCLUDED_FILES_STAGE_PREFIX = _INCLUDED_FILES_STAGE_PREFIX
INCLUDED_FILES_LOCK_NAME = _INCLUDED_FILES_LOCK_NAME
INCLUDED_FILES_LOCK_TEMP_PREFIX = _INCLUDED_FILES_LOCK_TEMP_PREFIX
INCLUDED_FILES_LOCK_CLEANUP_PREFIX = _INCLUDED_FILES_LOCK_CLEANUP_PREFIX
INCLUDED_FILES_JOURNAL_NAME = _INCLUDED_FILES_JOURNAL_NAME
INCLUDED_FILES_COMMIT_NAME = _INCLUDED_FILES_COMMIT_NAME
INCLUDED_FILES_JOURNAL_TEMP_PREFIX = _INCLUDED_FILES_JOURNAL_TEMP_PREFIX
INCLUDED_FILES_COMMIT_TEMP_PREFIX = _INCLUDED_FILES_COMMIT_TEMP_PREFIX
INCLUDED_FILES_STAGE_MARKER_NAME = _INCLUDED_FILES_STAGE_MARKER_NAME
INCLUDED_FILES_CLEANUP_PREFIX = _INCLUDED_FILES_CLEANUP_PREFIX
INCLUDED_FILES_LEGACY_RECOVERY_FORMAT_VERSION = _INCLUDED_FILES_LEGACY_RECOVERY_FORMAT_VERSION
INCLUDED_FILES_RECOVERY_FORMAT_VERSION = _INCLUDED_FILES_RECOVERY_FORMAT_VERSION
INCLUDED_FILES_STAGE_MARKER_FORMAT_VERSION = _INCLUDED_FILES_STAGE_MARKER_FORMAT_VERSION
INCLUDED_FILES_WORKER_WINDOW_MULTIPLIER = _INCLUDED_FILES_WORKER_WINDOW_MULTIPLIER
INCLUDED_FILES_RECOVERY_RECORD_MAX_BYTES = _INCLUDED_FILES_RECOVERY_RECORD_MAX_BYTES
INCLUDED_FILES_RECOVERY_MAX_TREE_ENTRIES = _INCLUDED_FILES_RECOVERY_MAX_TREE_ENTRIES
INCLUDED_FILES_RECOVERY_INTEGER_HEX_DIGITS = _INCLUDED_FILES_RECOVERY_INTEGER_HEX_DIGITS
INCLUDED_FILES_RECOVERY_INTEGER_MAX = _INCLUDED_FILES_RECOVERY_INTEGER_MAX
INCLUDED_FILES_RECOVERY_PLACEHOLDER_SHA256 = _INCLUDED_FILES_RECOVERY_PLACEHOLDER_SHA256
INCLUDED_FILES_LOCK_CONTENT = _INCLUDED_FILES_LOCK_CONTENT
