"""Capture and compare generated bytes and stable conversion snapshot fields.

This module reads output files but never launches converters or Godot, mutates a
conversion destination, exports a Git tree, or writes parity receipts.
"""

from __future__ import annotations

import json
import re
import stat
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path, PurePosixPath
from typing import cast

from scripts.conversion_parity_contract import (
    DestinationDefinition,
    FixtureDefinition,
    ParityError,
    value_sha256,
)


@dataclass(frozen=True)
class FixtureRun:
    destination: str
    files: dict[str, tuple[int, bytes]]
    snapshot: dict[str, object]


def compare_fixture_runs(
    base: FixtureRun,
    head: FixtureRun,
    fields: Sequence[str],
) -> dict[str, dict[str, str]]:
    """Compare exact output bytes and normalized transaction semantics."""
    if base.destination != head.destination:
        raise ParityError(
            f"Destination mismatch before comparison: {base.destination!r} != {head.destination!r}"
        )
    differences: dict[str, dict[str, str]] = {}
    for field in fields:
        base_value, head_value = _comparison_values(field, base, head)
        if base_value != head_value:
            differences[field] = {
                "base_sha256": _comparison_sha(field, base_value),
                "head_sha256": _comparison_sha(field, head_value),
            }
    return differences


def validate_expected_outcome(snapshot: Mapping[str, object], fixture: FixtureDefinition) -> None:
    if fixture.expected_outcome_state is None and fixture.expected_skipped_resources is None:
        return
    diagnostics = snapshot_object(snapshot["diagnostics"], "conversion diagnostics")
    outcome = snapshot_object(diagnostics.get("outcome"), "conversion outcome")
    if fixture.expected_outcome_state is not None:
        state = outcome.get("state")
        if state != fixture.expected_outcome_state:
            raise ParityError(
                f"{fixture.identifier} outcome mismatch: expected {fixture.expected_outcome_state!r}, got {state!r}"
            )
    if fixture.expected_skipped_resources is not None:
        resources = snapshot_object(outcome.get("resources"), "conversion resources")
        skipped = resources.get("skipped")
        if skipped != fixture.expected_skipped_resources:
            raise ParityError(
                f"{fixture.identifier} skipped-resource mismatch: expected {fixture.expected_skipped_resources}, got {skipped!r}"
            )


def collect_output_files(destination: Path) -> dict[str, tuple[int, bytes]]:
    """Capture every generated file's exact bytes and mode without following links."""
    files: dict[str, tuple[int, bytes]] = {}
    for path in sorted(destination.rglob("*")):
        if path.is_symlink():
            raise ParityError(f"Parity output must not contain a symlink: {path}")
        if path.is_dir():
            continue
        if not stat.S_ISREG(path.stat().st_mode):
            raise ParityError(f"Parity output must contain only regular files: {path}")
        relative = path.relative_to(destination).as_posix()
        files[relative] = (stat.S_IMODE(path.stat().st_mode), path.read_bytes())
    return files


def output_snapshot(
    files: Mapping[str, tuple[int, bytes]],
    *,
    destination: Path,
    definition: DestinationDefinition,
    stdout: str,
    stderr: str,
    exit_status: int,
    parser_error: Mapping[str, object],
    runtime_markers: Mapping[str, object],
    publication_observation: Mapping[str, object] | None = None,
) -> dict[str, object]:
    """Select visible outputs and fully capture managed-output transaction semantics."""
    visible = {
        path: record
        for path, record in files.items()
        if not _is_transaction_path(path, definition)
    }
    return {
        "relative_paths": sorted(visible),
        "file_bytes": {path: sha256(contents).hexdigest() for path, (_, contents) in visible.items()},
        "modes": {path: mode for path, (mode, _) in visible.items()},
        "generated_gdscript": {
            path: sha256(contents).hexdigest()
            for path, (_, contents) in visible.items()
            if path.endswith(".gd")
        },
        "source_maps": _json_outputs(visible, suffix=".gmlmap.json"),
        "diagnostics": _diagnostics_snapshot(visible),
        "diagnostic_ids": _diagnostic_ids(visible),
        "parser_error": dict(parser_error),
        "stdout": stdout,
        "stderr": stderr,
        "exit_status": exit_status,
        "terminal_output_state": _terminal_output_state(visible, destination),
        "transaction_provenance": _transaction_provenance_snapshot(
            files, definition, publication_observation
        ),
        "runtime_markers": dict(runtime_markers),
    }


def _transaction_provenance_snapshot(
    files: Mapping[str, tuple[int, bytes]],
    definition: DestinationDefinition,
    observation: Mapping[str, object] | None,
) -> dict[str, object]:
    """Normalize only independently authenticated publication relationships."""
    raw: dict[str, object] = {}
    for path, (mode, contents) in files.items():
        if not _is_transaction_path(path, definition):
            continue
        raw[path] = {
            "mode": mode,
            "size": len(contents),
            "sha256": sha256(contents).hexdigest(),
            "content": _transaction_content(contents, path),
        }
    semantics = [] if observation is None else _validated_publication(files, definition, observation)
    return {
        "raw": raw,
        "observation": None if observation is None else dict(observation),
        "validated": observation is not None,
        "semantics": sorted(semantics, key=value_sha256),
    }


def _comparison_values(
    field: str,
    base: FixtureRun,
    head: FixtureRun,
) -> tuple[object, object]:
    if field == "file_bytes":
        return _visible_file_bytes(base), _visible_file_bytes(head)
    if field == "modes":
        return _visible_file_modes(base), _visible_file_modes(head)
    if field == "transaction_provenance":
        return _transaction_semantics(base), _transaction_semantics(head)
    if field not in base.snapshot or field not in head.snapshot:
        raise ParityError(f"Unknown parity field {field!r}")
    return base.snapshot[field], head.snapshot[field]


def _comparison_sha(field: str, value: object) -> str:
    if field == "file_bytes":
        bytes_by_path = cast(dict[str, bytes], value)
        return value_sha256({path: sha256(contents).hexdigest() for path, contents in bytes_by_path.items()})
    return value_sha256(value)


def serialize_fixture_run(run: FixtureRun) -> dict[str, object]:
    return {
        "destination": run.destination,
        "files": {
            path: {"mode": mode, "size": len(contents), "sha256": sha256(contents).hexdigest()}
            for path, (mode, contents) in run.files.items()
        },
        "snapshot": run.snapshot,
    }


def _json_outputs(
    files: Mapping[str, tuple[int, bytes]],
    *,
    suffix: str,
) -> dict[str, object]:
    return {
        path: _json_bytes(contents, path)
        for path, (_, contents) in files.items()
        if path.endswith(suffix)
    }


def _diagnostics_snapshot(files: Mapping[str, tuple[int, bytes]]) -> object:
    entry = files.get("gm2godot/conversion_diagnostics.json")
    return {"diagnostics": []} if entry is None else _json_bytes(entry[1], "conversion_diagnostics.json")


def _diagnostic_ids(files: Mapping[str, tuple[int, bytes]]) -> list[str]:
    diagnostics = snapshot_object(_diagnostics_snapshot(files), "conversion diagnostics")
    identifiers: list[str] = []
    for raw_item in _json_list(diagnostics.get("diagnostics"), "conversion diagnostics entries"):
        item = snapshot_object(raw_item, "conversion diagnostics entry")
        code = item.get("code")
        if not isinstance(code, str):
            raise ParityError("conversion diagnostics entries must have string codes")
        identifiers.append(code)
    return identifiers


def _terminal_output_state(
    files: Mapping[str, tuple[int, bytes]],
    destination: Path,
) -> dict[str, object]:
    names = (
        "gm2godot/conversion_attempt.json",
        "gm2godot/conversion_manifest.json",
        "gm2godot/architecture_policy.json",
    )
    return {
        "destination": str(destination),
        "records": {
            name: _json_bytes(files[name][1], name)
            for name in names
            if name in files
        },
    }


def _is_transaction_path(path: str, definition: DestinationDefinition) -> bool:
    return path == definition.transaction_lock or path.startswith(f"{definition.transaction_root}/")


def _transaction_content(contents: bytes, path: str) -> object:
    if path.endswith(".lock"):
        return {"bytes_hex": contents.hex()}
    return _json_bytes(contents, path)


def _visible_file_bytes(run: FixtureRun) -> dict[str, bytes]:
    paths = cast(list[str], run.snapshot["relative_paths"])
    return {path: run.files[path][1] for path in paths}


def _visible_file_modes(run: FixtureRun) -> dict[str, int]:
    paths = cast(list[str], run.snapshot["relative_paths"])
    return {path: run.files[path][0] for path in paths}


def _transaction_semantics(run: FixtureRun) -> object:
    provenance = snapshot_object(run.snapshot["transaction_provenance"], "transaction provenance")
    if provenance.get("validated") is not True:
        raise ParityError("Transaction provenance has no authenticated publication observation")
    return provenance["semantics"]


_POINTER_NAME = ".gm2godot-managed-output-generation.json"
_MARKER_NAME = ".gm2godot-workspace-parent.json"
_JOURNAL_NAME = ".gm2godot-managed-output-transaction.json"
_GENERATION_NAME = re.compile(
    r"\.gm2godot-managed-output-generation-([0-9a-f]{32})-(previous|desired)\.json\Z"
)
_IDENTITY_MARKER = ["<verified-device>", "<verified-file-id>"]
_VOLATILE_FIELDS = frozenset({
    "workspace_marker.destination_identity", "workspace_marker.parent_identity",
    "pointer.transaction_id", "pointer.destination_identity", "pointer.journal_sha256",
    "pointer.generation_record.name", "pointer.generation_record.identity", "pointer.generation_record.sha256",
    "desired_generation.transaction_id", "desired_generation.destination_identity",
    "desired_generation.managed_identities[*][1:]", "desired_generation.evidence.attempt.identity",
    "desired_generation.evidence.manifest.identity", "desired_generation.record_path.transaction_id",
    "previous_generation.transaction_id", "previous_generation.destination_identity",
    "previous_generation.managed_identities[*][1:]", "previous_generation.evidence.attempt.identity",
    "previous_generation.evidence.manifest.identity", "previous_generation.record_path.transaction_id",
    "journal.transaction_id", "journal.destination_identity", "journal.workspace_parent_identity",
    "journal.stage_identity", "journal.publication_identity", "journal.pointer_stage_identity",
    "journal.previous_record.name", "journal.previous_record.identity", "journal.previous_record.sha256",
    "journal.desired_record.name", "journal.desired_record.identity", "journal.desired_record.sha256",
    "journal.directories[*].identity", "journal.transitions[*].previous_public_identity",
    "journal.transitions[*].backup.identity", "journal.transitions[*].desired_stage.identity",
})
_EVIDENCE_PATHS = {
    "attempt": "gm2godot/conversion_attempt.json",
    "manifest": "gm2godot/conversion_manifest.json",
}
_INVENTORY_KINDS = frozenset({
    "project", "source_map", "shader", "gdscript", "scene", "resource", "report",
    "image", "audio", "font", "import_metadata", "file",
})


def validate_required_outputs(files: Mapping[str, tuple[int, bytes]]) -> None:
    """A successful converter must emit all canonical diagnostics and evidence."""
    for path in (*_EVIDENCE_PATHS.values(), "gm2godot/architecture_policy.json",
                 "gm2godot/conversion_diagnostics.json"):
        if path not in files:
            raise ParityError(f"Successful parity fixture is missing required output {path!r}")
        snapshot_object(_json_bytes(files[path][1], path), path)


def verify_publication_identities(
    destination: Path, observation: Mapping[str, object], definition: DestinationDefinition
) -> None:
    """Check observed public identities again after converter cleanup completes."""
    for group in ("public_identities", "directory_identities"):
        identities = snapshot_object(observation.get(group), group)
        for name, expected in identities.items():
            path = destination / _relative_path(name)
            if path.is_symlink():
                raise ParityError(f"Publication identity refers to a symlink: {name}")
            try:
                actual = path.stat()
            except OSError as error:
                raise ParityError(f"Publication identity is missing for {name}: {error}") from error
            required_type = stat.S_ISDIR if group == "directory_identities" else stat.S_ISREG
            if not required_type(actual.st_mode) or _identity(expected) != _stat_identity(actual):
                raise ParityError(f"Publication identity changed after observation: {name}")
            if group == "directory_identities" and stat.S_IMODE(actual.st_mode) != snapshot_object(observation.get("directory_modes"), "directory modes").get(name):
                raise ParityError(f"Publication directory mode changed after observation: {name}")
    if _identity(observation.get("destination_identity")) != _stat_identity(destination.stat()):
        raise ParityError("Publication destination identity changed after observation")
    parent = destination / definition.transaction_root
    if parent.is_symlink() or not parent.is_dir() or _identity(observation.get("parent_identity")) != _stat_identity(parent.stat()):
        raise ParityError("Publication transaction-root identity changed after observation")


def _stat_identity(value: object) -> list[str]:
    return [f"{cast(int, getattr(value, field)):032x}" for field in ("st_dev", "st_ino")]


def _relative_path(value: object) -> str:
    if not isinstance(value, str) or not value or value == "." or "\\" in value or "\x00" in value:
        raise ParityError(f"Invalid publication relative path: {value!r}")
    path = PurePosixPath(value)
    if path.is_absolute() or path.as_posix() != value or ".." in path.parts:
        raise ParityError(f"Invalid publication relative path: {value!r}")
    return value


def _identity(value: object) -> list[str]:
    components = _json_list(value, "filesystem identity")
    if len(components) != 2 or any(
        not isinstance(item, str) or re.fullmatch(r"[0-9a-f]{32}", item) is None
        for item in components
    ):
        raise ParityError("Invalid filesystem identity")
    return cast(list[str], components)


def _exact_object(value: object, keys: set[str], label: str) -> dict[str, object]:
    result = snapshot_object(value, label)
    if result.keys() != keys:
        raise ParityError(f"Invalid {label} fields")
    return result


def _format_version(value: object) -> None:
    if type(value) is not int or value != 1:
        raise ParityError("Invalid publication format version")


def _canonical_record(contents: bytes, label: str, *, compact: bool = False) -> dict[str, object]:
    result = snapshot_object(_json_bytes(contents, label), label)
    canonical = (json.dumps(result, ensure_ascii=True, indent=None if compact else 2,
                            separators=(",", ":") if compact else None, sort_keys=True) + "\n").encode()
    if contents != canonical:
        raise ParityError(f"Noncanonical publication record: {label}")
    return result


def _digest(contents: bytes) -> str:
    return "sha256:" + sha256(contents).hexdigest()


def _content_receipt(value: object) -> dict[str, object]:
    receipt = _exact_object(value, {"mode", "byte_count", "sha256"}, "content receipt")
    if type(receipt["mode"]) is not int or not 0 <= receipt["mode"] <= 0o7777:
        raise ParityError("Invalid content receipt mode")
    if type(receipt["byte_count"]) is not int or receipt["byte_count"] < 0:
        raise ParityError("Invalid content receipt byte count")
    digest = receipt["sha256"]
    if not isinstance(digest, str) or re.fullmatch(r"sha256:[0-9a-f]{64}", digest) is None:
        raise ParityError("Invalid content receipt digest")
    return receipt


def _file_receipt(record: tuple[int, bytes]) -> dict[str, object]:
    return {"mode": record[0], "byte_count": len(record[1]), "sha256": _digest(record[1])}


def _observed_records(observation: Mapping[str, object]) -> tuple[
    dict[str, tuple[int, bytes]], dict[str, list[str]]
]:
    files: dict[str, tuple[int, bytes]] = {}
    identities: dict[str, list[str]] = {}
    for path, value in snapshot_object(observation.get("files"), "observed records").items():
        _relative_path(path)
        metadata = _exact_object(value, {"mode", "identity", "bytes_hex"}, "observed record")
        encoded = metadata["bytes_hex"]
        if not isinstance(encoded, str):
            raise ParityError("Invalid observed record bytes")
        try:
            content = bytes.fromhex(encoded)
        except ValueError as error:
            raise ParityError("Invalid observed record bytes") from error
        mode = metadata["mode"]
        _content_receipt({"mode": mode, "byte_count": len(content), "sha256": _digest(content)})
        files[path] = (cast(int, mode), content)
        identities[path] = _identity(metadata["identity"])
    return files, identities


def _generation_identities(record: Mapping[str, object]) -> dict[str, object]:
    result: dict[str, object] = {
        cast(str, cast(list[object], row)[0]): cast(list[object], row)[1:]
        for row in _json_list(record["managed_identities"], "managed identities")
    }
    for value in snapshot_object(record["evidence"], "evidence").values():
        evidence = snapshot_object(value, "evidence receipt")
        if evidence["present"] is True:
            result[cast(str, evidence["path"])] = evidence["identity"]
    return result


def _validate_generation(
    name: str, content: bytes, transaction_id: str, role: str, destination_identity: list[str]
) -> tuple[dict[str, object], dict[str, dict[str, object]]]:
    record = _exact_object(_canonical_record(content, name), {
        "format_version", "kind", "transaction_id", "role", "destination_identity",
        "inventory", "managed_identities", "evidence",
    }, "generation record")
    _format_version(record["format_version"])
    if (record["format_version"], record["kind"], record["transaction_id"], record["role"]) != (
        1, "gm2godot-managed-output-generation-record", transaction_id, role
    ) or _identity(record["destination_identity"]) != destination_identity:
        raise ParityError("Generation record transaction, role or destination mismatch")
    inventory = _exact_object(record["inventory"], {"format_version", "entries"}, "inventory")
    _format_version(inventory["format_version"])
    entries: dict[str, dict[str, object]] = {}
    for raw_entry in _json_list(inventory["entries"], "inventory entries"):
        entry = _exact_object(raw_entry, {
            "path", "kind", "owner", "mode", "byte_count", "sha256",
        }, "inventory entry")
        path = _relative_path(entry["path"])
        if path in entries or not isinstance(entry["kind"], str) or entry["kind"] not in _INVENTORY_KINDS:
            raise ParityError("Duplicate or invalid inventory entry")
        owner = _exact_object(entry["owner"], {"class", "name"}, "inventory owner")
        if owner["class"] not in {"converter_step", "shared_owner"} or not isinstance(owner["name"], str) or re.fullmatch(r"[a-z][a-z0-9_]{0,63}", owner["name"]) is None:
            raise ParityError("Invalid inventory owner")
        entries[path] = _content_receipt({key: entry[key] for key in ("mode", "byte_count", "sha256")})
    if list(entries) != sorted(entries):
        raise ParityError("Inventory entries are not sorted")
    rows = _json_list(record["managed_identities"], "managed identities")
    if len(rows) != len(entries):
        raise ParityError("Managed identity count mismatch")
    for path, raw_row in zip(entries, rows, strict=True):
        row = _json_list(raw_row, "managed identity row")
        if len(row) != 3 or row[0] != path:
            raise ParityError("Managed identity path mismatch")
        _identity(row[1:])
    _exact_object(record["evidence"], {"attempt", "manifest"}, "generation evidence")
    return record, entries


def _validate_reference(
    value: object, observed: Mapping[str, tuple[int, bytes]], identities: Mapping[str, list[str]],
    root: str, transaction_id: str, role: str,
) -> str:
    reference = _exact_object(value, {"name", "identity", "mode", "byte_count", "sha256"}, "record reference")
    name = reference["name"]
    if not isinstance(name, str) or name != f".gm2godot-managed-output-generation-{transaction_id}-{role}.json":
        raise ParityError("Generation filename and transaction mismatch")
    path = f"{root}/{name}"
    if path not in observed or _identity(reference["identity"]) != identities[path]:
        raise ParityError("Generation reference identity mismatch")
    if _content_receipt({key: reference[key] for key in ("mode", "byte_count", "sha256")}) != _file_receipt(observed[path]):
        raise ParityError("Generation reference bytes or mode mismatch")
    return path


def _validate_evidence(
    record: Mapping[str, object],
    files: Mapping[str, tuple[int, bytes]], identities: Mapping[str, object], *, desired: bool,
) -> dict[str, dict[str, object] | None]:
    receipts: dict[str, dict[str, object] | None] = {}
    for kind, path in _EVIDENCE_PATHS.items():
        evidence = _exact_object(snapshot_object(record["evidence"], "evidence")[kind], {
            "path", "present", "identity", "mode", "byte_count", "sha256",
        }, "evidence receipt")
        if evidence["path"] != path or type(evidence["present"]) is not bool:
            raise ParityError("Invalid evidence path or presence")
        if not evidence["present"]:
            if any(evidence[key] is not None for key in ("identity", "mode", "sha256")) or type(evidence["byte_count"]) is not int or evidence["byte_count"] != 0 or desired:
                raise ParityError("Missing or malformed publication evidence")
            receipts[path] = None
            continue
        identity = _identity(evidence["identity"])
        receipt = _content_receipt({key: evidence[key] for key in ("mode", "byte_count", "sha256")})
        if desired and (path not in files or receipt != _file_receipt(files[path]) or identity != _identity(identities.get(path))):
            raise ParityError("Publication evidence does not match public bytes or identity")
        receipts[path] = receipt
    if desired:
        manifest = _canonical_record(files[_EVIDENCE_PATHS["manifest"]][1], "conversion manifest")
        if value_sha256(manifest.get("generation_inventory")) != value_sha256(record["inventory"]):
            raise ParityError("Canonical manifest inventory mismatch")
        attempt = _canonical_record(files[_EVIDENCE_PATHS["attempt"]][1], "conversion attempt")
        canonical = snapshot_object(attempt.get("canonical_manifest"), "canonical manifest binding")
        manifest_receipt = receipts[_EVIDENCE_PATHS["manifest"]]
        if canonical.get("updated") is not True or (canonical.get("path"), canonical.get("status"), canonical.get("current_output"), canonical.get("sha256")) != (
            _EVIDENCE_PATHS["manifest"], "updated", "verified", None if manifest_receipt is None else manifest_receipt["sha256"]
        ):
            raise ParityError("Conversion attempt and manifest binding mismatch")
    return receipts


def _normalized_generation(record: Mapping[str, object]) -> dict[str, object]:
    result = dict(record)
    result["transaction_id"] = "<transaction-id>"
    result["destination_identity"] = _IDENTITY_MARKER
    result["managed_identities"] = [
        [cast(list[object], row)[0], *_IDENTITY_MARKER]
        for row in _json_list(record["managed_identities"], "managed identities")
    ]
    result["evidence"] = {
        key: {**snapshot_object(value, "evidence"), "identity": (
            None if snapshot_object(value, "evidence")["identity"] is None else _IDENTITY_MARKER
        )}
        for key, value in snapshot_object(record["evidence"], "evidence").items()
    }
    return result


def _normalized_reference(value: object, role: str) -> dict[str, object]:
    return {
        **snapshot_object(value, "reference"),
        "name": f".gm2godot-managed-output-generation-<transaction-id>-{role}.json",
        "identity": _IDENTITY_MARKER, "sha256": "<verified-generation-digest>",
    }


def _validated_publication(
    files: Mapping[str, tuple[int, bytes]], definition: DestinationDefinition,
    observation: Mapping[str, object],
) -> list[object]:
    if frozenset(definition.volatile_transaction_fields) != _VOLATILE_FIELDS:
        raise ParityError("Unsupported volatile transaction fields")
    observed, record_identities = _observed_records(observation)
    public_identities = snapshot_object(observation.get("public_identities"), "public identities")
    directory_identities = snapshot_object(observation.get("directory_identities"), "directory identities")
    directory_modes = snapshot_object(observation.get("directory_modes"), "directory modes")
    destination_identity = _identity(observation.get("destination_identity"))
    parent_identity = _identity(observation.get("parent_identity"))
    root = definition.transaction_root
    marker_path, pointer_path, journal_path = (f"{root}/{name}" for name in (_MARKER_NAME, _POINTER_NAME, _JOURNAL_NAME))
    for path in (marker_path, pointer_path, journal_path):
        if path not in observed:
            raise ParityError(f"Missing observed publication record {path}")
    marker = _exact_object(_canonical_record(observed[marker_path][1], "workspace marker", compact=True), {
        "format_version", "kind", "destination_identity", "parent_identity",
    }, "workspace marker")
    _format_version(marker["format_version"])
    if (marker["format_version"], marker["kind"]) != (1, "gm2godot-managed-output-workspace-parent") or _identity(marker["destination_identity"]) != destination_identity or _identity(marker["parent_identity"]) != parent_identity:
        raise ParityError("Workspace marker identity mismatch")
    pointer = _exact_object(_canonical_record(observed[pointer_path][1], "pointer"), {
        "format_version", "kind", "state", "transaction_id", "destination_identity", "journal_sha256", "generation_record",
    }, "pointer")
    _format_version(pointer["format_version"])
    transaction_id = pointer["transaction_id"]
    if not isinstance(transaction_id, str) or re.fullmatch(r"[0-9a-f]{32}", transaction_id) is None:
        raise ParityError("Invalid publication transaction ID")
    if (pointer["format_version"], pointer["kind"], pointer["state"]) != (1, "gm2godot-managed-output-generation", "committed") or _identity(pointer["destination_identity"]) != destination_identity:
        raise ParityError("Invalid committed publication pointer")
    if pointer["journal_sha256"] != _digest(observed[journal_path][1]):
        raise ParityError("Pointer journal digest mismatch")
    journal = _exact_object(_canonical_record(observed[journal_path][1], "journal"), {
        "format_version", "kind", "state", "transaction_id", "destination_identity",
        "workspace_parent_identity", "stage_identity", "publication_identity", "previous_record",
        "desired_record", "previous_pointer", "pointer_stage_identity", "directories", "transitions",
    }, "journal")
    _format_version(journal["format_version"])
    if (journal["format_version"], journal["kind"], journal["state"], journal["transaction_id"]) != (1, "gm2godot-managed-output-transaction", "prepared", transaction_id) or _identity(journal["destination_identity"]) != destination_identity or _identity(journal["workspace_parent_identity"]) != parent_identity or journal["previous_pointer"] is not None:
        raise ParityError("Journal transaction, destination or reset-state mismatch")
    for key in ("stage_identity", "publication_identity"):
        if _identity(journal[key]) != _identity(observation.get(key)):
            raise ParityError("Journal private directory identity mismatch")
    if _identity(journal["pointer_stage_identity"]) != record_identities[pointer_path]:
        raise ParityError("Journal pointer-stage identity mismatch")
    desired_path = _validate_reference(pointer["generation_record"], observed, record_identities, root, transaction_id, "desired")
    if journal["desired_record"] != pointer["generation_record"]:
        raise ParityError("Journal desired reference and pointer disagree")
    previous_path = _validate_reference(journal["previous_record"], observed, record_identities, root, transaction_id, "previous")
    desired, desired_entries = _validate_generation(desired_path, observed[desired_path][1], transaction_id, "desired", destination_identity)
    previous, previous_entries = _validate_generation(previous_path, observed[previous_path][1], transaction_id, "previous", destination_identity)
    for path, receipt in desired_entries.items():
        if path not in files or receipt != _file_receipt(files[path]):
            raise ParityError(f"Managed inventory does not match output bytes or mode: {path}")
    for row in _json_list(desired["managed_identities"], "managed identities"):
        values = cast(list[object], row)
        if _identity(values[1:]) != _identity(public_identities.get(cast(str, values[0]))):
            raise ParityError("Managed identity does not match observed public file")
    previous_receipts = {**previous_entries, **_validate_evidence(previous, files, public_identities, desired=False)}
    desired_receipts = {**desired_entries, **_validate_evidence(desired, files, public_identities, desired=True)}
    if set(public_identities) != set(desired_entries) | set(_EVIDENCE_PATHS.values()) | {marker_path, pointer_path, desired_path}:
        raise ParityError("Observed public identity inventory mismatch")
    for path in (marker_path, pointer_path, desired_path):
        if _identity(public_identities[path]) != record_identities[path]:
            raise ParityError("Observed publication record identity mismatch")
    backups, backup_identities = _observed_records({"files": observation.get("backup_files")})
    _validate_journal_rows(
        journal, previous_receipts, desired_receipts, directory_identities,
        directory_modes, _generation_identities(previous), _generation_identities(desired), backups, backup_identities,
    )
    expected_records = {marker_path, pointer_path, desired_path, definition.transaction_lock}
    if {path for path in files if _is_transaction_path(path, definition)} != expected_records:
        raise ParityError("Successful publication has missing or unexpected transaction records")
    if set(observed) != {marker_path, pointer_path, journal_path, desired_path, previous_path}:
        raise ParityError("Unexpected observed publication records")
    for path in (marker_path, pointer_path, desired_path):
        if files[path] != observed[path]:
            raise ParityError("Publication record changed after observation")
    normalized_pointer = {**pointer, "transaction_id": "<transaction-id>", "destination_identity": _IDENTITY_MARKER,
                          "journal_sha256": "<verified-journal-digest>", "generation_record": _normalized_reference(pointer["generation_record"], "desired")}
    normalized_marker = {**marker, "destination_identity": _IDENTITY_MARKER, "parent_identity": _IDENTITY_MARKER}
    normalized_journal = _normalized_journal(journal)
    semantics: list[object] = [{"record_path": definition.transaction_lock, "mode": files[definition.transaction_lock][0], "bytes": files[definition.transaction_lock][1].hex()}]
    for path, content in ((marker_path, normalized_marker), (pointer_path, normalized_pointer),
                          (journal_path, normalized_journal), (desired_path, _normalized_generation(desired)),
                          (previous_path, _normalized_generation(previous))):
        normalized_name = _GENERATION_NAME.sub(lambda match: f".gm2godot-managed-output-generation-<transaction-id>-{match.group(2)}.json", path.split("/")[-1])
        semantics.append({"record_path": f"{root}/{normalized_name}",
                          "mode": observed[path][0], "content": content})
    return semantics


def _validate_journal_rows(
    journal: Mapping[str, object], previous: Mapping[str, object], desired: Mapping[str, object],
    directory_identities: Mapping[str, object],
    directory_modes: Mapping[str, object],
    previous_identities: Mapping[str, object], desired_identities: Mapping[str, object],
    backups: Mapping[str, tuple[int, bytes]], backup_identities: Mapping[str, list[str]],
) -> None:
    directories = _json_list(journal["directories"], "journal directories")
    names: list[str] = []
    for raw_directory in directories:
        directory = _exact_object(raw_directory, {"path", "disposition", "identity", "mode", "stage_path"}, "journal directory")
        path = _relative_path(directory["path"])
        names.append(path)
        if directory["disposition"] not in {"existing", "staged"} or _identity(directory["identity"]) != _identity(directory_identities.get(path)):
            raise ParityError("Journal directory identity or disposition mismatch")
        if type(directory["mode"]) is not int or not 0 <= directory["mode"] <= 0o7777 or directory["mode"] != directory_modes.get(path):
            raise ParityError("Invalid journal directory mode")
        expected_stage = None if directory["disposition"] == "existing" else f".gm2godot-publication/directories/{path}"
        if directory["stage_path"] != expected_stage:
            raise ParityError("Journal directory stage path mismatch")
    if names != sorted(set(names)) or set(names) != set(directory_identities) or set(names) != set(directory_modes):
        raise ParityError("Journal directory inventory mismatch")
    names = []
    backup_names: set[str] = set()
    transition_keys: list[tuple[int, str]] = []
    for raw_transition in _json_list(journal["transitions"], "journal transitions"):
        row = _exact_object(raw_transition, {"path", "kind", "previous", "desired", "previous_public_identity", "backup", "desired_stage", "backup_path", "desired_stage_path", "displaced_path"}, "journal transition")
        path = _relative_path(row["path"])
        names.append(path)
        kind = row["kind"]
        if not isinstance(kind, str) or kind not in {"managed", "attempt", "manifest"} or (kind != "managed" and path != _EVIDENCE_PATHS[kind]) or (kind == "managed" and path in _EVIDENCE_PATHS.values()):
            raise ParityError("Journal transition kind or path mismatch")
        transition_keys.append(({"managed": 0, "attempt": 1, "manifest": 2}[kind], path))
        suffix = path if kind == "managed" else f"conversion_{kind}.json"
        expected_paths = {"backup_path": f".gm2godot-publication/backups/{suffix}", "desired_stage_path": path if kind == "managed" else f".gm2godot-publication/evidence/desired-{kind}.json", "displaced_path": f".gm2godot-publication/displaced/{suffix}"}
        if any(row[key] != value for key, value in expected_paths.items()) or row["previous"] != previous.get(path) or row["desired"] != desired.get(path):
            raise ParityError("Journal transition content or private path mismatch")
        for value_key, receipt_key, private_path in (("previous", "backup", "backup_path"), ("desired", "desired_stage", "desired_stage_path")):
            receipt = row[value_key]
            actual = row[receipt_key]
            if receipt is None:
                if actual is not None:
                    raise ParityError("Unexpected journal file receipt")
            else:
                actual_mapping = _exact_object(actual, {"path", "identity", "mode", "byte_count", "sha256"}, "journal file receipt")
                _identity(actual_mapping["identity"])
                if actual_mapping["path"] != row[private_path] or _content_receipt({key: actual_mapping[key] for key in ("mode", "byte_count", "sha256")}) != _content_receipt(receipt):
                    raise ParityError("Journal file receipt binding mismatch")
                if receipt_key == "backup":
                    backup_path = cast(str, actual_mapping["path"])
                    backup_names.add(backup_path)
                    if backup_path not in backups or _file_receipt(backups[backup_path]) != receipt or _identity(actual_mapping["identity"]) != backup_identities[backup_path]:
                        raise ParityError("Journal backup bytes or identity mismatch")
                elif _identity(actual_mapping["identity"]) != _identity(desired_identities.get(path)):
                    raise ParityError("Journal desired-stage and generation identity mismatch")
        if row["previous"] is None:
            if row["previous_public_identity"] is not None:
                raise ParityError("Unexpected previous public identity")
        else:
            if _identity(row["previous_public_identity"]) != _identity(previous_identities.get(path)):
                raise ParityError("Journal previous-public and generation identity mismatch")
    if transition_keys != sorted(transition_keys) or len(names) != len(set(names)) or set(names) != {path for path in set(previous) | set(desired) if previous.get(path) is not None or desired.get(path) is not None}:
        raise ParityError("Journal transition inventory mismatch")
    if backup_names != set(backups):
        raise ParityError("Observed backup inventory mismatch")


def _normalized_journal(journal: Mapping[str, object]) -> dict[str, object]:
    result = dict(journal)
    result["transaction_id"] = "<transaction-id>"
    for key in ("destination_identity", "workspace_parent_identity", "stage_identity", "publication_identity", "pointer_stage_identity"):
        result[key] = _IDENTITY_MARKER
    for role in ("previous", "desired"):
        result[f"{role}_record"] = _normalized_reference(journal[f"{role}_record"], role)
    result["directories"] = [{**snapshot_object(row, "directory"), "identity": _IDENTITY_MARKER} for row in _json_list(journal["directories"], "directories")]
    transitions: list[object] = []
    for value in _json_list(journal["transitions"], "transitions"):
        row = dict(snapshot_object(value, "transition"))
        if row["previous_public_identity"] is not None:
            row["previous_public_identity"] = _IDENTITY_MARKER
        for key in ("backup", "desired_stage"):
            if row[key] is not None:
                row[key] = {**snapshot_object(row[key], key), "identity": _IDENTITY_MARKER}
        transitions.append(row)
    result["transitions"] = transitions
    return result


def _json_bytes(contents: bytes, label: str) -> object:
    try:
        return json.loads(contents.decode("utf-8"), object_pairs_hook=_unique_json_pairs)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ParityError(f"{label} is not valid UTF-8 JSON: {error}") from error


def _unique_json_pairs(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ParityError(f"Duplicate JSON field: {key}")
        result[key] = value
    return result


def snapshot_object(value: object, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ParityError(f"{label} must be a JSON object")
    raw = cast(dict[object, object], value)
    return {str(key): item for key, item in raw.items()}


def _json_list(value: object, label: str) -> list[object]:
    if not isinstance(value, list):
        raise ParityError(f"{label} must be a JSON list")
    return list(cast(list[object], value))
