"""Capture and compare generated bytes and stable conversion snapshot fields.

This module reads output files but never launches converters or Godot, mutates a
conversion destination, exports a Git tree, or writes parity receipts.
"""

from __future__ import annotations

import json
import stat
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import cast

from scripts.conversion_parity_contract import (
    DestinationDefinition,
    FixtureDefinition,
    ParityError,
    value_sha256,
)


@dataclass(frozen=True)
class FixtureRun:
    destination: str
    files: dict[str, tuple[int, bytes]]
    snapshot: dict[str, object]


def compare_fixture_runs(
    base: FixtureRun,
    head: FixtureRun,
    fields: Sequence[str],
) -> dict[str, dict[str, str]]:
    """Compare exact output bytes and normalized transaction semantics."""
    if base.destination != head.destination:
        raise ParityError(
            f"Destination mismatch before comparison: {base.destination!r} != {head.destination!r}"
        )
    differences: dict[str, dict[str, str]] = {}
    for field in fields:
        base_value, head_value = _comparison_values(field, base, head)
        if base_value != head_value:
            differences[field] = {
                "base_sha256": _comparison_sha(field, base_value),
                "head_sha256": _comparison_sha(field, head_value),
            }
    return differences


def validate_expected_outcome(snapshot: Mapping[str, object], fixture: FixtureDefinition) -> None:
    if fixture.expected_outcome_state is None and fixture.expected_skipped_resources is None:
        return
    diagnostics = snapshot_object(snapshot["diagnostics"], "conversion diagnostics")
    outcome = snapshot_object(diagnostics.get("outcome"), "conversion outcome")
    if fixture.expected_outcome_state is not None:
        state = outcome.get("state")
        if state != fixture.expected_outcome_state:
            raise ParityError(
                f"{fixture.identifier} outcome mismatch: expected {fixture.expected_outcome_state!r}, got {state!r}"
            )
    if fixture.expected_skipped_resources is not None:
        resources = snapshot_object(outcome.get("resources"), "conversion resources")
        skipped = resources.get("skipped")
        if skipped != fixture.expected_skipped_resources:
            raise ParityError(
                f"{fixture.identifier} skipped-resource mismatch: expected {fixture.expected_skipped_resources}, got {skipped!r}"
            )


def collect_output_files(destination: Path) -> dict[str, tuple[int, bytes]]:
    """Capture every generated file's exact bytes and mode without following links."""
    files: dict[str, tuple[int, bytes]] = {}
    for path in sorted(destination.rglob("*")):
        if path.is_symlink():
            raise ParityError(f"Parity output must not contain a symlink: {path}")
        if path.is_dir():
            continue
        relative = path.relative_to(destination).as_posix()
        files[relative] = (stat.S_IMODE(path.stat().st_mode), path.read_bytes())
    return files


def output_snapshot(
    files: Mapping[str, tuple[int, bytes]],
    *,
    destination: Path,
    definition: DestinationDefinition,
    stdout: str,
    stderr: str,
    exit_status: int,
    parser_error: Mapping[str, object],
    runtime_markers: Mapping[str, object],
) -> dict[str, object]:
    """Select visible outputs and fully capture managed-output transaction semantics."""
    visible = {
        path: record
        for path, record in files.items()
        if not _is_transaction_path(path, definition)
    }
    return {
        "relative_paths": sorted(visible),
        "file_bytes": {path: sha256(contents).hexdigest() for path, (_, contents) in visible.items()},
        "modes": {path: mode for path, (mode, _) in visible.items()},
        "generated_gdscript": {
            path: sha256(contents).hexdigest()
            for path, (_, contents) in visible.items()
            if path.endswith(".gd")
        },
        "source_maps": _json_outputs(visible, suffix=".gmlmap.json"),
        "diagnostics": _diagnostics_snapshot(visible),
        "diagnostic_ids": _diagnostic_ids(visible),
        "parser_error": dict(parser_error),
        "stdout": stdout,
        "stderr": stderr,
        "exit_status": exit_status,
        "terminal_output_state": _terminal_output_state(visible, destination),
        "transaction_provenance": _transaction_provenance_snapshot(files, definition),
        "runtime_markers": dict(runtime_markers),
    }


def _transaction_provenance_snapshot(
    files: Mapping[str, tuple[int, bytes]],
    definition: DestinationDefinition,
) -> dict[str, object]:
    """Retain raw records, modes, IDs, and normalized stable transaction semantics."""
    raw: dict[str, object] = {}
    semantics: list[object] = []
    for path, (mode, contents) in files.items():
        if not _is_transaction_path(path, definition):
            continue
        raw[path] = {
            "mode": mode,
            "size": len(contents),
            "sha256": sha256(contents).hexdigest(),
            "content": _transaction_content(contents, path),
        }
        record_path = _normalized_transaction_path(path, definition)
        if path == definition.transaction_lock:
            semantics.append(
                {"record_path": record_path, "mode": mode, "bytes": contents.hex()}
            )
        elif path.startswith(f"{definition.transaction_root}/"):
            semantics.append(
                {
                    "record_path": record_path,
                    "mode": mode,
                    "content": _normalize_transaction_record(
                        _json_bytes(contents, path),
                        definition.volatile_transaction_fields,
                    ),
                }
            )
    return {"raw": raw, "semantics": sorted(semantics, key=value_sha256)}


def _normalized_transaction_path(path: str, definition: DestinationDefinition) -> str:
    prefix = f"{definition.transaction_root}/.gm2godot-managed-output-generation-"
    suffix = "-desired.json"
    if path.startswith(prefix) and path.endswith(suffix):
        return f"{prefix}<transaction-id>{suffix}"
    return path


def _comparison_values(
    field: str,
    base: FixtureRun,
    head: FixtureRun,
) -> tuple[object, object]:
    if field == "file_bytes":
        return _visible_file_bytes(base), _visible_file_bytes(head)
    if field == "modes":
        return _visible_file_modes(base), _visible_file_modes(head)
    if field == "transaction_provenance":
        return _transaction_semantics(base), _transaction_semantics(head)
    if field not in base.snapshot or field not in head.snapshot:
        raise ParityError(f"Unknown parity field {field!r}")
    return base.snapshot[field], head.snapshot[field]


def _comparison_sha(field: str, value: object) -> str:
    if field == "file_bytes":
        bytes_by_path = cast(dict[str, bytes], value)
        return value_sha256({path: sha256(contents).hexdigest() for path, contents in bytes_by_path.items()})
    return value_sha256(value)


def serialize_fixture_run(run: FixtureRun) -> dict[str, object]:
    return {
        "destination": run.destination,
        "files": {
            path: {"mode": mode, "size": len(contents), "sha256": sha256(contents).hexdigest()}
            for path, (mode, contents) in run.files.items()
        },
        "snapshot": run.snapshot,
    }


def _json_outputs(
    files: Mapping[str, tuple[int, bytes]],
    *,
    suffix: str,
) -> dict[str, object]:
    return {
        path: _json_bytes(contents, path)
        for path, (_, contents) in files.items()
        if path.endswith(suffix)
    }


def _diagnostics_snapshot(files: Mapping[str, tuple[int, bytes]]) -> object:
    entry = files.get("gm2godot/conversion_diagnostics.json")
    return {"diagnostics": []} if entry is None else _json_bytes(entry[1], "conversion_diagnostics.json")


def _diagnostic_ids(files: Mapping[str, tuple[int, bytes]]) -> list[str]:
    diagnostics = snapshot_object(_diagnostics_snapshot(files), "conversion diagnostics")
    identifiers: list[str] = []
    for raw_item in _json_list(diagnostics.get("diagnostics"), "conversion diagnostics entries"):
        item = snapshot_object(raw_item, "conversion diagnostics entry")
        code = item.get("code")
        if not isinstance(code, str):
            raise ParityError("conversion diagnostics entries must have string codes")
        identifiers.append(code)
    return identifiers


def _terminal_output_state(
    files: Mapping[str, tuple[int, bytes]],
    destination: Path,
) -> dict[str, object]:
    names = (
        "gm2godot/conversion_attempt.json",
        "gm2godot/conversion_manifest.json",
        "gm2godot/architecture_policy.json",
    )
    return {
        "destination": str(destination),
        "records": {
            name: _json_bytes(files[name][1], name)
            for name in names
            if name in files
        },
    }


def _is_transaction_path(path: str, definition: DestinationDefinition) -> bool:
    return path == definition.transaction_lock or path.startswith(f"{definition.transaction_root}/")


def _transaction_content(contents: bytes, path: str) -> object:
    if path.endswith(".lock"):
        return {"bytes_hex": contents.hex()}
    return _json_bytes(contents, path)


def _normalize_transaction_record(value: object, volatile_fields: Sequence[str]) -> object:
    return _normalize_transaction_value(value, volatile_fields, ())


def _normalize_transaction_value(
    value: object,
    volatile_fields: Sequence[str],
    path: tuple[str, ...],
) -> object:
    if isinstance(value, dict):
        result: dict[str, object] = {}
        for raw_key, child in cast(dict[object, object], value).items():
            key = str(raw_key)
            child_path = (*path, key)
            dotted = ".".join(child_path)
            if key in volatile_fields or dotted in volatile_fields:
                result[key] = {"volatile_shape": _volatile_shape(child)}
            else:
                result[key] = _normalize_transaction_value(child, volatile_fields, child_path)
        return result
    if isinstance(value, list):
        return [
            _normalize_transaction_value(item, volatile_fields, path)
            for item in cast(list[object], value)
        ]
    return value


def _volatile_shape(value: object) -> object:
    if isinstance(value, str):
        return {"type": "string", "length": len(value), "hex": _is_hex(value)}
    if isinstance(value, list):
        return {
            "type": "list",
            "items": [_volatile_shape(item) for item in cast(list[object], value)],
        }
    return {"type": type(value).__name__}


def _is_hex(value: str) -> bool:
    return bool(value) and all(character in "0123456789abcdef" for character in value.casefold())


def _visible_file_bytes(run: FixtureRun) -> dict[str, bytes]:
    paths = cast(list[str], run.snapshot["relative_paths"])
    return {path: run.files[path][1] for path in paths}


def _visible_file_modes(run: FixtureRun) -> dict[str, int]:
    paths = cast(list[str], run.snapshot["relative_paths"])
    return {path: run.files[path][0] for path in paths}


def _transaction_semantics(run: FixtureRun) -> object:
    provenance = snapshot_object(run.snapshot["transaction_provenance"], "transaction provenance")
    return provenance["semantics"]


def _json_bytes(contents: bytes, label: str) -> object:
    try:
        return json.loads(contents.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ParityError(f"{label} is not valid UTF-8 JSON: {error}") from error


def snapshot_object(value: object, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ParityError(f"{label} must be a JSON object")
    raw = cast(dict[object, object], value)
    return {str(key): item for key, item in raw.items()}


def _json_list(value: object, label: str) -> list[object]:
    if not isinstance(value, list):
        raise ParityError(f"{label} must be a JSON list")
    return list(cast(list[object], value))
